### ISSUE TITLE
Implement 404 Page

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#118]
**Is your feature request related to a problem? Please describe.**
Whenever a user requests an URL that is not routed in our application a white page turns up. 

**Describe the solution you'd like**
Building a custom 404 page which routes back to our home page after a time-lapse of 5 seconds. It should also have a button to navigate to the home page for an instant move route to the home page. 

**Additional context**
The 404 page should have a soothing UI and must be responsive. A fancy yet interesting text that might give the end-user a laugh when they hit the page would make the application a bit interactive.

<img width="664" alt="404 Page IHR Skeleton" src="https://user-images.githubusercontent.com/67703407/164004311-7fb4f78e-0755-4446-a024-f055229bacc8.png">

This is the basic skeleton of how I have planned to implement the 404 page, feel free to share your thoughts along with the UI. Once we have finalized the UI feel free to code. 

PS. If you want to solve this issue comment on this issue. Please start working on the issue after you are assigned. Do note this issue is marked as `first-timers-only`, so if you have not contributed before we encourage you to work on this and get to know about IHR's workflow :)

**Comment by femitosin** [comment]
Will there be design for the 404 page ? If yes, how will i get access to the design?

**Comment by aryan-surin** [comment]
Hey @Aniket762 can I contribute to this issue?

**Comment by Aniket762** [comment]
> Hey @Aniket762 can I contribute to this issue?

For sure, do you want me to assign this issue to you? By the way, is there any particular UI that you have thought about?

**Comment by thisiskaransgit** [comment]
I'll work on this issue 
and since you gave the additional context for the UI , I will be making it while keeping the context in mind 
> The 404 page should have a soothing UI and must be responsive. A fancy yet interesting text that might give the end-user a laugh when they hit the page would make the application a bit interactive.

**Comment by Aniket762** [comment]
> I'll work on this issue and since you gave the additional context for the UI , I will be making it while keeping the context in mind
> 
> > The 404 page should have a soothing UI and must be responsive. A fancy yet interesting text that might give the end-user a laugh when they hit the page would make the application a bit interactive.

Okay, that sounds great :) since we haven't heard back from @aryan-surin as of now. Let's wait for a day, if he doesn't get back I would assign you and you can start working. Till then you may check out #33, a pretty beginner-friendly issue. Let me know your thoughts :)

**Comment by Aniket762** [comment]
> I'll work on this issue and since you gave the additional context for the UI , I will be making it while keeping the context in mind
> 
> > The 404 page should have a soothing UI and must be responsive. A fancy yet interesting text that might give the end-user a laugh when they hit the page would make the application a bit interactive.

Hi, do you still want to work on this?

**Comment by thisiskaransgit** [comment]
> 

Yes , I'll work on this

**Comment by Aniket762** [comment]
Hi @thisiskaransgit, take your time and share a basic wireframe you want to develop, and once we have concluded the layout you can code. In case, you don't want to design you can implement the skeleton which I have given while creating the issue. Let me know, which way you are going? :)

**Comment by thisiskaransgit** [comment]
![1](https://user-images.githubusercontent.com/92504666/164965311-aa2ed5f8-fc2f-49a8-a3e6-48d9a242e55b.PNG)
This is the design that I came up with ,  If you like it then I can start working on the coding part, or if you have some more suggestion to add to it ,or the design is not up to the mark ,let me know.🤝

**Comment by Aniket762** [comment]
> ![1](https://user-images.githubusercontent.com/92504666/164965311-aa2ed5f8-fc2f-49a8-a3e6-48d9a242e55b.PNG) This is the design that I came up with , If you like it then I can start working on the coding part, or if you have some more suggestion to add to it ,or the design is not up to the mark ,let me know.🤝

Your design looks great, specially with the button part. But, I would say for now, go with the skeleton I have provided then we can make changes accordingly. You button looks good, so keep it that way round in the skeleton. 

![image](https://user-images.githubusercontent.com/67703407/164967443-7a0264f4-7c5c-44c3-8bad-7efe8a0656b5.png)

Make sure to keep it responsive in Desktop, mobile and tab view. Since, the deployment bot is still in process, it will be great if you can send the PR while attaching the screenshots and URLs you have tested

**Comment by thisiskaransgit** [comment]
I am done with coding part and the page is ready and looks just the same as we discussed 
![404](https://user-images.githubusercontent.com/92504666/165154295-823368b3-a3c2-43f1-9c43-5294301ad641.png)
It's responsive in Desktop, mobile and tab view. 

But I was unable to run it in my local host as  I was repeatedly getting the following error
![Screenshot 2022-04-25 230023](https://user-images.githubusercontent.com/92504666/165155238-7d51e036-b6b1-4e13-8121-20299385e962.png)

**Comment by Aniket762** [comment]
> I am done with coding part and the page is ready and looks just the same as we discussed ![404](https://user-images.githubusercontent.com/92504666/165154295-823368b3-a3c2-43f1-9c43-5294301ad641.png) It's responsive in Desktop, mobile and tab view.
> 
> But I was unable to run it in my local host as I was repeatedly getting the following error ![Screenshot 2022-04-25 230023](https://user-images.githubusercontent.com/92504666/165155238-7d51e036-b6b1-4e13-8121-20299385e962.png) I have tried it multiple times in every way I could look but the result was same

Hey @thisiskaransgit, thanks a lot for coding the wireframe, it looks great to me ✨

I am extremely sorry to know that, you were not able to run the code on your localhost. After reading your error I immediately did a dry run on my system, and it ran without any error. There are some things that you can try out to fix this error:
1. Install the LTS versions of Vue-CLI and Node
2. Try removing the node modules directory and do a clean install with`npm ci` command. 

Please let me know if you face any problems in the process! We would try to resolve your error together :)

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 
I have successfully tested it locally with several URL and it's working just as we wanted  
 1. Whenever the user requests a invalid URL our custom 404 page appears
 2. redirect button takes us to the home page 
 3.  The design is same as we discussed

The only issue is that the page is not getting responsive for mobile and tablet view as it's not taking effect on a single page 
and was implementing changes throughout the app which were giving error so  I didn't applied them.

So should I send the PR ?

**Comment by thisiskaransgit** [comment]
Thanks @Aniket762  for the approval , It's really for me exciting as it's my first Successful PR. I would like to continue to contribute to this project more as it's in my field of interest  , so can you guide and share some resources me which can help me to get to know more about this project. 
Thank You

**Comment by Aniket762** [comment]
> Thanks @Aniket762 for the approval , It's really for me exciting as it's my first Successful PR. I would like to continue to contribute to this project more as it's in my field of interest , so can you guide and share some resources me which can help me to get to know more about this project. Thank You

Thanks, @thisiskaransgit for your kind words. You can join our slack which we are opening up for contributors. Please click![here]( https://join.slack.com/t/internethealthreport/shared_invite/zt-19d4e48py-~oirVwkINe01gTVEF3o4Kw) to join the slack. 

Although, I reverted back the PR, I guess it broke the prod. I would check it and merge it again. In the meantime, you join slack get onboarded and let's meet soon. What say?
