### ISSUE TITLE
Error message for unknown resources

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#124]
**Is your feature request related to a problem? Please describe.**
When opening a report for a resource that does not exists, the page just show the loading message.

**Describe the solution you'd like**
It would be nice to have a default message saying that the queried network/AS doesn't exists

**Additional context**
An example is available here: [https://ihr.iijlab.net/ihr/en-us/networks/AS74598](https://ihr.iijlab.net/ihr/en-us/networks/AS74598?af=4&last=7&date=2022-05-08)

**Comment by yihu55** [comment]
fetch('https://api.github.com/users/hadley/orgs') //make the api unaccessble, the error message will appear
    .then(response=>{
           if(!response.ok){
                const div=document.createElement('div')
                const h1=document.createElement('h2')
                document.body.appendChild(div)
                div.appendChild(h1)
                h1.appendChild(document.createTextNode('page not found'))        
        }
       return response.json()
    })
    .then(data=>{console.log(data)})

**Comment by romain-fontugne** [comment]
Please send a Pull Request if you want to fix this issue, thanks!

**Comment by yihu55** [comment]
sorry I am absolutly newbie to open source, i will check out how things works!

**Comment by Abhay2342** [comment]
I can fix this issue for you.

**Comment by romain-fontugne** [comment]
@yihu55 are you planning to work on this issue? if not I'll assign it to @Abhay2342

**Comment by yihu55** [comment]
> @yihu55 are you planning to work on this issue? if not I'll assign it to @Abhay2342

sorry, please assign it to @Abhay2342.

**Comment by romain-fontugne** [comment]
OK thanks!

**Comment by Abhay2342** [comment]
In my local server, everything is working fine now. Please review my pull request.

![Capture](https://user-images.githubusercontent.com/73768090/168632248-0f625c04-3d94-46b3-8209-aed2ce1bf6e2.PNG)

**Comment by Aniket762** [comment]
Keeping this issue open for a while, in case @romain-fontugne needs some changes.

**Comment by Abhay2342** [comment]
If everything is fine then please close this issue.

**Comment by Aniket762** [comment]
> If everything is fine then please close this issue.

Thanks for your contribution 💖

 I am closing the issue as of now
