### ISSUE TITLE
UI improvements for AS-hegemony graphs

### ISSUE THREAD

**Issue by emileaben** [InternetHealthReport/ihr-website#126]
**Is your feature request related to a problem? Please describe.**
I often use IHR as-hegemony on slides. Some use-cases can be better:

** showing when a network disappears (ex. RIPE84 slide deck for Mariupol network)
In the graph show the timeline also for when there is no data (ie. if the query says 7 days before 2022-04-07 and there is no data 2022-04-02 and after, in that case still show the y-axis for 2022-04-02 up until 2022-04-07 but show that the network was not visible in the routing table.
** y-axis is percentage
Make it clear that the y-axis is a percentage (currently just says 100 ) for the hegemony scores.
The depending networks graph is NOT a percentage so should not be changed
** Different visual style for directly connected networks
Often you want to see if a network is directly connected to the network you are looking at or not. The difference between directly and indirectly connected networks could be visualised (for instnace the one type is a dotted line, the other not)

**Comment by emileaben** [comment]
ah, and
** use a step graph so it's clear when a dependency disappears (not a line graph)

**Comment by Aniket762** [comment]
Hey @emileaben, I have added some tags such that it will become easier for external contributors to find this issue. Hope you are okay with this 

Cheers!

**Comment by nimishmedatwal** [comment]
Hey i believe that i can fix this issue

**Comment by Aniket762** [comment]
> Hey i believe that i can fix this issue

You can go for it.

**Comment by Rithvik-padma** [comment]
@nimishmedatwal Are u still working on it? If not I would love to work on this issue. @Aniket762

**Comment by J0SAL** [comment]
Hey @Aniket762, if no one's working on this could you assign it to me? I would love to give it a shot. If not could you please suggest me some beginner-friendly issues, to help me get started

**Comment by romain-fontugne** [comment]
@nimishmedatwal any update on this? If you don't have time for this someone else could try it

**Comment by nimishmedatwal** [comment]
if anyone else is willing to work on this, go for it

**Comment by Rithvik-padma** [comment]
@romain-fontugne  I can try solving this issue can u assign this to me

**Comment by romain-fontugne** [comment]
Go for it @Rithvik-padma

**Comment by anishbasnet027** [comment]
Hello, I want to work on this issue, can you please assign me? @romain-fontugne

**Comment by romain-fontugne** [comment]
I think @Rithvik-padma is currently working on this

**Comment by ConnectBhawna** [comment]
@Rithvik-padma are you working on this issue?

**Comment by Rithvik-padma** [comment]
@ConnectBhawna yes I just started working on this if I couldn't resolve it I will inform in this issue.

**Comment by niladrix719** [comment]
can i work on this?

**Comment by Rithvik-padma** [comment]
@niladrix719 I am currently working on this issue, if I am not able to resolve it I will inform here

**Comment by Rithvik-padma** [comment]
Hey @romain-fontugne @Aniket762 sorry for the delay I actually forgot about this issue 🤦‍♂️, I found that the first issue is already implemented or maybe I interpreted it in the wrong way so I am sharing an image, please review whether this is the expected result or not
![image](https://user-images.githubusercontent.com/99183441/225437447-b73cbcf9-cd36-4533-a8b8-aae85fb8b8f1.png)
Second issue is resolved - I have changed the y-axis values to percentages for the AS-dependency chart
Third issue - I have actually tried to know how to differentiate between direct and indirect connected networks (by looking around the codebase and API params) but I couldn't find any parameters for it. 
It would be great if someone can help me out on how to address the third issue or they can work on this if they already have the right approach.
I am making a PR that solves the second issue ie Changing the y-axis values to percentages.

**Comment by AyeshaLoladia** [comment]
HIi @romain-fontugne, Is anyone currently working on this issue? If not, I'd like to solve it. Please assign it to me.

**Comment by 0xAnon0602** [comment]
Hi @dpgiakatos 
Could you explain what is left to be done on this issue? I'm not fully understanding it.

**Comment by romain-fontugne** [comment]
There is multiple things here. And before explaining them, I will add another wish:

1. We need two different labels: one label is 'no data' if there was problem with IHR and we don't have data for the selected AS and time period. The other label is 'network unreachable' if IHR worked as usual but the selected network is actually completely disconnected from the Internet. To make the difference between the two cases, we can make a API call with orginasn=0 and a very large ASN (e.g. 2914):
https://ihr.iijlab.net/ihr/api/hegemony/?timebin__lte=2024-04-17T12%3A00&timebin__gte=2024-04-17T00%3A00&af=4&asn=2914&originasn=0
If this API call returns data that means IHR was working.
I think this is partially implemented but it is actually not working.

2. after implementing 1. we can show the "no data" or "network unreachable" label if the user goes to a page where we have no data to show. For example: https://ihr.iijlab.net/ihr/en-us/networks/AS2497?af=4&last=3&date=2001-04-01&rov_tb=routes should show "no data"

3. the last one is to show in the graph which ASes are directly connected to the monitored AS. For example, here https://ihr.iijlab.net/ihr/en-us/networks/AS2501?rov_tb=routes&af=4&last=3&date=2024-04-18&hege_tb=dependency&hege_dt=2024-04-16%2011%3A00 
we want to show (with a different line style, or a marker, etc..?) that AS2907 is directly connected

**Comment by 0xAnon0602** [comment]
I would like to work on this 
Please assign this to me

**Comment by romain-fontugne** [comment]
sure, let me know if it's unclear

**Comment by 0xAnon0602** [comment]
@romain-fontugne 
I still can't understand the key difference in "no data" and "network unreachable"
Can you please explain it little more to me 
Thanks )

**Comment by dpgiakatos** [comment]
Let me explain how the IHR project operates and clarify the key difference between "no data" and "network unreachable" using an example (though the actual pipeline is more complex, I'll simplify it here). The IHR website serves as our frontend, displaying data from both the IHR backend and IYP. For this particular issue, you only need to focus on the IHR backend. This backend comprises various services that gather and analyze network data from multiple sources, such as RIPE Atlas.

If any of our services are offline, the IHR backend cannot collect network data, resulting in a "no data" response on the frontend (please let me know if this scenario is clear).

As mentioned earlier, we gather network data from various sources. For instance, let's consider the collection of AS2497 prefixes. Through our service, we request RIPE to provide the prefixes for AS2497. RIPE attempts to retrieve the prefixes from AS2497, but for some unknown reason, AS2497 is currently offline or unreachable from the internet, preventing us from obtaining the requested data. In such cases, the frontend should display "network unreachable" (please let me know if this scenario is clear).

I hope this explanation clarifies things.

**Comment by 0xAnon0602** [comment]
So as @romain-fontugne mentioned above to find out if it is - 

**No-Data**
> First send an API request to 
https://ihr.iijlab.net/ihr/api/hegemony/?format=json&timebin__lte=2024-04-17T12%3A00&timebin__gte=2024-04-17T00%3A00&af=4&asn=2497&originasn=0

>If the result array from the above response is not empty that means the network is reachable 
Then send the API request to the AS I want data for and if the result of that is empty then it means it is a "No-Data" case.


**Network-Unreachable**
>  Send API request to 
https://ihr.iijlab.net/ihr/api/hegemony/?format=json&timebin__lte=2024-04-17T12%3A00&timebin__gte=2024-04-17T00%3A00&af=4&asn=2497&originasn=0

> If the result array from the above response is empty that means the network is unreachable.

Am I thinking in the right direction?

**Comment by romain-fontugne** [comment]
Nope, for the extra API call with originasn=0, we want to use a different AS. Above I gave 2914 as an example of one network where we also expect a results (AS2914 is a Tier1 network, one of the core network for the Internet, we expect it to be always connected to the Internet). You can actually use more than one network for this test:
https://ihr.iijlab.net/ihr/api/hegemony/?format=json&timebin__lte=2024-04-17T12%3A00&timebin__gte=2024-04-17T00%3A00&af=4&asn=2914,174,3356,1299&originasn=0

So this API call with originasn=0 and asn=2914,174,3356,1299 should always return results. If it doesn't return results that means the whole Internet is broken (we'll disregard this case :D ) or that IHR backend had a problem and we don't have data for the selected time frame.

**Comment by 0xAnon0602** [comment]
So if there is no result from Tier1 networks is it "Network-Unreachable" case? 
And If there is resullt from Tier1 networks and no result from specified AS then it is case of "No-Data"?

**Comment by romain-fontugne** [comment]
no, that's the opposite:
- no results from Tier1: 'No-Data'
- results from Tier1 but no results for the selected network: 'Network-Unreachable'

**Comment by 0xAnon0602** [comment]
I fully understand it now 
Thanks )

**Comment by 0xAnon0602** [comment]
@romain-fontugne 
Is this what we are expecting as a result?
https://ihr.iijlab.net/ihr/en-us/networks/AS2497?af=4&last=3&date=2004-04-21&rov_tb=routes

<img width="2116" alt="image" src="https://github.com/InternetHealthReport/ihr-website/assets/71931823/88bbcd3f-9818-45b7-81c3-17f8147d9d03">

**Comment by 0xAnon0602** [comment]
https://ihr.iijlab.net/ihr/api/hegemony/?format=json&originasn=0&asn=2914,174,3356,1299&af=4&timebin__gte=2022-04-04T23:59:59.000Z&timebin__lte=2022-04-07T23:59:59.000Z&ordering=timebin

The IHR API is taking a long time to respond with these input data. 
How do you suggest I should tackle this issue?

**Comment by romain-fontugne** [comment]
ok, maybe the first or second time is a bit long but then it should be cached, so hopefully if many users do that same query it will be faster. Also we can maybe make the results smaller by querying only for two tier1 (for example 174 and 1299)
