### ISSUE TITLE
Main graph for global report

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#14]
All alarms can be summarized in a single graph, maybe a sunburst or treemap (https://plot.ly/javascript/sunburst-charts/ https://plot.ly/javascript/treemaps/)

The granularity could go from AS/location -> alarm types -> alarms
On selection the below tables could show only the alarms for the selected AS/location

**Comment by Aniket762** [comment]
> All alarms can be summarized in a single graph, maybe a sunburst or treemap (https://plot.ly/javascript/sunburst-charts/ https://plot.ly/javascript/treemaps/)
> 
> The granularity could go from AS/location -> alarm types -> alarms On selection the below tables could show only the alarms for the selected AS/location

@romain-fontugne sir, I believe I can take upon this issue. Can you please help me where to get the data from? And what should be my labeling for the graph data?

What is Alarms I am not able to get a clear picture, any reference to read from?

**Comment by romain-fontugne** [comment]
Actually this one requires that I restart the alarm system on our backend. It is currently not working, I have some stuff to fix there.

But you can see past alarms, for example here: https://ihr.iijlab.net/ihr/en-us/global_report?filter_level=1&last=3&date=2020-03-01
We want to make a visual representation of the data shown in all these tables. This requires some experimentation, we are not sure what would be the best way to represent all alarms in a single visualization. I think it would be nice to have this also for each country or network.

The data is fetch from IHR API (https://ihr.iijlab.net/ihr/en-us/api) any endpoint that ends with '/alarms'

**Comment by MBWankhade** [comment]
hey @Aniket762 I am not able to understand the issue.
can you tell how to work on this?

**Comment by romain-fontugne** [comment]
Let me change a bit the initial issue.

This page https://ihr.iijlab.net/ihr/en-us/global_report shows tables with different types of alarms. We'd like to have one a summary of all alarms into one plot. I think the easiest would be to show a world map with all alarms (similar to what we have at the bottom of the page but currently the map show only one type of alarms).

**Comment by harish343** [comment]
hey can i work on this issue

**Comment by romain-fontugne** [comment]
in the bottom map we currently only have 'network disconnections' alarms. But we'd like to have one maps with all types of alarms: AS dependency, network delay, link delay (this one is currently not working so there is no alarm currently)

**Comment by harish343** [comment]
share link and tell me how can i help

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir if no one working in this issue. I would like to work on this issue

**Comment by Avi-88** [comment]
@romain-fontugne @ConnectBhawna if possible I would also like to help with this in order to get more familiar with the visualizations used in the project, thanks

**Comment by romain-fontugne** [comment]
before assigning this one, I'd like to know your exact plans. We have a gsoc project planned for this, I want to have a nice / comprehensive viz for this one

**Comment by Althaf66** [comment]
By creating four buttons on above the world map - As dependency, network delay, link delay, network disconnection Each buttons have separate representation with same world map.this is my plan, if any change needed please comment @romain-fontugne.

**Comment by kanishk88** [comment]
hey @romain-fontugne agreeing with althaf i see this issue as an addition to the global report page keeping intact of all other widgets and data. i think i can explain the best using flowcharts
![flowchart1](https://user-images.githubusercontent.com/110462331/225924917-8870618b-45e1-4048-863f-fc3e9400e6ff.PNG)

**Comment by kanishk88** [comment]
> hey @romain-fontugne agreeing with althaf i see this issue as an addition to the global report page keeping intact of all other widgets and data. i think i can explain the best using flowcharts ![flowchart1](https://user-images.githubusercontent.com/110462331/225924917-8870618b-45e1-4048-863f-fc3e9400e6ff.PNG)

i see you have edited the issue and i was figuring on the previous one :p

**Comment by mhmdawnallah** [comment]
I'm very interested to work on this issue. I've made a prototype for this world map visualization for IHR global report in **Vue Js** as seen in the following video:

https://user-images.githubusercontent.com/69568555/226918174-9f1736d4-cfd1-4687-8802-55772890d4a1.mov

Could you please @romain-fontugne assign this issue to me so that I could integrate this world map prototype to the IHR website codebase?

**Comment by romain-fontugne** [comment]
That's very close to what I had in mind. Go ahead @mhmdawnallah !
