### ISSUE TITLE
Missing error handling for dynamic page links

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/ihr-website#146]
**Describe the bug**
Links to pages that use [Vue Router's Params](https://router.vuejs.org/guide/essentials/dynamic-matching.html) (currently the country and network reports) do not show a proper error page or message when called with invalid params.

**To Reproduce**
For country reports:

1. Go to https://ihr.iijlab.net/ihr/en-us/countries/HELLOTHERE
2. See an empty report page.

For network reports:
1. Go to https://ihr.iijlab.net/ihr/en-us/networks/HELLOTHERE
2. Get redirected to the network report start page.

**Expected behavior**
The behavior of the network reports is better than for country reports, since at least no empty report is shown. So either we do the same thing for the country reports, _or_ display an error, _or_ redirect to a 404 page.

**Screenshots**
Empty report without heading
![image](https://user-images.githubusercontent.com/49444122/175208574-0091c256-5689-4a10-b1c2-8e38cf21ae91.png)

**Comment by Aniket762** [comment]
> **Describe the bug** Links to pages that use [Vue Router's Params](https://router.vuejs.org/guide/essentials/dynamic-matching.html) (currently the country and network reports) do not show a proper error page or message when called with invalid params.
> 
> **To Reproduce** For country reports:
> 
> 1. Go to https://ihr.iijlab.net/ihr/en-us/countries/HELLOTHERE
> 2. See an empty report page.
> 
> For network reports:
> 
> 1. Go to https://ihr.iijlab.net/ihr/en-us/networks/HELLOTHERE
> 2. Get redirected to the network report start page.
> 
> **Expected behavior** The behavior of the network reports is better than for country reports, since at least no empty report is shown. So either we do the same thing for the country reports, _or_ display an error, _or_ redirect to a 404 page.
> 
> **Screenshots** Empty report without heading ![image](https://user-images.githubusercontent.com/49444122/175208574-0091c256-5689-4a10-b1c2-8e38cf21ae91.png)

Thanks a lot @m-appel for pointing out. I guess this needs to be fixed soon.

I was just curious to know how you want to get this fixed. We can proceed like:
First, get the query check in the countries, cities and networks list from the ihr_api call. If not found, in the list them we can display no such network available. 

But, the constraint with this method would be it would take a longer for every call, since the search traversal for the query would go on. Which would make the entire process slower. 

Do you have a better way to implement the 404 page?

**Comment by romain-fontugne** [comment]
I'll take care of this. I think a redirection to the country landing page is good: https://ihr.iijlab.net/ihr/en-us/countries

**Comment by romain-fontugne** [comment]
fixed in 740ef0fa4d60cc39deb58c2dec5f76a1d7ffa402
