### ISSUE TITLE
Add Download Report Button

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#177]
**Is your feature request related to a problem? Please describe.**
If our end-users want to see a file for future reference, it would be difficult for them to refer to. 

**Describe the solution you'd like**
Adding a download button on every page which generates customizable reports will make the task easier for the end users to keep a track of the reports they are working for. 

**Describe alternatives you've considered**
Currently, our users are using screenshots that have low picture quality, generating pdfs would increase the pixels and the quality of the graphs.

**Comment by thisiskaransgit** [comment]
I would like to work on this issue!

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 kindly, review the PR 😀

**Comment by romain-fontugne** [comment]
added in #186
