### ISSUE TITLE
Probe report

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#18]
Add probe report, including:
- [ ] Network delays
- [ ] Tag (noisy or not)

**Comment by Aniket762** [comment]
> Add probe report, including:
> 
> * [ ]  Network delays
> * [ ]  Tag (noisy or not)

@romain-fontugne sir, can you please elaborate on this issue a bit?

**Comment by Yh010** [comment]
@romain-fontugne we can use tools like ping or traceroute to measure network delays...but assigning tags (noisy or not), what should be the criteria? one of the criteria can be a network delay of more than 100ms may be tagged as "noisy," while delays less than 100ms are tagged as "not noisy", what more criteria should we add?

**Comment by romain-fontugne** [comment]
This is a very old issue, it would need some rethinking. Maybe I should close this for now. #252 is similar but much more important. I'll add more details there.
