### ISSUE TITLE
Add annotations on hegemony graphs

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#19]
add colored overlays to show missing data and low visibility.
Also make the graph to 0 if a dependency disappear.

**Comment by Aniket762** [comment]
Hi @romain-fontugne sir, I am interested in taking up the issue. But, I am having a bit of a problem understanding the requirements. 

As of now, I have understood you want me to add some sort of component to visualize data in a more structured way. Can you please provide an example or elaborate on the type of overlays you want me to add? 

And by dependency disappearance do you mean npm modules as dependencies or failure of API endpoints or is it something completely different.

**Comment by romain-fontugne** [comment]
:)

Sorry that was more of a reminder for myself.

So there is two things here:
1) Missing data: Sometimes our backend has problems and we may not produce data. For example we don't have data for March 1st in the top graph here:  https://ihr.iijlab.net/ihr/en-us/networks/AS2497?af=4&last=3&date=2022-03-02&rov_tb=routes
Currently plotly draws a long line to fill this gap but we'd like to show that there is missing data, for example with a shaded area where data is missing and maybe a message saying 'No data available'.

2) Make the graph goes to 0: For some interesting events some lines in our 'AS dependency' graphs just stop. See this example where the line for AS174 stops on March 4th 5pm: https://ihr.iijlab.net/ihr/en-us/networks/AS20485?rov_tb=routes&af=4&last=3&date=2022-03-05
In reality it means that AS174 is equal to zero from 5:15pm onward. So this is what we want to fix. Continue the AS174 line with only zero values. Note that it can happen the other way around, where a line starts in the middle of the graph. In this case we'd like to add zero values before it starts.

Let me know if it is more clear now and if you want to take care of this issue. Thanks!

**Comment by Aniket762** [comment]
> :)
> 
> Sorry that was more of a reminder for myself.
> 
> So there is two things here:
> 
> 1. Missing data: Sometimes our backend has problems and we may not produce data. For example we don't have data for March 1st in the top graph here:  https://ihr.iijlab.net/ihr/en-us/networks/AS2497?af=4&last=3&date=2022-03-02&rov_tb=routes
>    Currently plotly draws a long line to fill this gap but we'd like to show that there is missing data, for example with a shaded area where data is missing and maybe a message saying 'No data available'.
> 2. Make the graph goes to 0: For some interesting events some lines in our 'AS dependency' graphs just stop. See this example where the line for AS174 stops on March 4th 5pm: https://ihr.iijlab.net/ihr/en-us/networks/AS20485?rov_tb=routes&af=4&last=3&date=2022-03-05
>    In reality it means that AS174 is equal to zero from 5:15pm onward. So this is what we want to fix. Continue the AS174 line with only zero values. Note that it can happen the other way around, where a line starts in the middle of the graph. In this case we'd like to add zero values before it starts.
> 
> Let me know if it is more clear now and if you want to take care of this issue. Thanks!

Yes, I would take upon this issue and will try to work on it accordingly. In case there is any doubt would revert back to you asap. Please assign this issue to me

**Comment by Aniket762** [comment]
Hey @romain-fontugne,

I was trying to work on this issue. but testing on localhost didn't fetch API calls due to Cross Origin policy. It would be difficult for me to test things and add functionality without seeing any changes on localhost.
 
I was trying to test this url https://localhost:8081/ihr/en-us/networks/AS2497?af=4&last=3&date=2022-03-02&rov_tb=routes replacing ihr.iijlab.net with localhost:8081.  The first link one you mentioned above.

How should I proceed with the task.

<img width="1440" alt="Screenshot 2022-03-16 at 2 42 25 PM" src="https://user-images.githubusercontent.com/67703407/158556209-57f8077d-227b-48ec-9101-5908cd30fe78.png">

**Comment by romain-fontugne** [comment]
I recently had the same problem, I'm really not sure why this is happening. I don't think I had this problem before. And it is very confusing, for some links it is working for me... I'll take a look at it

**Comment by Aniket762** [comment]
> I think the problem happen with our CDN, somehow some cached queries enforce CORS. If you are on Mac/Linux you can bypass the CDN by adding the following in /etc/hosts: 202.214.97.18 ihr.iijlab.net
> 
> And then it should work.
> 
> Issue #17 is actually already implemented, sorry forgot to close it. Tomorrow I can add issues related to GSoC ideas. I will also review your PRs tomorrow.

Thanks a lot sir

**Comment by romain-fontugne** [comment]
@Aniket762 I just found out this weird case where there is data but we are putting the 'no data' label on top of it:
https://ihr.iijlab.net/ihr/en-us/networks/AS270903?af=4&last=3&date=2022-04-06&rov_tb=routes

I think the problem is that one of he timeseries stopped. To check the data availability we can use the timeseries where "originasn"=="asn" (we are not plotting this one)

**Comment by Aniket762** [comment]
> @Aniket762 I just found out this weird case where there is data but we are putting the 'no data' label on top of it: https://ihr.iijlab.net/ihr/en-us/networks/AS270903?af=4&last=3&date=2022-04-06&rov_tb=routes
> 
> I think the problem is that one of he timeseries stopped. To check the data availability we can use the timeseries where "originasn"=="asn" (we are not plotting this one)

I would check on that and try to resolve it as soon as possible from my end! Sorry, I missed the corner case

**Comment by Aniket762** [comment]
> @Aniket762 I just found out this weird case where there is data but we are putting the 'no data' label on top of it: https://ihr.iijlab.net/ihr/en-us/networks/AS270903?af=4&last=3&date=2022-04-06&rov_tb=routes
> 
> I think the problem is that one of he timeseries stopped. To check the data availability we can use the timeseries where "originasn"=="asn" (we are not plotting this one)

So, actually, some AS are having values whereas some are not. For a small interval, I don't think making the missing data points to zero would be good so I am planning to remove the grey box with the label no data available. In the 2 cases you have mentioned above, I made the data points zero for graphs that don't have data after a certain period. But, this case was missed out, if you want me to make the missing data points zero let me know I would do that, but as of now, I am removing the data label and grey box and keeping the missing data points empty for those particular AS. Please let me know if this works

**Comment by romain-fontugne** [comment]
> So, actually, some AS are having values whereas some are not.

I see. It means that in this case we have data but that AS has values equal to 0 (which are not reported by IHR API). So I think we should remove the gey box and also add zero values for ASes that have no value

**Comment by Aniket762** [comment]
Yes, that's what I did :)
