### ISSUE TITLE
Font size and box height can be modified for each screen width

### ISSUE THREAD

**Issue by cool-man-vk** [InternetHealthReport/ihr-website#207]
For each screen width, the heights and font-sizes can be mentioned in a css file to be more responsive, if possible I can do this!

**Comment by Aniket762** [comment]
> For each screen width, the heights and font-sizes can be mentioned in a css file to be more responsive, if possible I can do this!

Hey @cool-man-vk please go for it. Will be of great help, thanks

**Comment by Aniket762** [comment]
Hey @cool-man-vk are you still working on it?

**Comment by cool-man-vk** [comment]
Hey Aniket ,
I'm working on it . I have semester exams right now , so from 28th of this
month , I'll continue working on this . So please let give some time and
I'll work on it for sure.

Thanks & Regards,
R.Vignesh kumar

**Comment by nimishmedatwal** [comment]
I can work on this issue as well

**Comment by cool-man-vk** [comment]
Yes , please go ahead

**Comment by Aniket762** [comment]
> I can work on this issue as well

Go for it! Assigned

**Comment by hussain-shariff** [comment]
> I can work on this issue as well
> 

Hey are you working on it? 
If you need help I'll be glad to help.

**Comment by hussain-shariff** [comment]
> I can work on this issue as well
> 

@nimishmedatwal are you working on this?
I'll be glad to fix it

**Comment by ConnectBhawna** [comment]
@nimishmedatwal Are you still working on this , If not let me know i will work on this issue :)
Thanks

**Comment by J0SAL** [comment]
Hey @nimishmedatwal are you still working on it?
If no one's working on it, @Aniket762 @romain-fontugne, I would love to work on the issue.

**Comment by Skshmshah2611** [comment]
hello @Aniket762 if no one is working on it I would Like to work on it and increase its responsiveness and make it more interactive and user friendly .
thanks

**Comment by romain-fontugne** [comment]
we haven't heard from @nimishmedatwal for more than a month, who wants to work on this?

**Comment by ConnectBhawna** [comment]
I want to work on this @romain-fontugne sir :)

**Comment by Skshmshah2611** [comment]
I want to work on this sir @romain-fontugne

**Comment by romain-fontugne** [comment]
go ahead @ConnectBhawna
