### ISSUE TITLE
Add IHR logo on all graphs

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#21]
Add logo and mention IHR on all graphs so that people knows where screenshots come from.

**Comment by Aniket762** [comment]
Hey, did you use any module to generate the graphs?

**Comment by romain-fontugne** [comment]
We are using plotly. Most (all?) graphs are based on this component: https://github.com/InternetHealthReport/ihr-website/blob/master/src/components/ReactiveChart.vue

**Comment by Aniket762** [comment]
> We are using plotly. Most (all?) graphs are based on this component: https://github.com/InternetHealthReport/ihr-website/blob/master/src/components/ReactiveChart.vue

Thanks, sir for the reply, I will check if there is any way to pass the logo as a parameter! If so will raise the PR asap. Thanks for the help

**Comment by romain-fontugne** [comment]
Great, thank you!

**Comment by romain-fontugne** [comment]
Cool, thanks. I think we have to experiment a bit here, intuitively I was thinking of putting at the right upper corner. There is a bit of white space there and if possible I don't want the logo to interfere with the plotted data.

I'd prefer the IHR logo for the image: https://github.com/InternetHealthReport/ihr-website/blob/master/src/assets/imgs/ihr_logo.svg
