### ISSUE TITLE
NavBar not responsive

### ISSUE THREAD

**Issue by VenomFate-619** [InternetHealthReport/ihr-website#222]
**Describe the bug**
NavBar is not responsive to mobile screen

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the website
2. Switch to mobile layout from the dev tool

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/207927591-3c090104-5d09-4699-8457-05fb110e3ce6.png)

I would like to make it responsive

**Comment by Aniket762** [comment]
Hey @VenomFate-619 you can go for it.

**Comment by Adityasaini10012001** [comment]
hey @VenomFate-619  are you working on this

**Comment by VenomFate-619** [comment]
> hey @VenomFate-619 are you working on this

yes I am working on it

**Comment by niranjan-kurhade** [comment]
Hey, @VenomFate-619 are you still working on this issue?

**Comment by VenomFate-619** [comment]
this issue is resolved  by  pr #225
