### ISSUE TITLE
align ihr tweets and special thanks

### ISSUE THREAD

**Issue by VenomFate-619** [InternetHealthReport/ihr-website#226]
**Describe the bug**
The ihr tweet and special thanks section is not aligned in the centre and need to increase margin-top of the special thanks section
**Check this on dev environment as the latest changes are not deployed**

**To Reproduce**
Steps to reproduce the behaviour:
**Check this on the dev environment as the latest changes are not yet deployed**
open the homepage 
scroll down

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/210179889-3d6a3f0a-a4fb-4525-8a26-060e62f14337.png)

![image](https://user-images.githubusercontent.com/67755128/210179901-7b27f253-dee8-4418-aa74-07c73fcdaf75.png)

**Desktop (please complete the following information):**

- OS: PopOS 
- Browser brave
- Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)

**Comment by VenomFate-619** [comment]
I would like to fix this

**Comment by VenomFate-619** [comment]
@Aniket762

**Comment by romain-fontugne** [comment]
sure go for it @VenomFate-619

**Comment by VenomFate-619** [comment]
This issue is resolved
