### ISSUE TITLE
IX-Federation IDs instead of CAIDA IX IDs

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#23]
CAIDA IX file has redundant entries, two IDs could map to the same IX and LAN just named differently in peeringdb and pch data (e.g. INEX). Plus the IX community is mainly using peeringdb or IX federation IDs.

But currently I don't see an easy way to map an IP address to an IX federation ID. IXP DB is the best effort so far (https://ixpdb.euro-ix.net/en/ixpdb/ixps/) But seems to miss a lot of IP prefixes?

**Comment by ConnectBhawna** [comment]
Hey @romain-fontugne Can I work on this issue?

**Comment by romain-fontugne** [comment]
This is actually a fairly complicated issue. I have added a few new issue today, you may want to look at it @ConnectBhawna

**Comment by ConnectBhawna** [comment]
Okkk sure @romain-fontugne sir, thank you for helping me out :)

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir, Can i work on this issue, Now i am little bit familiar with the codebase so willing to work on this issue.
Can you please provide some info about this issue. So that i can easily approach this issue.
Thank you

**Comment by romain-fontugne** [comment]
I'm closing this one, because actually it is a problem we have on the backend
