### ISSUE TITLE
Hero banner not covering the container

### ISSUE THREAD

**Issue by VenomFate-619** [InternetHealthReport/ihr-website#232]
**Describe the bug**
Hero banner not covering the container in tablet and mobile layout

**To Reproduce**

1. Go to homepage
2. See the homepage in tablet or mobile phone layout

**Expected behaviour**
![image](https://user-images.githubusercontent.com/67755128/210710877-f2402312-7ead-427a-8fbe-c8f8b10c3507.png)

![image](https://user-images.githubusercontent.com/67755128/210710912-de2674d1-efdf-477d-bde0-3d54f4592d8c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/210710718-318619fa-712e-41ee-a350-0549e6e52ac9.png)

![image](https://user-images.githubusercontent.com/67755128/210710773-59088a33-de36-4742-b6e9-1b576aa5ff48.png)

**Desktop (please complete the following information):**

- OS: PopOs
- Browser brave
- Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)

**Comment by VenomFate-619** [comment]
I would like to resolve this.

**Comment by Aniket762** [comment]
Go for it @VenomFate-619 :)
