### ISSUE TITLE
No Hegemony values for dates older than 2015

### ISSUE THREAD

**Issue by sim-azan** [InternetHealthReport/ihr-website#24]
Hi. I was wondering is this a limitation of the API that there are no AS hegemony values fetched for dates older than 2015.

**Comment by sim-azan** [comment]
> We have data for the 15th of every month from 2007 to 2015.
> For example: https://ihr.iijlab.net/ihr/api/hegemony/?originasn=2497&af=4&timebin=2007-01-15T00:00
> 
> It is a bit hard to maintain more results for past data, our database if pretty big already. Let me know if this is enough for your study? otherwise I will explain in the other issue how you can get results for more dates. By the way I think it might be hard to go up to 2000, RIS/routeviews before 2007 are very sparse and iirc there is some timing inconsistencies.

Thanks Romain. I wasn't aware of this. At the moment I use hegemonic values for the first week of every month post 2015 and average the values per ASN for consistency. Could you explain how the hegemony for the 15th of every month is calculated? Is it using timebin only for a single day? or is the average of values for the first 15 days ? Thanks

**Comment by romain-fontugne** [comment]
Oh yes, there is results for every 15min timebins from 00:00 until 23:45 of the 15th of every months. You could average these values but it might not be as robust as what you have using an entire week. Maybe using median values could be good enough to filter out rapid changes.

**Comment by sim-azan** [comment]
> Oh yes, there is results for every 15min timebins from 00:00 until 23:45 of the 15th of every months. You could average these values but it might not be as robust as what you have using an entire week. Maybe using median values could be good enough to filter out rapid changes.

Thanks, but I think if I could find a way to get hegemony calues per originASN for the entire week every month for 2010 and after it would align well with my study. I was wondering how I could go about this. The new repo 'as-hegemony' or the older 'as-hash' ? For AS-hegemony repo I managed to run the kakfa and the produce_bgpdata.py to get data into my kafka cluster but I am clueless on how to proceed after that. I am thinking I need to run the code in a particular order for the producer and consumer to work. Thanks for your help.

**Comment by romain-fontugne** [comment]
Let me close this issue and reply on the as-hegemony repo. In case someone else has the same problem.
