### ISSUE TITLE
Footer-alignment

### ISSUE THREAD

**Issue by Yasir761** [InternetHealthReport/ihr-website#240]
Footer content should be in the middle of the footer,
@romain-fontugne I would to like work on this, can you please assign me this?
Thank you

**Comment by romain-fontugne** [comment]
Sure, thanks for pointing this out!

**Comment by Rithvik-padma** [comment]
@romain-fontugne The footer content is already aligned properly in the new website version but is not yet deployed ig.
![image](https://user-images.githubusercontent.com/99183441/214048079-1323a095-3f48-496c-93b3-bed18cdcb907.png)

**Comment by Yasir761** [comment]
@Rithvik-padma sir, you are right about the alignment of the footer, but I made some changes in the footer when responsiveness is active.
