### ISSUE TITLE
Add Prefix-level Hegemony to the searchbox and UI

### ISSUE THREAD

**Issue by mesflores** [InternetHealthReport/ihr-website#252]
Currently, the UI allows you to search by ASN, Country, or IXP, and displays a number of "local" context charts (AS Dependency, origin validation, etc). It would be helpful to add Prefixes to the set of possible inputs -- and display the corresponding information for the prefix level dependency that's already available via API.

This would be especially helpful to multi-homed networks with multiple sites that feature different upstream providers.

Thanks!

**Comment by romain-fontugne** [comment]
For this issue we need a new page (Prefix report) with:
- Title: The IP prefix (e.g. 192.168.0.0/16) 
- Some information about the prefix: country code, RPKI, IRR, delegated status (as shown in 'Route Origin Validation')
- AS Dependency graph: we can probably reuse/adapt the current component we have for showing the AS Dependency graph on the 'Network report', but this time the parameter is a prefix not an ASN and we don't want to show the second graph (Number of ASes dependent on ASXXX)

All the data is available from the API, /hegemony/prefixes/

Then we should add a way to search IP prefixes in the headers search bar

**Comment by romain-fontugne** [comment]
Anyone up for this one?

**Comment by roopeshsn** [comment]
I would like to work on this @romain-fontugne sir.

**Comment by Yh010** [comment]
As mentioned in #18, I would like to work on this issue

**Comment by romain-fontugne** [comment]
@roopeshsn , @Yh010  we could actually split this in to two parts. One is to add IP prefixes to the search bar, the other one is to make the page for prefixes. Pick the one you prefer

**Comment by Yh010** [comment]
I would like to work on adding the prefixes

**Comment by romain-fontugne** [comment]
ok, thanks to both of you!

**Comment by romain-fontugne** [comment]
let me know if you have questions on how to modify the code.

**Comment by Yh010** [comment]
@romain-fontugne if you could provide us with some resources to get started , it would help us to get the issue solved faster and better!

**Comment by romain-fontugne** [comment]
For the header search bar, the code is in ```src/components/search_bar/NetworkSearchBar.vue```

And you'll have to call the hegemony_prefix API, see (src/plugins/query/IhrQuery.js). 

In the near future, we'll have to change a bit the API. For now the API cannot do partial search for a prefix. That means we can search for a specific prefix, for example for "8.8.8.0/24" we have this results:
https://ihr.iijlab.net/ihr/api/hegemony/prefixes/?timebin__lte=2023-03-02T00%3A00&timebin__gte=2023-02-28T00%3A00&prefix=8.8.8.0%2F24

But we cannot search for a substring (e.g."8.8.8.0")

**Comment by romain-fontugne** [comment]
For the prefix page, I would start by looking at he network report page: src/views/Networks.vue 
And keep only the first part up to the as-interdependencies-chart.

Then we have to modify or duplicate that chart to make it work for prefixes (src/views/charts/AsInterdependenciesChart.vue)

maybe we should create a different issue for this, so we don't mix up the discussions here

**Comment by roopeshsn** [comment]
> For the prefix page, I would start by looking at he network report page: src/views/Networks.vue And keep only the first part up to the as-interdependencies-chart.
> 
> Then we have to modify or duplicate that chart to make it work for prefixes (src/views/charts/AsInterdependenciesChart.vue)
> 
> maybe we should create a different issue for this, so we don't mix up the discussions here

Yep, that makes sense @romain-fontugne sir!

**Comment by Yh010** [comment]
@roopeshsn I have made changes in the NetworkSearchBar.vue to take prefix as input in the search and then call the  hegemony_prefix API . I'll push the changes in the branch named "#252" .Pls review the changes so that we can proceed further

**Comment by romain-fontugne** [comment]
@Yh010 are you still working on this? This issue is quite important in my regards, I hope we could fix it soon. 
So if you dont have time or at not really confident to implement this, let us know

**Comment by Yh010** [comment]
@romain-fontugne @roopeshsn pls have a look : [PR](https://github.com/InternetHealthReport/ihr-website/pull/433)

**Comment by mflores-edgio** [comment]
Any movement on this?

**Comment by roopeshsn** [comment]
> Any movement on this?

Awaiting for a little change (#429).

**Comment by romain-fontugne** [comment]
> @romain-fontugne @roopeshsn pls have a look : [PR](https://github.com/InternetHealthReport/ihr-website/pull/433)

Please have a look at Roopesh's comment in that PR

**Comment by romain-fontugne** [comment]
> > Any movement on this?
> 
> Awaiting for a little change (#429).

@roopeshsn I still cannot make that code working. When I try http://localhost:8080/ihr/en-us/prefixes/8.8.8.0/24 it gives me error 404. I thought we agreed to use
```
path: `${routerBase}prefixes/:prefix/:prefix_length?
```
in the router file?

**Comment by roopeshsn** [comment]
> > > Any movement on this?
> > 
> > 
> > Awaiting for a little change (#429).
> 
> @roopeshsn I still cannot make that code working. When I try http://localhost:8080/ihr/en-us/prefixes/8.8.8.0/24 it gives me error 404. I thought we agreed to use
> 
> ```
> path: `${routerBase}prefixes/:prefix/:prefix_length?
> ```
> 
> in the router file?

Yep, that change is pending.

**Comment by dpgiakatos** [comment]
Closed by #719
