### ISSUE TITLE
Add hovering property to the 3 buttons present in the footer

### ISSUE THREAD

**Issue by Arunjagan12** [InternetHealthReport/ihr-website#255]
**Is your feature request related to a problem? Please describe.**
The 3 buttons present in the footer doesn't has hovering property.

https://user-images.githubusercontent.com/96646536/218083627-e0981544-e8c1-4854-b975-3ca06e098741.mp4

**Describe the solution you'd like**
So,I have added the hovering property to those buttons.

**Describe alternatives you've considered**
I added a hovering property to those buttons.

**Additional context**

https://user-images.githubusercontent.com/96646536/218085963-e3d4b743-5588-49ae-85e2-c142ef1ff350.mp4

**Comment by Arunjagan12** [comment]
https://github.com/InternetHealthReport/ihr-website/pull/256

**Comment by sarkartanmay393** [comment]
@Arunjagan12 Hey, I'm exploring GitHub and found this amazing project. I would love to contribute to this issue.

**Comment by sarkartanmay393** [comment]
Oh, this issue is solved.
