### ISSUE TITLE
Fix unequal width of embedded tweets to achieve consistency

### ISSUE THREAD

**Issue by Avi-88** [InternetHealthReport/ihr-website#257]
The analysis modules and the embedded tweets section span up to different widths for smaller screens causing inconsistency in layout. The embedded tweets section also gets misaligned for smaller screens 

## Before :

![misalign](https://user-images.githubusercontent.com/79744258/218387459-d29b8b97-c5ce-4c4b-a457-582b5cd508af.png)

![notcenter](https://user-images.githubusercontent.com/79744258/218387496-51ec49e0-618b-48db-becd-742fff492de5.png)

## After :
It can be fixed by changing a bit of css and adding a media query which sets the max width equal to the analysis modules 

![aligned](https://user-images.githubusercontent.com/79744258/218388603-0fc7ee2e-17a1-4473-9d1d-df38a267192f.png)

![sentered](https://user-images.githubusercontent.com/79744258/218388639-cd9c4a80-a329-4c3b-99de-844d9cfb0017.png)

**Comment by romain-fontugne** [comment]
thanks, indeed it looks much better
