### ISSUE TITLE
Error when setting up the project in Ubuntu with Node v16

### ISSUE THREAD

**Issue by roopeshsn** [InternetHealthReport/ihr-website#259]
**Describe the bug**
I am using Ubuntu OS and tried to setup the project. Followed the steps as described in the docs. When I ran `npm run serve` command the following error pops up. 

```
error  in ./node_modules/swagger-ui/dist/swagger-ui.css

Syntax Error: Error: Cannot find module './terminal-highlight'
```

Detailed error message is attached in the **Screenshots** section.

**To Reproduce**

1. Fork and Clone the project using git clone
2. npm install
3. npm run serve

node -v 
v16.19.0

npm -v
8.19.3

**Expected behavior**
Compiling without any errors

**Screenshots**
```
 ERROR  Failed to compile with 1 error                                                                                 13:02:04

 error  in ./node_modules/swagger-ui/dist/swagger-ui.css

Syntax Error: Error: Cannot find module './terminal-highlight'
Require stack:
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/node_modules/postcss/lib/css-syntax-error.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/node_modules/postcss/lib/node.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/node_modules/postcss/lib/declaration.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/node_modules/postcss/lib/postcss.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/lib/createICSSRules.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/icss-utils/lib/index.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/css-loader/lib/processCss.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/css-loader/lib/loader.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/css-loader/index.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/loader-runner/lib/loadLoader.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/loader-runner/lib/LoaderRunner.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/webpack/lib/NormalModule.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/webpack/lib/NormalModuleFactory.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/webpack/lib/Compiler.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/webpack/lib/webpack.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/@vue/cli-service/lib/commands/serve.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/@vue/cli-service/lib/Service.js
- /home/pando-roopesh/ihr-org/ihr-website/node_modules/@vue/cli-service/bin/vue-cli-service.js


 @ ./node_modules/swagger-ui/dist/swagger-ui.css 4:14-139 15:3-20:5 16:22-147
 @ ./src/configs/quasar.config.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.11.51:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Chrome
- Version: 20.04

**Smartphone (please complete the following information):**
_No Response_

**Additional context**
_No Response_

**Comment by roopeshsn** [comment]
Update: The app is compiled, and served when using version 14 of Node (v14.21.2).

**Comment by Avi-88** [comment]
Hi @roopeshsn , I'm using node v16 as well and it didn't cause any issue. I was initially using v18 which caused issue with ssl packages as a bug was fixed in v17 release of node, but other that that no other  issues were found. Could you please confirm if this is not a issue specific to your system, thanks

**Comment by roopeshsn** [comment]
> Hi @roopeshsn , I'm using node v16 as well and it didn't cause any issue. I was initially using v18 which caused issue with ssl packages as a bug was fixed in v17 release of node, but other that that no other issues were found. Could you please confirm if this is not a issue specific to your system, thanks

If that's the case then how the app is compiled and served when using v14?

**Comment by Avi-88** [comment]
> > Hi @roopeshsn , I'm using node v16 as well and it didn't cause any issue. I was initially using v18 which caused issue with ssl packages as a bug was fixed in v17 release of node, but other that that no other issues were found. Could you please confirm if this is not a issue specific to your system, thanks
> 
> If that's the case then how the app is compiled and served when using v14?

I'm not sure either , but the issue another one of the contributors faced was also due to the node version being v17^ and was related to ssl packages. The error you got is a dependency error which is different from the one we both faced. If possible could you try with v16 again because I tried and cloned again and it worked without any hitch. Just want to make sure if this is a general error so that we can try and prevent it for others, thanks

**Comment by Aniket762** [comment]
Closing the issue, since you have configured your system
