### ISSUE TITLE
Proposal to add generic workflow

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#26]
With the popularity of IHR and its infamous reports, I personally believe an upsurge in the number of contributors and increasing functionality in the web application. I propose to add a contributor's workflow and dependant bot.

### Contributor's workflow
- Issue template: To generalize issue and parameters a contributor needs to add while creating an issue
- Bug Report: To generalize bug reporting and parameters a contributor needs to add while reporting a bug
- Pull Request template:  To generalize PRs and parameters a contributor needs to add while sending a PR

### Dependant bot
With the application using multiple packages, there is a need to keep track of all new versions of the package released. Implementing would help us reduce variabilities along with increasing uptime of the application in a process reducing the points of failure.

@romain-fontugne sir let me know, what you think about my basic proposal to add a generic workflow. If you want me to add the features I requested, will send a PR the same day then work on other issues I requested to work on to keep generalized PRs.  If you don't want the feature feel free to close the issue else do assign me, sir.

**Comment by romain-fontugne** [comment]
Excellent, yes we definitely need all of that!
