### ISSUE TITLE
Documentation page is not responsive

### ISSUE THREAD

**Issue by roopeshsn** [InternetHealthReport/ihr-website#260]
**Describe the bug**
Documentation page is not responsive in smaller screen sizes.

**To Reproduce**
Head over to https://ihr.iijlab.net/ihr/en-us/documentation

**Expected behavior**
Responsiveness and Readability

**Screenshots**
![ihr iijlab net_ihr_en-us_documentation(iPhone SE)](https://user-images.githubusercontent.com/70762571/219021967-31af6056-5753-403a-b7ce-5a32a41bda0c.png)

**Comment by sayande2002** [comment]
Can I work on it?

**Comment by roopeshsn** [comment]
Hey, @sayande2002 I already worked on it and raised a PR. But you can work on other issues or find a bug and fix it by setting up the project locally.
