### ISSUE TITLE
Add GSoC logo

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#266]
**Is your feature request related to a problem? Please describe.**
IHR is part of Google Summer of Code, we should emphasize this on the website.

**Describe the solution you'd like**
We should display GSoC logo on the home page in the ' Special thanks to ' section. Also we should this text (or something similar) in the documentation (Acknowledgements section):
GSoC
Google Summer of Code supports new contributors into the development of IHR.

**Comment by Arunjagan12** [comment]
Sir,can u assign me to solve this issue??

**Comment by romain-fontugne** [comment]
Yes, go for it!

**Comment by Arunjagan12** [comment]
https://github.com/InternetHealthReport/ihr-website/pull/269

**Comment by Arunjagan12** [comment]
Sir, I have added gsoc logo in special thanks section. Only documentation part is pending

**Comment by Arunjagan12** [comment]
https://github.com/InternetHealthReport/ihr-website/pull/275

**Comment by Arunjagan12** [comment]
Sir,I have added gsoc documentation in the acknowledgement section.
