### ISSUE TITLE
Implement Scroll-to-Top Button on IHR Website

### ISSUE THREAD

**Issue by J0SAL** [InternetHealthReport/ihr-website#279]
**Is your feature request related to a problem? Please describe.**
As an end user, I have noticed that it can be inconvenient to scroll back to the top of the page after scrolling through a lot of content. I suggest that we implement a "scroll-to-top" button that would allow users to quickly return to the top of the page with a single click.

**website link**
- https://ihr.iijlab.net/

**Describe the solution you'd like**
1. Add a "scroll-to-top" button to the website's interface that is visible on all pages.
2. Ensure that the button is easily identifiable and positioned in a consistent location on all pages.

**Additional context**
This feature if implemented should greatly improve the user experience on the IHR website.

**Comment by J0SAL** [comment]
Hey @Aniket762 @romain-fontugne, I would like to work on this issue, could you please assign it to me

**Comment by romain-fontugne** [comment]
sure, go for it!

**Comment by sawaisinghh** [comment]
Hey @J0SAL, Are u still working on it? If not, I would love to work on this issue. @romain-fontugne.

**Comment by J0SAL** [comment]
Hey @sawaisinghh I'm working on it

**Comment by J0SAL** [comment]
Hi @romain-fontugne ! Could you please verify the above PR
