### ISSUE TITLE
Proposal to add contributing guidelines 

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#28]
Contributing guidelines would provide potential project contributors with a short guide to how they can contribute to the particular application. It would help contributors understand how to open a PR or raise issues. Adding Contributing guidelines would help maintainers and contributors work in symphony and with ease. Ultimately, increase the productivity of both the stakeholders. 

I am creating a PR, this being a basic issue won't take much time. @romain-fontugne sir in case you don't want a contributing guideline feel free to close this issue as well as the PR I am sending.  

As of now, I am creating a branch and sending PRs, I would mention that in the contributing guideline as well.

**Comment by romain-fontugne** [comment]
Thanks, I have spotted two typos there otherwise it is ready for merge. Thanks for your help!
