### ISSUE TITLE
Metis page need to be made responsive

### ISSUE THREAD

**Issue by roopeshsn** [InternetHealthReport/ihr-website#280]
**Describe the bug**
The [Metis](https://ihr.iijlab.net/ihr/en-us/metis) page needs to be made responsive in different screen sizes.

**To Reproduce**

Go to https://ihr.iijlab.net/ihr/en-us/metis

**Expected behavior**
The Metis page needs to be responsive in all screen sizes.

**Screenshots**
![ihr iijlab net_ihr_en-us(iPhone SE)](https://user-images.githubusercontent.com/70762571/221421372-2eef4c85-cff9-4d17-8d29-8978805e5f98.png)

**Comment by roopeshsn** [comment]
And, I would like to work on this!

**Comment by romain-fontugne** [comment]
sure, go for it

**Comment by rishabhknowss** [comment]
Hi! I can fix it, can you assign me this issue :>

**Comment by roopeshsn** [comment]
> Hi! I can fix it, can you assign me this issue :>

Hey, It's half done already. Do check out other issues or you can create an issue if you find a bug or maybe a feature request.
