### ISSUE TITLE
Sign up Change name request

### ISSUE THREAD

**Issue by mhmdahmedfathi** [InternetHealthReport/ihr-website#281]
**Describe the bug**

In the user-mngt branch, there is a file called views/user/signup, which contains the function of the login and the UI of the login page, and this will lead people to think it is the signup page.

**To Reproduce**

1. run the server
2. Click on login
3. you will see that the UI and functionality of the login

**Expected behavior**
It is expected that we have to change the name of the signup component to make it login so it won't mislead people and change the name of the component for each page that imports signup.

**Screenshots**

1- for the code functionality :
![Screenshot from 2023-02-27 04-44-40](https://user-images.githubusercontent.com/52926511/221461896-7240f865-34e0-4f38-89a4-2b0829e65157.png)

2- for the UI of the signup component :

![Screenshot from 2023-02-27 04-45-25](https://user-images.githubusercontent.com/52926511/221461956-81bbeb82-fe5f-4218-a181-a81d2718c4c4.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 110.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mhmdahmedfathi** [comment]
And, I would like to work on this!

**Comment by romain-fontugne** [comment]
sure, go for it!

**Comment by Aniket762** [comment]
Merged PR, thus closing the issue
