### ISSUE TITLE
Compilation warnings and typo 

### ISSUE THREAD

**Issue by thisiskaransgit** [InternetHealthReport/ihr-website#283]
- Compilations Warnings due to usage of wrong stylus variable in GlobalReport.vue

![Screenshot from 2023-02-27 20-46-32](https://user-images.githubusercontent.com/92504666/221615335-63985df8-b061-49b7-bade-a30ca5500382.png)

- Typo in quasar variable in footer component

**Comment by Aniket762** [comment]
Already solved thus closing it
