### ISSUE TITLE
Feature Request: Adding Github Actions 

### ISSUE THREAD

**Issue by thisiskaransgit** [InternetHealthReport/ihr-website#286]
**Is your feature request related to a problem? Please describe.**

Right now there are no actions present for caching lint errors and merge conflicts, because of which some of the small issues have been overlooked while merging.

**Describe the solution you'd like**

My proposal is to add workflows for the stated.

**Comment by ConnectBhawna** [comment]
@thisiskaransgit that's the great point we can work on this .

**Comment by Aniket762** [comment]
Hey @thisiskaransgit this was really needed. I personally wanted to work on it. Since, you are working on it, I am glad and certain the issue will be resolved. 

But can you please specify which all action you are planning to integrate.

**Comment by romain-fontugne** [comment]
I have absolutely no experience with all of that :)
I hope @Aniket762 can help you here.

if you think that we should add ```package-lock.json``` to the repo and @Aniket762 agrees then it is fine for me

**Comment by Aniket762** [comment]
Hey @thisiskaransgit we can add `package-lock.json`. Did you test the actions post forking and checking with your own creds?


> Also, there's still an issue with the build and deploy action, It's not previewing the built website, I've tried to resolve that one, but it has to be done by someone with authorization. Either we should migrate to some other provider (like Vercel), or resolve the bug in with Netlify.

You need to change the public path. Make sure to change the public path from `/ihr/` to `/` in `vue.config.js`. It will be fixed.

> The dependant bot, should be configured more precisely so that it does not bump dependency to a major version (which may introduce breaking changes) and also create, test, merge and close the PR by itself.

That will be of real use, you can create a separate PR or send it all in another, by creating another issue.

> Right now, the website isn't SEO friendly, we can introduce SEO optimization with the help of lighthouse ci, which will help in optimizing the website.

Go for it


Let me know, if you need something from our end
