### ISSUE TITLE
IHR Logo not aligned properly

### ISSUE THREAD

**Issue by thisiskaransgit** [InternetHealthReport/ihr-website#287]
**Describe the bug**

IHR-logo background not aligned properly

 

**To Reproduce**
1. Go to: https://ihr.iijlab.net/ihr/en-us/contact

4. See the grayish design just above the footer, that is actually the the IHR logo which is not aligned properly
![Screenshot from 2023-02-28 16-20-21](https://user-images.githubusercontent.com/92504666/221832861-75dcea34-d1ba-4c6c-90a3-81808f1963f3.png)

**Expected behavior**
We can either remove the logo, or align the position properly with respect to the page 

**Desktop (please complete the following information):**

- OS:Ubuntu
- Browser Chromium

**Smartphone (please complete the following information):**
Tested in the development environment with every size

**Comment by anugcodes** [comment]
hey @thisiskaransgit can i work on this issue. 
I think simply removing the IHR logo would be good because other pages lack the logo and if we decide to keep it we may have to add it to other pages too.

**Comment by thisiskaransgit** [comment]
Hey @anugcodes, I am not the one who can assign you.

cc: @Aniket762 , @romain-fontugne

**Comment by anugcodes** [comment]
> 

Ok, well i  have already made the changes to remove the background logo from the Contact page. can i commit it and create a PR?

**Comment by anugcodes** [comment]
> Hey @anugcodes, I am not the one who can assign you.
> 
> cc: @Aniket762 , @romain-fontugne

Ok, but i have made the required changes to remove the background logo from the contact page. can i create a PR?

**Comment by Aniket762** [comment]
Thanks a lot, @thisiskaransgit for opening the issue. Also, thanks for your PR @anugcodes, but please make sure to start working on issues when you get assigned.

**Comment by anugcodes** [comment]
> Thanks a lot, @thisiskaransgit for opening the issue. Also, thanks for your PR @anugcodes, but please make sure to start working on issues when you get assigned.

yes @Aniket762  sir, i will keep it in mind.
