### ISSUE TITLE
Dockerize IHR Website

### ISSUE THREAD

**Issue by aabhas-sao** [InternetHealthReport/ihr-website#289]
**Is your feature request related to a problem? Please describe.**

So I was having a look at the project ideas and found `Dockerize all IHR components`.

> Brief explanation: The IHR backend is based on a lot of different analysis modules, anomaly detectors, and scripts that produce data for our main database. The goal of this project is to create docker images for all these components so that each component can be easily move on our servers.

I think this will ease the process of deployment and make setup easier with single command.

I will love to work on this issue. I am actually interested in Docker and have done a similar task during my internship.

**Describe the solution you'd like**
I will create a `Dockerfile` which will describe how container will be created. This will be instructions for creating a single container. Also I'll bind container's port `8080` to host's `8080`.

**Describe alternatives you've considered**
None as of now.

**Additional context**
This will be a step in dockerizing all components at IHR.

**Comment by Aniket762** [comment]
Can you please explain what exactly you want to do? Like you want to build multiple containers or single containers? What about the entry point?

Also, we are actually looking forward to containerizing the backend applications so it will be easier to manage and deploy. Can you explain a bit more on the feature, how it will help, how you plan to proceed. And actually follow the template guide?

Ping me, when you have it ready. If we feel there is a need for it, I will assign it to you and you can start working.

Cheers!

**Comment by aabhas-sao** [comment]
Hey @Aniket762. Would keep in mind following the template next time. I have updated the issue with appropriate details. Will start looking how to do this.

**Comment by anmode** [comment]
This perfectly suits me! I have created docker images and using docker for the past 1 year! Thanks. I see this is a GSoC project too! Hoping to contribute if get chance

**Comment by anmode** [comment]
Hii I have done with the Proposal! Where should I send it for review? Even created the dockerize components too!!

**Comment by Srijan-SS02** [comment]
fixed this issue in #432

**Comment by dpgiakatos** [comment]
The application has been upgraded to Vue 3.js with a new file structure. Kindly acquaint yourself with the updated code structure before revisiting this pull request.
