### ISSUE TITLE
cannot access the  ihr-website through mobile phones

### ISSUE THREAD

**Issue by Ayeshashaik759** [InternetHealthReport/ihr-website#297]
**Describe the bug**
As I have seen some issues are raised related to the responsiveness of the ihr-website. I wanted to try the ihr-website in my mobile phone. but I cannot access the website even after having the stable internet connection. I can only get screen as loading after waiting for more than 10 minutes. I even tried to reload the website a no of times.

**To Reproduce**
Try to open the website through your mobile phones 

**Expected behavior**
we should be able to see the website

**Screenshots**
![Screenshot_20230302_102558](https://user-images.githubusercontent.com/101845170/222335824-a2a22422-e985-4c12-ac58-cffd9d07862c.jpg)

**Smartphone (please complete the following information):**

- vivo v20
- android
- google chrome

**Comment by thisiskaransgit** [comment]
Hey, it's working fine for me, I tried it on multiple devices, with different browsers, The issue is related to your Browser, try deleting the cache and closing all the tabs, and restarting the device.

**Comment by Ayeshashaik759** [comment]
I have tried to open the website after closing all tabs but still can't access it. May be the issue from my side but I can access it through my laptop. @thisiskaransgit if you don't mind can you share the screenshot of the website view in your phone.

**Comment by thisiskaransgit** [comment]
<b>You can see it's working fine, kindly close this issue, </b>
<img src="https://user-images.githubusercontent.com/92504666/222353433-ef1db503-cddb-4746-9bad-ae68c5abcbc8.jpeg " width="45%" height="45%" align="right">
</img>
<img src="https://user-images.githubusercontent.com/92504666/222355719-84fe44e5-4a5e-4227-aa87-5419c10fbb4e.jpeg" width="45%" height="45%" align="left">
</img>

**Comment by thisiskaransgit** [comment]
**Hey I've tried it on different devices and it's working fine, you can try solutions available on the web to solve the issue, but it's not related to the code, kindly close this issue** 
<img src="https://user-images.githubusercontent.com/92504666/222357145-890207b8-31ae-452a-92e4-85962ec7b009.jpeg" height="45%" width="45%" align="right"> </img>

<img src="https://user-images.githubusercontent.com/92504666/222357159-1bbc6133-ec9c-4fe4-a682-42eec79870ba.jpeg" height="45%" width="45%" align="left"> </img>

**Comment by Ayeshashaik759** [comment]
Kk thanks for reply i will close this issue
