### ISSUE TITLE
Network delay graph is not cleared when changing date

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#299]
**Describe the bug**
When we change the date on the website, the network delay graph will show both data from the old and new dates.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/networks/AS2497
2. Click on the calendar icon next to the date and select a past date (e.g. Feb. 24th, 2023)
3. Scroll down to Network Delay
4. See the graph shows the past data for the selected date and also the current data

**Expected behavior**
Other graphs are cleared before plotting the new data. We expect the same here.

**Screenshots**
The problem:
![image](https://user-images.githubusercontent.com/1373917/222635565-54c7b89b-09d5-4fd7-a7d1-8a5e325cf56e.png)

The expected graph:
![image](https://user-images.githubusercontent.com/1373917/222635672-0033f2cd-f8e4-460f-a40f-6b0b8d58b593.png)

**Comment by aabhas-sao** [comment]
hey @romain-fontugne I will like to work on this.

**Comment by Aniket762** [comment]
> hey @romain-fontugne I will like to work on this.

Go for it.

**Comment by aabhas-sao** [comment]
<img width="1430" alt="Screenshot 2023-03-03 at 11 08 05 AM" src="https://user-images.githubusercontent.com/58210877/222640279-f4308b11-7323-46d5-be92-50086d4cdeed.png">

It looks fine when running locally.

**Comment by Aniket762** [comment]
Hey @aabhas-sao did you try running the production build? Try building with `npm run build` then spin up the prod server. 

But, I guess the prod server has some issues when it runs in localhost. When I was configuring the deployment pipeline with Vercel. It was not building.

@romain-fontugne can you please share, how to run the prod server in localhost? Because, even for me in development server the issue is not present.

**Comment by Aniket762** [comment]
Hey, @aabhas-sao did you get a chance to spin up the prod server in localhost to check out the error? Try running `npm i -g serve` post installing the module run `serve -s dist`.  

Actually, there is an issue that needs to be fixed to spin up the prod server on your computer. I will get it fixed and comment back over here, and post that resolves it. I faced the error while setting up, the Development Deployment Pipeline, but somehow forgot to push the changes.

**Comment by Aniket762** [comment]
> <img alt="Screenshot 2023-03-03 at 11 08 05 AM" width="1430" src="https://user-images.githubusercontent.com/58210877/222640279-f4308b11-7323-46d5-be92-50086d4cdeed.png">
> 
> It looks fine when running locally.

Hey, @aabhas-sao did you get a chance to spin up the prod server in localhost to check out the error? Try running npm i -g serve post installing the module run serve -s dist. Before that make sure to build with `npm run build`

**Comment by Aniket762** [comment]
Also, @aabhas-sao there is an error which I faced while running the prod serve in localhost and even while setting up the development deployment CI/CD pipeline. 

Make sure to change the public path from `/ihr/` to `/` in `vue.config.js`. You would get the prod env in your local setup

**Comment by thisiskaransgit** [comment]
> Also, @aabhas-sao there is an error which I faced while running the prod serve in localhost and even while setting up the development deployment CI/CD pipeline.
> 
> Make sure to change the public path from `/ihr/` to `/` in `vue.config.js`. You would get the prod env in your local setup

Ohh boy, it has been a long-running issue in the repo, everytime we have to do this while running the production build, we should also be looking for a solution for this now, I hope changing the path won't trigger another set of new bugs.

**Comment by aabhas-sao** [comment]
> > <img alt="Screenshot 2023-03-03 at 11 08 05 AM" width="1430" src="https://user-images.githubusercontent.com/58210877/222640279-f4308b11-7323-46d5-be92-50086d4cdeed.png">
> > It looks fine when running locally.
> 
> when the page loads for the first time, it looks good. But if you change the date using the calendar at the top of the page then you'll see the bug

hey @romain-fontugne, I have opened a PR to fix this. Also we are having issues running production build running locally as @Aniket762 and @thisiskaransgit pointed out, will look in to that later.
