### ISSUE TITLE
Proposal to setup Prettier as code formatter

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#30]
Currently, this codebase is not using any code formatting tool and linting but people tend to use separate tools for these two jobs i.e. ES Lint for code listing & managing errors & Prettier for code formatting.

## Solution 
[Prettier](https://prettier.io/) is a tool that automatically makes your code more readable and consistent with your project's style guide. It integrates with your editor, so your code is tidied up every time you save your changes.

Why use Prettier? https://prettier.io/docs/en/why-prettier.html

@romain-fontugne sir, I am sending a PR for the issue, in case you don't want it feel free to close the issue and the linked PR. I also plan to add `editor configuration file` to keep the code structure and layout uniform throughout.  Adding the code formatting tool will surely increase DX.

**Comment by romain-fontugne** [comment]
Thanks!
