### ISSUE TITLE
UI changes to the navbar

### ISSUE THREAD

**Issue by Ayeshashaik759** [InternetHealthReport/ihr-website#303]
I want to make justify-content property of items in the navbar to be space-around.
![navbarihr](https://user-images.githubusercontent.com/101845170/222715637-d0eaca57-8830-489e-bcdf-bf628f03beee.png)

**Comment by romain-fontugne** [comment]
It looks like this year multiple people want to change the layout of the navbar :)

I think the justify-content looks good for small screens but I prefer the way it is now on large screens. I'd be glad to hear what other people think, but for me having the logo and search bar all to the left is quite standard. That's how it is done on github and gmail.

**Comment by Ayeshashaik759** [comment]
Yah in case of large screens the navbar is looking good as the way it is now. But in case of small screens can I implement the changes.

**Comment by romain-fontugne** [comment]
ok, let's do the change only for small screens

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir someone already make the PR for small screen before the @Ayeshashaik759 created this issue.
You already merged it here is the [Link](https://github.com/InternetHealthReport/ihr-website/pull/302)
I would say @Ayeshashaik759 so can work on some other issue.Also you can delete the PR. 
Also Please check once before creating any issue might be the chance someone already did:)
Thanks
