### ISSUE TITLE
creative commons website opens in the same tab

### ISSUE THREAD

**Issue by Ayeshashaik759** [InternetHealthReport/ihr-website#305]
As all the external website links opens in a new tab in ihr-website. In the footer section when we click on the license links the creative commons website opens in the same tab. so I want to change the code so that the creative commons website opens in a new tab

**Comment by lord2anil** [comment]
I wanţto work on this issue please assine me

**Comment by Ayeshashaik759** [comment]
Actually I too am a contributor and i want to make the changes if any of the mentor approves this issue.

**Comment by romain-fontugne** [comment]
Thanks for pointing this out. Go for it @Ayeshashaik759 !
