### ISSUE TITLE
Changing text color of elements in documentation navigation section

### ISSUE THREAD

**Issue by Ayeshashaik759** [InternetHealthReport/ihr-website#306]
At present when we navigate from one section other section to other section in the documentation we get a red border at bottom of our present section. I want to highlight the text color of our section also so that it looks more beautiful. 
![docnav](https://user-images.githubusercontent.com/101845170/222902351-8101b09d-9cc0-4e36-b36f-851095e52494.png)

**Comment by romain-fontugne** [comment]
I think the current implementation is good enough, let's not spend time on this
