### ISSUE TITLE
Footer enhancement 

### ISSUE THREAD

**Issue by devamisha** [InternetHealthReport/ihr-website#308]
![Screenshot_2023-03-05-09-04-53-856-edit_com brave browser](https://user-images.githubusercontent.com/125384128/222940336-ac658e4e-aa82-4525-ac7e-f480cfb8d34a.jpg)

I think the footer could be more interactive it's not looking that much good. 
What do you think? @romain-fontugne

**Comment by lord2anil** [comment]
i want to work on this issue , please assine me

**Comment by romain-fontugne** [comment]
yes, it could looks better. How can we improve this? @devamisha do you have any idea to make it looks better?

**Comment by anugcodes** [comment]
hey @romain-fontugne  , i have some suggestions for the footer

- we can move the IHR logo and links to a single column .
-  about the logo it would look good if the IHR logo would be at the top and below it the title 'Internet Health Report'. 
- also the IHR logo size can be increased as per the screen size.
- The links are aligned slightly to the right that is more visible in the mobile phones we can align them properly.
- The links do not feel like links we can improve them by adding some kind of text decoration like  making them underline or highlight on hover event.
- also making the text size of links a little less than the links heading.
- current hover effect on the icons can be changed to the one applied in the Thanks section.
- For the desktop screens i think the 2 column layout is good and we can change to single column layout with the logo and with icon links at the top followed by the links to different sections and below them the creative commons license.

these are my suggestion @devamisha , you can implement them if you agree and please mention yours too.

**Comment by Yh010** [comment]
@anugcodes the social media links could be brought below the IHR logo on the left, and the license statement can be brought to the complete bottom and extended throughout the bottom. What say?

**Comment by Amishakumari544** [comment]
I was thinking to explain using the design rather than explaining it written 😅

**Comment by Amishakumari544** [comment]
But your ideas are seems to be good @anugcodes 🙂

**Comment by anugcodes** [comment]
> @anugcodes the social media links could be brought below the IHR logo on the left, and the license statement can be brought to the complete bottom and extended throughout the bottom. What say? 

Yes exactly.

**Comment by romain-fontugne** [comment]
it would be easier to decide if you could show a screenshots (or several different design)? Then we can choose the one we prefer

**Comment by anugcodes** [comment]
@romain-fontugne sir, here are some screenshots of the above mentioned changes.

![desktop-view](https://user-images.githubusercontent.com/110781959/224705205-94cf80da-b2aa-446f-b866-703f48c8fe61.jpg)

![tablet-view](https://user-images.githubusercontent.com/110781959/224705251-3031a93e-ce80-48b6-abee-324ba1fafcf7.jpg)

![mobile-view](https://user-images.githubusercontent.com/110781959/224705313-e80861b2-58b9-4660-966d-f8a2bcf06b46.jpg)

**Comment by romain-fontugne** [comment]
looks good to me! who wants to work on this?

**Comment by anugcodes** [comment]
sure @romain-fontugne sir, i can do it.
