### ISSUE TITLE
Netlify Preview

### ISSUE THREAD

**Issue by devamisha** [InternetHealthReport/ihr-website#309]
As of now there is no deploy preview to see what changes contributors are doing.
It's better if we can add netlify preview to see the changes live in the website and then do the merge part.

What do you think?
@romain-fontugne 

If this is accepted, I am willing to work on it.

**Comment by Aniket762** [comment]
Go for it

**Comment by J0SAL** [comment]
Hey @devamisha, are you still working on the issue? 
I would also like to learn more about the issue and the solution, do you mind if we work on this together?
