### ISSUE TITLE
Potentially hiding the unecessary information

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [InternetHealthReport/ihr-website#310]
In the global report and network reports oftentimes the website does not possess any data related to the query.

I would like to change this by attempting to hide the vue component when it is unable to provide any information

![image](https://user-images.githubusercontent.com/72858215/223020101-1b7f0de2-b55d-40bf-b876-9a5eeb8dcd63.png)
![image](https://user-images.githubusercontent.com/72858215/223020136-98f75a0a-f586-4186-b478-a50b3013622b.png)

OR like this 

![image](https://user-images.githubusercontent.com/72858215/223020189-5cf071a5-31f2-4c52-b5f7-6c2e8de23100.png)

@romain-fontugne, if you do believe that would be a handy UI fix for the user then please relay the same. And if you so kindly would assign the issue to me.

**Comment by romain-fontugne** [comment]
Please go ahead, I think we should still show the headers ('AS Dependency', Network Delays', etc..) and make just make it grey?

**Comment by Mohamed-Ayaan358** [comment]
Thank you will get started soon enough, college is quite demanding atm :)

**Comment by Mohamed-Ayaan358** [comment]
Just an update I have found a method via which we can determine the value needs to be hidden or not

**Comment by Mohamed-Ayaan358** [comment]
@romain-fontugne I have been able to make a PR please do review it at your own time.

**Comment by Mohamed-Ayaan358** [comment]
I will most likely have to attempt a .redraw() on the plotly instance and have to see how I can initiate it.

That may be too much of an issue, so I can potentially remove the greying system for the last table as this is an inherent plotly problem.

Proof:
https://anvil.works/forum/t/plotly-rendering-on-window-resize/4647/3
