### ISSUE TITLE
Header enhancement 

### ISSUE THREAD

**Issue by Rithvik-padma** [InternetHealthReport/ihr-website#318]
I found that a few UI changes in the header section are necessary to make it look better like -

- Changing the position of the search icon
- Changing the alignment of the header elements by moving the menu entries to the right so that all the items are covering enough space makes it look neat.
- Changing the search bar view contents view by adding necessary padding.

@Aniket762 & @romain-fontugne I would like to work on this.

**Comment by kohasummons** [comment]
This looks like a good fix to the header issues. Welldone @Rithvik-padma

**Comment by romain-fontugne** [comment]
This was discussed before. We didn't really need this :D
But I've merged it because this issue is coming back too frequently. thanks

oh and please next time, make the PR after you've been assigned the issue

**Comment by Rithvik-padma** [comment]
@romain-fontugne Sorry sir I did not know this was not necessary, I felt that it looks nice if I shift the menu entries towards the right side of the header bar. Is it the case that the space was left to add some extra entries later?

**Comment by romain-fontugne** [comment]
no problem, let's move it back when needed!
