### ISSUE TITLE
Update the master branch to ihr-website

### ISSUE THREAD

**Issue by Althaf66** [InternetHealthReport/ihr-website#319]
when I run locally in my computer,(UI is better)
![Screenshot (353)](https://user-images.githubusercontent.com/114910365/224539231-a4bc0543-1e05-45c0-b5e8-f94e46d29271.png)
but I opened the ihr-website 
![Screenshot (352)](https://user-images.githubusercontent.com/114910365/224539300-7340803f-71b4-4cdd-ae41-4d737c5f21f5.png)
I think the master branch is not updated to the IHR website.I just opened this issue for just informing this problems @romain-fontugne.I am requested to solve this issue.

**Comment by romain-fontugne** [comment]
Thanks, I will deploy the new version soon. No need to create an issue for this. I usually deploy when we have new features or bug fixes. (The look of the website is actually the last thing our users are interested in :D )
