### ISSUE TITLE
Issue: Possible typo in header dropdown menu

### ISSUE THREAD

**Issue by yshv** [InternetHealthReport/ihr-website#328]
**Describe the bug**
Possible spelling mistake of English word 'resources' as French word 'ressources' under the Reports dropdown description of Routes Origin Validation and Country.

**To Reproduce**

1. Go to the Ihr-Website front page
2. Hover over 'Reports' on the dropdown menu in the header
3. Observe the spelling mistake "ressources" for description of 'Routes Origin Validation' and 'Country'.

**Solution**
Go to hr-website/src/views/Header.vue and correct lines 89 and 99. 

If this spelling is as intended please dismiss this issue.

**Comment by romain-fontugne** [comment]
oh, that's embarrassing. how come nobody pointed this out before.
Yes, that's a typo... that's how we write it in french! :P

**Comment by yshv** [comment]
Thank you, will do.
