### ISSUE TITLE
Proposal to add PWA with offline support

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#33]
A progressive web application is a type of application software delivered through the web, built using common web technologies including HTML, CSS, and JavaScript. It is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices. Progressive Web Apps (PWAs) allow developers to deliver an app-like experience to the user.

I would like to work on the issue, in case you don't want PWA support feel free to close the issue or the PR I am sending rn. 

PS. I have also written a blog on why is PWA important @romain-fontugne sir you may give it a read [here](https://dev.to/aniket762/pwa-learning-implementing-and-loving-ft-nextjs-under-2-mins-il7), although I am sure you know the importance of PWA way more than me, just wanted to share my viewpoint.

**Comment by Aniket762** [comment]
> Member

Sir, I am currently working on it. So basically what I need to do is add service-worker and manifest, I am trying to do, but getting some bugs hopefully will send the PR soon 😢

I don't think any substantial change in code is required, as I was thinking of using the user's cache memory to store most of the data and hence increasing UX and making our servers work better. So, it would benefit both the stakeholders for sure.

**Comment by romain-fontugne** [comment]
OK, thanks. Let me know if I can help

**Comment by Aniket762** [comment]
Hello developers, the labels for this issue have been changed and no one has been assigned as of now. `first-timers-only` label promotes first-timer contributors and gives them space to contribute to projects having large codebases. This being a particularly simple issue to resolve would give them a headstart in open source. 

If you are someone who wants to get started in open source or want to contribute to an organization that is catering to a large audience, this is the right place for you to begin. 

If you are interested in resolving the issue feel free to comment below and I would assign it to you 💪

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 , I would like to work on it

**Comment by Aniket762** [comment]
> Hey @Aniket762 , I would like to work on it

Sure go for it
