### ISSUE TITLE
Getting many warnings in console.

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#338]
@romain-fontugne I am getting many warning in the console which seems to be due to the same reason, [vue-i18n] Cannot translate the value of keypath.

I think I can fix it. Please assign this issue to me.
Thanks!

**Comment by thisiskaransgit** [comment]
What are warnings are you referring to, could you provide more context.
Screenshot?
Steps to reproduce?
OS?

**Comment by kkartik07** [comment]
@thisiskaransgit 
![image](https://user-images.githubusercontent.com/87076033/225449385-240d8719-71c2-4c00-b240-9a04f395da4b.png)
I am using Windows

**Comment by Arunjagan12** [comment]
hey @kkartik07 , can you provide the steps to reproduce as I am also using windows os as well??

**Comment by kkartik07** [comment]
@Arunjagan12 these warnings come anywhere in the website , I think it comes due to the Header section.
Just keep your console open, you will find it

**Comment by romain-fontugne** [comment]
go ahead @kkartik07
