### ISSUE TITLE
Invalid props in Countries.vue file

### ISSUE THREAD

**Issue by Rithvik-padma** [InternetHealthReport/ihr-website#345]
**Describe the bug**
The props 'noAS' should have a type of boolean but instead it has the type of String

**To Reproduce**

1. Go to 'src/views'
2. Click on 'Countries.vue'
3. Scroll down to 'network-search-bar' tag.
4. You will find that the type of the prop 'noAS' will be String

**Expected behavior**
The prop type of 'noAS' should be boolean.

**Comment by romain-fontugne** [comment]
please wait to be assigned before sending the PR
