### ISSUE TITLE
Add validation and documentation for custom events emitted in Vue.js components

### ISSUE THREAD

**Issue by mhmdawnallah** [InternetHealthReport/ihr-website#355]
**Is your feature request related to a problem? Please describe.**

Yes. Currently, when I'm reading through a Vue.js codebase, I've noticed that custom events are being emitted in the component without being defined in the `emits` option. This makes it difficult to understand which events the component is emitting, and it also lacks type validation and documentation for these events.

**Describe the solution you'd like**

I would like to suggest that we add documentation and validation for all custom events emitted by a Vue.js component. To achieve this, we could define all custom events in the `emits` option of the component. This would provide better documentation for the component's API and also help prevent errors when emitting custom events.

**Describe alternatives you've considered**

One alternative could be to rely on convention-based naming for custom events, which would allow developers to infer the name and purpose of the event based on its name. However, this would still lack type validation and could result in naming conflicts.

**Additional context**

I believe that adding documentation and validation for custom events would improve the maintainability and reliability of Vue.js components, as well as make it easier for developers to work with them. I believe it would be a useful feature to add to the IHR website codebase.

**Comment by romain-fontugne** [comment]
thanks, that's indeed needed
