### ISSUE TITLE
UI issues with text alignment in "Global Reports" section

### ISSUE THREAD

**Issue by AhnafSulficar** [InternetHealthReport/ihr-website#357]
Description: When navigating to the "Reports>Global" section of the web app, there are several UI issues that are causing problems with text alignment. Specifically, the text is not properly aligned with the buttons and input fields, causing confusion and frustration for users.

Steps to reproduce:

Open the web app.
Navigate to the "Global>Reports" section.
Observe that the text is not properly aligned with the buttons and input fields.

Expected behavior: The text in the "Global>Reports" section should be properly aligned with the buttons and input fields, making it clear and easy to understand.

Actual behavior: The texts in the "Global>Reports" section is not properly aligned with the buttons and input fields, causing confusion and frustration for users.

https://ihr.iijlab.net/ihr/en-us/global_report?filter_level=1&last=3&date=2023-03-21

Screenshots:

![IMG_2355](https://user-images.githubusercontent.com/89102131/226529449-29a6b853-27f6-4882-ba50-602277fea39d.jpg)
![IMG_2354](https://user-images.githubusercontent.com/89102131/226529459-87bf3a0a-0148-4d53-a69d-d49b1cee5b76.jpg)
![IMG_2353](https://user-images.githubusercontent.com/89102131/226529460-a662739d-d7f9-47ad-a641-eee755d5a67e.jpg)

Additional information:

This issue is only present in the "Global>Reports" section of the web app.
The issue persists across different browsers in Mobile View.
This issue has been reported by multiple users, indicating that it is not an isolated incident.
This issue is impacting the usability of the web app and should be addressed as soon as possible.

LABELS: UI, MobileView , beginner-friendly

**Comment by Soohti** [comment]
Maybe we can move the input field to a new row? I'm going to work on this.

**Comment by sharmaachintya08** [comment]
This issue is solved, check it out
![Screenshot 2023-03-21 174405](https://user-images.githubusercontent.com/80171589/226602781-32d896b3-8417-4e42-8540-ee31ec86da73.png)

**Comment by AhnafSulficar** [comment]
Yes, This issue seems to be solved in the master branch repo , however in the hosted version has this issue.
