### ISSUE TITLE
UI Improvement on page https://ihr.iijlab.net/ihr/en-us/api (Mobile)

### ISSUE THREAD

**Issue by sharmaachintya08** [InternetHealthReport/ihr-website#359]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem, the page is fully functional. This issue is for a UI change as the UI on mobile or smaller screens is a little bit disoriented and hard to understand. here's a screenshot of the UI on a mobile device. The names such as "countries", "disco", and "events" on https://ihr.iijlab.net/ihr/en-us/api (smaller screens) shouldn't be dispersed like this, it makes it harder to read and understand
![Screenshot 2023-03-21 183630](https://user-images.githubusercontent.com/80171589/226614986-dea76e1b-71a3-4ef3-831d-3ed1fedcfb2c.png)

**Describe the solution you'd like**

The UI presented on a desktop site page or for bigger screens is much more easier and efficient to understand, whereas "countries", "disco", and "events" are much easier to understand as they are well formatted and in the same line. For smaller devices, this type of formatting should be used on the web page where such names are present in the same line as the "get" button. This little change will make it much easier to understand the web-page
![Screenshot 2023-03-21 182834](https://user-images.githubusercontent.com/80171589/226613585-0b3bb915-62f3-4ac0-8618-aa03b92e6912.png)

**Describe alternatives you've considered**

Any alternative would be a huge change in the whole UI structure of the block.

**Comment by Rithvik-padma** [comment]
@sharmaachintya08 I have already opened a PR on this and the problem will not persist after it gets merged.

Btw this issue is already present, so u can just close this to avoid redundancy.
