### ISSUE TITLE
npm run build with errors (error: Unexpected console statement (no-console)

### ISSUE THREAD

**Issue by sharmaachintya08** [InternetHealthReport/ihr-website#360]
**Describe the bug**
Whenever we try to build the project the build. The project is built with the same error occurring multiple times:
   - error: Unexpected console statement (no-console)
 

**To Reproduce**

1. Open powershell in administrative mode
2. go to the project dir using ' cd '
3. run comand : npm run build

**Expected behavior**
The build should run without any errors

**Screenshots**
error screen shot : 
![Screenshot 2023-03-21 233707](https://user-images.githubusercontent.com/80171589/226703585-1db99002-38db-4814-a768-8abe1eb5fd6d.png)

**Desktop (please complete the following information):**

- OS: windows 
- Browser - firefox
- Version - 111.0

**Comment by romain-fontugne** [comment]
I guess this was resolved by #400
