### ISSUE TITLE
Fix: The No data available message in various tables can be more prominent

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#374]
Whenever there is no data available , we get a small message showing "No data available" at the bottom of the table. 
I think it's size should be little more and also at the center instead of being at start of the row.
This is common for all tables when No data is available.
![image](https://user-images.githubusercontent.com/87076033/227857644-e8e50619-870e-48c5-9088-3035176b1fe4.png)

@romain-fontugne @Aniket762 Please assign this issue to me.
Thanks.

**Comment by romain-fontugne** [comment]
Sure it could be better. Please let us know how you'd improve that

**Comment by kkartik07** [comment]
@romain-fontugne I was thinking of moving it to the center and increase the size and padding as well.
It would look something like this:
![image](https://user-images.githubusercontent.com/87076033/229373375-0870266e-c219-43ed-b6a4-7e314209582a.png)

But I am having problem finding the code related to it. It would be helpful if someone can help me do this.
Thanks.

**Comment by Skshmshah2611** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/91542654/230714712-ad917544-d779-424f-b306-b812f686509d.png)


hello @romain-fontugne ,I think this is how the issue needs to be fixed ,can you please assign me .
thanks!

**Comment by romain-fontugne** [comment]
@Skshmshah2611 you can make a PR for it. @kkartik07 can I ask you to review the PR?

**Comment by Skshmshah2611** [comment]
ok @romain-fontugne sir
