### ISSUE TITLE
Fix: Button styling can be improved 

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#375]
Button styling can be improved and made more consistent in the plots for each country in covid19 section.

Currently, the "Clear all" button is not styled properly and it doesn't match the design of "Add" button due to which it doesn't look good.

I want to change the styling of it to look more consistent. 
![image](https://user-images.githubusercontent.com/87076033/227859162-72cda110-a930-473e-806a-551cb732c750.png)

@romain-fontugne @Aniket762 Please assign this issue to me. 
Also suggest some other changes in style if you think necessary.
Thanks.

**Comment by romain-fontugne** [comment]
go for it!

**Comment by kkartik07** [comment]
@romain-fontugne Apart from the design issue in the same page, I think the "Add more destinations" toggler at the bottom should be moved at the top as the user may not be able to see it when at the bottom.

Before
![image](https://user-images.githubusercontent.com/87076033/228760931-84e4c802-5b69-4711-891f-6f6cae02d8bf.png)

After
![image](https://user-images.githubusercontent.com/87076033/228760730-6e483dde-2ac3-41cc-862f-d1963edc8c63.png)

I would like to fix this as well.
Thanks.
