### ISSUE TITLE
Some data not loading in Network Delays section and also its not Mobile responsive.

### ISSUE THREAD

**Issue by Vidip-Ghosh** [InternetHealthReport/ihr-website#377]
**Describe the bug**
Data is not available for some services. 

**Screenshots**
<img width="1674" alt="Screenshot 2023-03-28 at 18 29 47" src="https://user-images.githubusercontent.com/91741581/228244907-d4c89582-d45d-4400-a04c-aa867d259271.png">
<img width="1680" alt="Screenshot 2023-03-28 at 18 22 50" src="https://user-images.githubusercontent.com/91741581/228244927-81d0e3ca-8e45-45e8-b3e3-71017b0f407e.png">
<img width="495" alt="Screenshot 2023-03-28 at 18 41 55" src="https://user-images.githubusercontent.com/91741581/228247835-b76a02dd-8583-47a6-b92c-82129edb1115.png">

**Comment by Althaf66** [comment]
I am working on the mobile responsive

**Comment by romain-fontugne** [comment]
It is possible that we don't have data for some networks. So make sure with the API if it is a UI problem or not

**Comment by Vidip-Ghosh** [comment]
I can work on the issues of UI. @romain-fontugne please assign the work.

**Comment by romain-fontugne** [comment]
sure I can assign you this issue, but I'm not sure what is the problem you are trying to fix?

**Comment by romain-fontugne** [comment]
Thanks @thisiskaransgit . So I guess we can close this.
