### ISSUE TITLE
Minor UI improvements in Documentation section

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#380]
In the document section, I suggest some UI changes so that it is more clearer to the end-user to navigate and explore.

1. Increase margin between various headers from the previous section.
2. Increase font-weight for the headers so that they can be distinguished.
3. Introduce some styling for code block so that they can be observed easily.

These changes are important for better usability of the docs.
![image](https://user-images.githubusercontent.com/87076033/228463464-87d36061-13f7-4a72-8cab-0988e4cebf62.png)

@romain-fontugne @Aniket762 Please review the issue and if found necessary, I will make PR asap.
Thanks!

**Comment by harshlancer** [comment]
Can I solve this issue please?
