### ISSUE TITLE
Moving Stylus styles to a separate file

### ISSUE THREAD

**Issue by J0SAL** [InternetHealthReport/ihr-website#387]
**Is your feature request related to a problem? Please describe.**
Currently, the Stylus styles are included in the VueJS file, which can make the code difficult to manage and maintain. 

**Describe the solution you'd like**
To improve code organization and readability, we should move the Stylus styles to a separate file. This can be achieved by creating a new file with a .styl extension and moving the Stylus styles to it. We can then link to this file in the HTML file using a <link> tag. This will improve the overall structure of our codebase and make it easier to maintain and update the styles.

The targetted files are:
- [Contact.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Contact.vue)
- [Corona.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Corona.vue)
- [Footer.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Footer.vue)
- [GlobalReport.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/GlobalReport.vue)
- [Header.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Header.vue)
- [Home.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Header.vue)
- [PageNotFound.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/PageNotFound.vue)
- [PersonalPage.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/user/PersonalPage.vue)

**Comment by J0SAL** [comment]
@Aniket762  @romain-fontugne sir, I would love to work on this issue.

**Comment by romain-fontugne** [comment]
thanks for looking at this. Then do you suggest to put all these styles to src/styles/ihr.style.styl?

I think it is a good idea, go for it

**Comment by J0SAL** [comment]
> thanks for looking at this. Then do you suggest to put all these styles to src/styles/ihr.style.styl?
> 
> I think it is a good idea, go for it

@romain-fontugne  sir, As some styles are quite large (more than 100 lines) I was thinking of creating individual .styl files for each of the .vue files. The directory structure for these files would be the same as how the src/views/* structure

more specifically,

- [Contact.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Contact.vue) -> src/styles/contact.styl
- [Corona.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Corona.vue) -> src/styles/corona.styl
- [Footer.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Footer.vue) -> src/styles/footer.styl
- [GlobalReport.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/GlobalReport.vue) -> src/styles/globalReport.styl
- [Header.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Header.vue) -> src/styles/header.styl
- [Home.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/Header.vue) -> src/styles/home.styl
- [PageNotFound.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/PageNotFound.vue) -> src/styles/pageNotFound.styl
- [PersonalPage.vue](https://github.com/InternetHealthReport/ihr-website/blob/master/src/views/user/PersonalPage.vue) -> src/styles/user/personalPage.styl

Do you think it's a good idea? or should I put everything to the src/styles/ihr.style.styl file like you mentioned before?
Also, sir could you assign me the issue, so that I can start working on it.

**Comment by thisiskaransgit** [comment]
Hey @J0SAL, my approach would be to move the repeating elements to the global styles along with that you can extend the global style for all variables including the headlines, paragraphs, and hyperlinks as these are being used multiple times but their default value hasn't been set. We have to focus on reducing code redundancy too.

And you can let the styles unique to the components be as it is. As for the header and footer, you can create separate style files.

**Comment by J0SAL** [comment]
> 

Okay, noted

**Comment by romain-fontugne** [comment]
@thisiskaransgit are you ok to review this PR?

**Comment by thisiskaransgit** [comment]
@romain-fontugne Sure, will do it  :+1:

**Comment by romain-fontugne** [comment]
thanks
