### ISSUE TITLE
Fix: Capitalised Various labels in Global report

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#396]
There are some boxes which shows certain number of alarms and other data. For that the labels are starting with lowercase letters which looks a bit odd.
So I am changing it to Uppercase wherever necessary.

Before:
![image](https://user-images.githubusercontent.com/87076033/229232321-40a51090-685c-449e-b56d-5664e078ec5c.png)

After:
![image](https://user-images.githubusercontent.com/87076033/229232251-1279a8f5-4c3e-40d1-a875-ba92d56d7ab1.png)

@romain-fontugne @Aniket762 I would like to change this. 
Thanks.

**Comment by thisiskaransgit** [comment]
Hey, @kkartik07 you have been assigned multiple PRs, First, complete the assigned ones and let the maintainers review and merge them, then you can work and ask to get assigned to others. This helps them to keep track of all issues.

**Comment by kkartik07** [comment]
> Hey, @kkartik07 you have been assigned multiple PRs, First, complete the assigned ones and let the maintainers review and merge them, then you can work and ask to get assigned to others. This helps them to keep track of all issues.

Ok sure
