### ISSUE TITLE
Responsiveness in Network Delays page

### ISSUE THREAD

**Issue by Vidip-Ghosh** [InternetHealthReport/ihr-website#399]
**Describe the bug**
Search bar, search button are overlapping on top of each other in when size of page changes. Also graph is not properly visible. I would like to work on this issue @romain-fontugne 
Please assign this to me

**Screenshots**
<img width="496" alt="Screenshot 2023-04-01 at 13 55 08" src="https://user-images.githubusercontent.com/91741581/229275107-17f8ba6b-f0ab-4d94-8a64-3771d9a5040f.png">

<img width="498" alt="Screenshot 2023-04-01 at 14 00 16" src="https://user-images.githubusercontent.com/91741581/229275222-5da00dc6-1a1f-46af-a1cf-4397dcb3d3f3.png">

**Comment by thisiskaransgit** [comment]
1. Update the issue with the correct message and title, the Network Delay is a dropdown component, not a page, along with that use the issue template and add all the related information. 

2. One of the things is that the website is not updated with respect to the github source code, so just double-check whether the issue persists in the development environment or not.

**Comment by romain-fontugne** [comment]
I believe that was fixed in a recent PR. Reopen if the problem persists
