### ISSUE TITLE
Dropdown menu moving on scroll

### ISSUE THREAD

**Issue by Vidip-Ghosh** [InternetHealthReport/ihr-website#403]
**Describe the bug**
On scrolling the page, dropdown menu is not at its proper position. 

**Screenshots**

https://user-images.githubusercontent.com/91741581/229277262-60217d43-35ea-478f-b83b-ab871d33ae9b.mov

**Comment by Rithvik-padma** [comment]
@romain-fontugne @Aniket762 I would like to work on this issue
Thanks!

**Comment by thisiskaransgit** [comment]
Thank you for pointing out that issue, but PLEASE use the issue template and include the steps to reproduce, desired behavior, OS, browser, etc. Kindly Update your issue.

**Comment by romain-fontugne** [comment]
@Vidip-Ghosh are you planning to fix this? or can I assign @Rithvik-padma ?

**Comment by Vidip-Ghosh** [comment]
You can assign it to other person

**Comment by romain-fontugne** [comment]
ok thanks, @Rithvik-padma go for it

**Comment by mohamedawnallah** [comment]
Closing the issue, Solved in #435
