### ISSUE TITLE
Problems I identify in the navigation bar

### ISSUE THREAD

**Issue by HarshDubey1011** [InternetHealthReport/ihr-website#419]
1. I think all three items(logo, input and links) on the navigation should be equally space-between them(As you can see in below image). It should look good and it will be better user experience.

![IHR_Navigation_Bar](https://user-images.githubusercontent.com/64142529/229333594-5d85ccae-a261-4486-a357-8361654a7d5a.png)

2. After 1024px x 334px the hamburger menu appears and most of the space on the right side is empty which does not look good in the website.

![IHR_1024px_below](https://user-images.githubusercontent.com/64142529/229334024-a5bb305f-d7b0-4593-95d2-e921a2413853.png)

3.  I came up with the two solutions:
				a. We continue showing links till 900px by reducing there font size.
				b. Or if we really want the hamburger menu then we should equally space all three items with slightly increasing the size of the input field.

what do you think sir @romain-fontugne.

**Comment by mohitmohlia** [comment]
can i work on this ?

**Comment by anugcodes** [comment]
hey @HarshDubey1011 sorry but this issue has been fixed, you can see that by setting up this repo in your local machine and running it.
![issuecloser1](https://user-images.githubusercontent.com/110781959/229797530-2f447e60-c8b7-4cdd-9f15-61fb1110e930.jpg)


![issuecloser2](https://user-images.githubusercontent.com/110781959/229797626-9c91b95f-446f-49b9-a294-97d5c61d664b.jpg)
So i suggest you should close this issue.

**Comment by HarshDubey1011** [comment]
Thanks @anugcodes
