### ISSUE TITLE
Expansion panel not working properly inside country reports.

### ISSUE THREAD

**Issue by crediblebilal** [InternetHealthReport/ihr-website#421]
**Describe the bug**
There are 3 expansion panels inside the Country Reports section namely: **Network Dependency**, **Route Origin Validation**, and **Network Delay**. The first two are working fine, but there are issues with the **Network Delay** panel. Once the data gets displayed, we can not close this expansion pane. If we try to close it, it gets displayed(expanded) again.

**To Reproduce**

1. Go to 'Home Page'.
2. Click on 'Reports'.
3. In the dropdown, select 'Country'.
4. Enter any country name or click on any country name shown in examples, say United States.
5. Three panels:  **Network Dependency**, **Route Origin Validation**, and **Network Delay** will be shown.
7. Try to close and expand the **Network Delay** panel to see the error.

**Expected behavior**
We should be able to expand and close the **Network Delay** panel like the other two.

**Screenshots**
![image](https://user-images.githubusercontent.com/55330484/229351898-7337915f-8547-42aa-81ba-97087760f153.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome, Brave

**Comment by romain-fontugne** [comment]
yes, that's a bug, do you wanna try to fix it?

**Comment by crediblebilal** [comment]
Yes, I'll do it. Assign it to me.

**Comment by kkartik07** [comment]
@romain-fontugne I had also encountered same issue and it was getting solved by removing this line:
![image](https://user-images.githubusercontent.com/87076033/230705181-da3f4090-da52-4614-a143-7cfd6af4581a.png)

**Comment by kkartik07** [comment]
Actually the call to NetworkQueryDelay is taking place two times which is causing it to reopen again. And after removing the `@display=displayNetDelay` line, its calling it only once, so it functioning properly then.

I found out this by checking the console messages
