### ISSUE TITLE
Global Report page's internal link incorrectly changes the URL

### ISSUE THREAD

**Issue by Soohti** [InternetHealthReport/ihr-website#423]
**Describe the bug**
This issue was brought up by https://github.com/InternetHealthReport/ihr-website/issues/382#issuecomment-1489781191.
I updated the description so that it's more accurate.
When we click the alarm buttons, the page will jump to the corresponding section. However, the URL of the page will be broken. The result is that when we copy and paste the link we'll be unable to see the site.

**To Reproduce**

> 1. Go to: https://ihr.iijlab.net/ihr/en-us/global_report
> 2. Click on any of the alarm buttons (example : Network Delay )
> 3. See the updated query
It should have been
//ihr.iijlab.net/ihr/en-us/global_report?[filter]#networkDelay
but, it is coming as //ihr.iijlab.net/#networkDelay

**Expected behavior**
The link should be correctly updated and remain functional after copy and paste.

**Screenshots**
![](https://user-images.githubusercontent.com/110781959/228551594-893c84c8-31cb-4375-abce-d6c3a5d6892a.jpg)
Screenshot by https://github.com/InternetHealthReport/ihr-website/issues/382#issue-1645895334

**Comment by romain-fontugne** [comment]
Thanks, yes that's a bug we want to fix
