### ISSUE TITLE
Add Pop-up Feature on Internet Health Report for Graphs with Detailed Information and API Links

### ISSUE THREAD

**Issue by ConnectBhawna** [InternetHealthReport/ihr-website#425]
**Is your feature request related to a problem? Please describe.**

The pop-up feature on the Internet Health Report that allows users to click on a graph and get more details and links to the API is important for several reasons.

Firstly, it enhances the user experience by providing easy access to more information about the data presented in the report. Users can quickly obtain detailed information on a specific data point they are interested in without having to navigate away from the report. This feature also saves time for users who may not want to scroll through the entire report to find the information they are looking for.

Secondly, it promotes transparency by providing access to the API, which allows users to verify the data presented in the report. This helps to build trust with the users and ensures that the information presented is accurate and up-to-date.

Thirdly, it enhances the usability of the report by providing additional resources that users can use to further explore the data presented. By providing links to the API, users can access the data directly and use it to conduct their own analysis or create custom visualizations.

Overall, the pop-up feature on the Internet Health Report is an important tool that enhances the user experience, promotes transparency, and provides users with additional resources to explore the data presented in the report.

**Describe the solution you'd like**
For the above thing , i want to build the dashboard something like this in the image
![IHR_PROPOSAL(1)](https://user-images.githubusercontent.com/81790585/229579636-2ba6706a-9e30-4565-bd95-7fbee6f76050.png)

**Additional context**
@romain-fontugne sir can you please assign this to me i am looking to work in this issue.
Thanks

**Comment by romain-fontugne** [comment]
Thanks, I think a bit less intrusive popups would be nice. For example just a small pop-up at the bottom right corner, with 'skip' and 'next' button, so that user can still use the website as usual if it is already familiar with the website

**Comment by ConnectBhawna** [comment]
![issue_image](https://user-images.githubusercontent.com/81790585/230705289-38cd8af7-4d59-4f55-a095-8ccaa2a0620b.png)

@romain-fontugne sir is this looks good to you let me know, than i will start code it out :)
Thanks

**Comment by Skshmshah2611** [comment]
hello @romain-fontugne Can you please assign this to me

**Comment by ConnectBhawna** [comment]
Hey @Skshmshah2611 is mentor approve this , i will work on this issue.
Thanks

**Comment by Skshmshah2611** [comment]
hey @ConnectBhawna would you like to work together if mentor allows.
