### ISSUE TITLE
Feat: Enable Generate report button for all reports

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#430]
**Is your feature request related to a problem? Please describe.**
In various reports, there is a generate report button which downloads the entire report but it has been removed for now.

I am referring to these buttons : 
![image](https://user-images.githubusercontent.com/87076033/229999794-484f9aa5-7f4e-43b8-afa4-b1677cb0f53d.png)

@romain-fontugne @Aniket762 Can I know the reason for it to be removed? 
I would like to include that and also style that button so that the user can use it to download the report.

**Comment by romain-fontugne** [comment]
I think we need a better UI for that. This is a very minor feature for our
users, so I don't think we need such large button at the top of each report

**Comment by kkartik07** [comment]
@romain-fontugne Yes, I will be changing the UI of it and then only include it. I had attached this image just to give a reference for the button.
If you think this is necessary, I can work on it.

**Comment by romain-fontugne** [comment]
I don't think this is *necessary* right now For the past month i have been spending to much time on minor tweaks in the frontend. Sorry but I'd like to focus more on important features/bugs
