### ISSUE TITLE
Increasing UI in small screens for metis atlas probe deployment

### ISSUE THREAD

**Issue by Althaf66** [InternetHealthReport/ihr-website#436]
**BEFORE**
We cannot see the proper graph in the screen for mobile users.
![Screenshot (389)](https://user-images.githubusercontent.com/114910365/230659916-7f165bc6-242f-43d5-bd88-7b3a9b501612.png)
**AFTER**
Now we can see graph at any screen size.
![Screenshot (390)](https://user-images.githubusercontent.com/114910365/230660373-7f161428-bdef-492f-82e7-521f11a72294.png)

**could you assign me to this issue**, **@romain-fontugne**

**Comment by Skshmshah2611** [comment]
hello @romain-fontugne sir, I understood the issue and also have an approach to fix this .So could you please assign me to this issue

**Comment by Althaf66** [comment]
Hey @Skshmshah2611, I already fix this issue. Will I open the pull request @romain-fontugne.

**Comment by romain-fontugne** [comment]
Thanks! go for it @Althaf66
