### ISSUE TITLE
Make sponsor icons clickable to redirect users to their websites.

### ISSUE THREAD

**Issue by imad10902** [InternetHealthReport/ihr-website#438]
**Is your feature request related to a problem? Please describe.**
If the traffic to sponsor websites increases, this would result in increased reach for the sponsors.

**Describe the solution you'd like**
We can add their website links to their icons on IHR website.

**Comment by imad10902** [comment]
@romain-fontugne Sir, assign this to me if you agree on the feature.
Thank You

**Comment by Skshmshah2611** [comment]
@romain-fontugne this will definitely increase the reach of the sponsors also will not create mess on the page . Please assign this to me 
thanks.

**Comment by romain-fontugne** [comment]
Icons are already clickable. Please try the code from the repo,  ihr.iijlab.net is not showing the latest version
