### ISSUE TITLE
feat: more filter options for the global report

### ISSUE THREAD

**Issue by anugcodes** [InternetHealthReport/ihr-website#445]
**Is your feature request related to a problem? Please describe.**
Currently in the global reports page the filter input in the top helps only to filter the whole report by the As number only.

**Describe the solution you'd like**
It would be more useful if more filter options could be added to the global report. It would make filtering the required data more easy. filter options like country or city names etc

**Describe alternatives you've considered**
**Additional context**

hey @romain-fontugne , @Aniket762  what do you think  and please correct me i am wrong or if this is already implemented.

**Comment by romain-fontugne** [comment]
yes, this is needed but I believe this will change as part of gsoc23. We have a project on improving the whole global report that @mhmdawnallah is working on
