### ISSUE TITLE
Display the current IP, Prefix, AS, ASN, and Country where the user's device is connected to

### ISSUE THREAD

**Issue by roopeshsn** [InternetHealthReport/ihr-website#446]
**Is your feature request related to a problem? Please describe.**
It would be nice if the current IP, Prefix, AS, ASN, and Country were displayed to which the user's device is connected on the network report page.

**Describe the solution you'd like**
The current IP, Prefix, AS, ASN, and Country should be displayed on the network report page. 

**Additional context**

I attached a mockup for the same.

![launchpad_mockup](https://user-images.githubusercontent.com/70762571/233817698-aaf7c2e0-52e1-4271-afb1-c8dbbf3b1bf5.png)

**Comment by roopeshsn** [comment]
And, I would like to work on this!

**Comment by romain-fontugne** [comment]
yes, it would be nice to have that implemented.

**Comment by 0xAnon0602** [comment]
@roopeshsn Are you still working on it? 
If not then I would like to work on this @romain-fontugne

**Comment by roopeshsn** [comment]
> @roopeshsn Are you still working on it? If not then I would like to work on this @romain-fontugne

This is still in the discussion phase.
