### ISSUE TITLE
Fix: Use of filter could be more clearer

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#453]
**Describe the bug**
There is a Filter feature available in various sections in the Global report. 
I was not initially unable to know how to use it as there were no options available for user. 
So it can be confusing and the user may end up not even using it.

**To Reproduce**
1. Go to Global reports page

**Expected behavior**
I think the user should be able to find way to use it, as they can't just do hit and trial to make it work. 
So we should try to make it more user friendly.

**Screenshots**
![image](https://user-images.githubusercontent.com/87076033/235347303-194a45e5-b0df-4ab3-b58c-47b35670c345.png)

**Comment by kkartik07** [comment]
@romain-fontugne @Aniket762 Please review this and it's need and assign me if required.
Others can also give their opinions.

Thank you!

**Comment by romain-fontugne** [comment]
yes, I guess we can make it more user friendly. What do you suggest to improve this?

**Comment by noobCoderVP** [comment]
Yes, we can provide filter for each field. May I work on this issue?
