### ISSUE TITLE
Miigrate the IHR Website into Vite.js

### ISSUE THREAD

**Issue by ConnectBhawna** [InternetHealthReport/ihr-website#466]
**Describe the solution you'd like**
Vite.js is a build tool and development server that is designed to optimize the performance of Vue.js applications. It achieves this by leveraging modern web technologies such as ES modules and dynamic imports, which allow for faster loading times and better performance.
Migrating an existing Vue.js project i.e, IHR Website to Vite.js can provide several benefits, including:
-  Faster development and build times: Vite.js's development server is designed to be fast and efficient, which can significantly reduce the time it takes to develop and build a Vue.js application.
-  Improved performance: Vite.js uses advanced optimization techniques to improve the performance of Vue.js applications, which can result in faster load times and a smoother user experience.
-  Better tooling: Vite.js provides better tooling for Vue.js applications, including hot module replacement, which allows for real-time updates to the application without needing to refresh the page.
-  Easier maintenance: Vite.js's modular architecture makes it easier to maintain and update Vue.js applications over time.

Overall, migrating your project to Vite.js can provide significant benefits for your application's performance and development workflow, making it a worthwhile investment for many developers.

**Additional context**
Let us know Contributors and Maintainers about this idea.

**Comment by romain-fontugne** [comment]
I'm not sure I want to refactor the whole repository now (too much work already going on.. :( )
But related to that we'll surely have to update the code to vue.js 3

**Comment by ConnectBhawna** [comment]
Okk surely sir, means Can I work on updating the codebase to Vue.js 3 ??

**Comment by romain-fontugne** [comment]
yes, but let's create a separate issue for it

**Comment by aabhas-sao** [comment]
module bundler which supports modern features like dynamic imports can help in importing observable notebooks easily.
