### ISSUE TITLE
Feature: Optimize IHR Alarm World Map API Calls

### ISSUE THREAD

**Issue by mhmdawnallah** [InternetHealthReport/ihr-website#467]
**Is your feature request related to a problem? Please describe.**
Currently, redundant HTTP requests are being made to retrieve the Aggregated IHR alarm data for the World Map. This process can be optimized by implementing a mechanism to pass the data between components. By doing so, we can significantly reduce latency, increase throughput, and prevent overwhelming the IHR webserver when dealing with a large number of alarm data.

**Branch**: `alarm-corr-aggr`

**How to observe the problem**
1. Access the system and navigate to the alarms module.
2. Observe the process of retrieving the IHR alarm data.
3. Notice the redundant HTTP requests being made.

**Expected Behavior**
The system should pass the data between components instead of making redundant HTTP requests, resulting in decreased latency, increased throughput, and avoidance of overwhelming the IHR webserver.

**Comment by romain-fontugne** [comment]
Thanks, that's definitely needed, not only for the world map, but also to enhance data usage between components.
