### ISSUE TITLE
Update the code to vue.js 3

### ISSUE THREAD

**Issue by ConnectBhawna** [InternetHealthReport/ihr-website#469]
**Is your feature request related to a problem? Please describe.**
Updating a codebase to Vue.js 3 can bring several benefits and improvements over previous versions. Here are some reasons why you might consider updating your codebase to Vue.js 3
- Composition API: Vue.js 3 introduces the Composition API, which provides a more flexible and powerful way to organize and reuse code logic
- Better TypeScript support: Vue.js 3 has improved support for TypeScript, making it easier to write type-safe Vue applications. 
- Smaller bundle size: Vue.js 3 introduces a new, optimized rendering core called "Vue 3 runtime," which is smaller in size compared to the previous version. 
- Performance improvements: Vue.js 3 brings various performance enhancements, including a new rendering algorithm called "Fast Refresh," which improves reactivity and reduces the number of unnecessary re-renders. 
- Scalability and maintainability: With the Composition API and improved TypeScript support, Vue.js 3 allows for better code organization and modularity, making it easier to scale and maintain large codebases. 

**Describe the solution you'd like**
For converting the codebase to Vue.js 3 . I follow the certain steps.
- Read the official migration guide provided by Vue.js, which outlines the breaking changes and provides instructions for updating your codebase.
- Update Dependencies: Check if any of your project dependencies have updates available for Vue.js 3 compatibility. 
- Update Vue.js Components - updating the vue.js different components to Vue.js 3
- Update Router and Store: If you're using Vue Router or Vuex in your project, ensure that you're using the Vue.js 3 compatible versions of these libraries. 
- Testing: Update your tests to use the Vue.js 3 compatible testing utilities and adapt them to any changes in the Vue.js API.
- Run and Test: After making the necessary code changes, run your application and thoroughly test its functionality to ensure everything is working as expected.
- Documentation and Resources: Update your project's documentation to reflect the changes introduced by Vue.js 3. 

**Additional context**
Romain sir can you assign this issue to me, i would like to work on this issue.
Thanks

**Comment by romain-fontugne** [comment]
Thanks, that sounds like quite a lot of work. Now that GSoC as started the code will be changing at different places. Do you think it would be better to do the migration after the summer?

**Comment by ConnectBhawna** [comment]
Sure sir, will work on this after Summers.
Till than i am working on dashboard one

**Comment by sarkartanmay393** [comment]
@ConnectBhawna @romain-fontugne I would like to raise a PR for it. And I want to if this issue is under any programme like Gsoc?

**Comment by romain-fontugne** [comment]
if @ConnectBhawna is not working on it, then you can work on this. There is currently not in any program but we may add it to the list of ideas for the next gsoc

**Comment by ConnectBhawna** [comment]
Hii @romain-fontugne sir, you told me that start working on this once the GSOC projects PR got merged.

I think now we can start working on this issue. Let me know if that works

**Comment by romain-fontugne** [comment]
ah yeah :D Let's wait a bit more then, we still have some code to merge. That said I'm not very familiar with vue.js 3, it would be good to start discussing the main changes that will happen and what will be the main difficulties

**Comment by ConnectBhawna** [comment]
Okk sure @romain-fontugne sir 👍✨

**Comment by romain-fontugne** [comment]
Sorry for the change of plan, but we have a new (full-time) maintainer for the website, and this migration is a good chance for him to go over the whole website. Sorry again but this will be done by @dpgiakatos

**Comment by romain-fontugne** [comment]
We'll create new issues after the migration, stay tuned!

**Comment by romain-fontugne** [comment]
closed by #669
