### ISSUE TITLE
Proposal to make the web UI responsive 

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#47]
Currently, the website breaks in mobile view and there are accessibility issues with the change of device size. As discussed with @romain-fontugne sir, regarding the UI change I was talking about, I would work on the responsive after that is discussed properly and we arrive at a conclusion.

It would be great if @romain-fontugne sir can assign this issue to me and I can plan on the UI revamp or fix some of the points which can increase the accessibility.

**Comment by nimishmedatwal** [comment]
I can contribute in this issue

**Comment by romain-fontugne** [comment]
addressed by #225
