### ISSUE TITLE
Bug/No IHR Logo in Network Disconnections WorldMap

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#517]
**Problem Description:**
There is no IHR alarm logo that appears at the top right of the Network Disconnections World Map that lacks the credibility and recognition of the source if taken an image of the Data Visualization.

**Solution Description:**
It is mostly related to a margin/offset issue. Please look at the Covid19 data visualizations where the IHR log appears at the top right.

**Screenshots:**
![no-ihr-logo-network-disconnections-world-map](https://github.com/InternetHealthReport/ihr-website/assets/69568555/e7ca9528-2950-46e0-ad1a-1f4bc50e4c87)

![ihr-logo-covid19-data-visualizations](https://github.com/InternetHealthReport/ihr-website/assets/69568555/5b48f3e8-6309-4ed9-9e99-bb42d0ee9fbf)

**Comment by niladrix719** [comment]
can i work on this?

**Comment by mohamedawnallah** [comment]
Go for it @niladrix719!

**Comment by ayushgourav214** [comment]
Hey @mohamedawnallah could you please help me to find the exact file to contribute

**Comment by mohamedawnallah** [comment]
Hey @niladrix719, are you still working on this? If not, please let me know so that others can jump in. Thanks!

**Comment by niladrix719** [comment]
@mohamedawnallah yeah please consider assigning others, i am really sorry i get not get time to finish it

**Comment by mohamedawnallah** [comment]
Anyone is welcome to submit a pull request for this issue

**Comment by mohamedawnallah** [comment]
@ayushgourav214 You could use chrome dev tools (or any browser debugger) to inspect where the file for this Network Disconnection Map is located.

**Comment by Prithvi101** [comment]
hi can i get this issue assigned to me

**Comment by mohamedawnallah** [comment]
Thanks, @Prithvi101 for your interest. @SurajitCh10 already submitted a merged pull request for this issue however there are many good firsts issues in the ihr you're welcome to submit PR(s) for them.
