### ISSUE TITLE
Hyperlinking organisations branding

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#52]
In the special thanks section, I guess it would be good if we can hyperlink the branding logos with links to the corresponding websites.

<img width="1281" alt="Screenshot 2022-03-17 at 2 20 42 PM" src="https://user-images.githubusercontent.com/67703407/158772319-fcf12676-6706-4b92-bd22-5b5e7c47ae03.png">

@romain-fontugne sir, let me know if you want me to add this or there are some reasons due to which we should not hyperlink. The reason I personally feel hyperlinking will be beneficial becomes, while understanding IHR I searched about the corresponding organizations and work they do which was enhanced by understanding. 

If you want the corresponding do assign me I will raise a PR immediately!

**Comment by romain-fontugne** [comment]
I'd prefer to link these logos to the acknowledgment section of the documentation (https://ihr.iijlab.net/ihr/en-us/documentation#Acknowledgements). So the user can read about the relation between IHR and these organizations (and there is hyperlinks to each organization in the ack section).

does it make sense?

**Comment by Aniket762** [comment]
@romain-fontugne sir, you are right, it looks better that way, and as it is already done I am closing this issue!
