### ISSUE TITLE
Feature/Ioda Alarms Integration

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#537]
## Issue Description

We are in the process of integrating new alarm types from Ioda into our system to enhance our monitoring capabilities. This GitHub issue outlines the details of the alarm types, their data sources, and the objectives of the integration.

### BGP (bgp)

- Data is obtained by processing updates from Route Views and RIPE RIS collectors.
- Calculation of the number of full-feed peers observing each prefix occurs every 5 minutes.
- Visibility criteria: A prefix is visible if more than 50% of full-feed peers observe it.
- Aggregation: Prefix visibility statistics are aggregated by country, region, and ASN.

### Active Probing (ping-slash24)

- Custom implementation of the Trinocular technique.
- Regular probing of ~4.2 million /24 blocks at least once every 10 minutes.
- Alerting system currently uses data from a team of 20 probers at SDSC.
- Trinocular technique categorizes /24 blocks as up, down, or unknown.
- Aggregation: Up /24 blocks are aggregated into statistics by country, region, and ASN.
- Note: Alerts from distributed probers on the Ark platform are forthcoming.

### Network Telescope (ucsd-nt and merit-nt)

- Analysis of traffic data from UCSD and Merit Network Telescopes.
- Alerts currently generated using Merit Telescope data.
- Application of anti-spoofing heuristics and noise reduction filters.
- Geolocation and ASN lookups performed on source IP addresses.
- Computation of unique source IPs per minute.
- Aggregation: Statistics are aggregated by country, region, and ASN.

## Integration Objectives

The primary objective of this GitHub issue is to seamlessly integrate the alarm data from Ioda into our existing alert generation system. This integration will provide enhanced insights into network behavior and anomalies, contributing to a more comprehensive monitoring solution.

**Comment by romain-fontugne** [comment]
done in #538
