### ISSUE TITLE
Feature/Time Slicing on the Time Series

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#539]
## Issue Description
In the realm of time series data analysis, it is crucial to be able to identify and analyze spikes or sudden anomalies in the data. This issue proposes the implementation of a Time Slicing functionality tailored specifically for spike detection within time series data. This enhancement would empower users to efficiently capture and analyze data segments containing spikes, aiding in anomaly detection, root cause analysis, and data-driven decision-making.

**Comment by romain-fontugne** [comment]
done in #540
