### ISSUE TITLE
Feature/Filter Alarms By Severities

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#541]
### Background:
The current alarm management system lacks a crucial functionality that allows users to filter alarms based on their severity. This feature is essential for efficient incident response, as it enables users to focus on critical alarms and prioritize their actions accordingly. Additionally, the severity mapping of alarms can vary depending on the source of the alarm, further complicating the implementation of this feature.

### Problem:
Currently, users are presented with alarms on Data Visualizations without the ability to differentiate their severity levels at a glance. This results in inefficiencies in incident handling, as critical alarms might get lost in the noise of lower-priority ones. The absence of a severity filter also hampers users in conducting targeted analysis during post-incident reviews.

### Proposal:
This issue aims to introduce a feature that allows users to filter alarms based on their severities: low, medium, and high. However, the severity levels assigned to alarms can differ based on the source or origin of the alarm type.

**Comment by romain-fontugne** [comment]
done in #542
