### ISSUE TITLE
Feature/Document how to add Data Source in the Alarms Correlation and Aggregated Reports Project

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#545]
## Issue Description:
Currently, the Alarms Correlation and Aggregated Reports project lacks comprehensive documentation regarding the procedure for integrating new data sources into the system. This absence of clear instructions makes it challenging for developers and users to seamlessly incorporate additional data sources to enhance the project's capabilities.

This issue aims to address this documentation gap by creating a detailed guide on how to add new data sources to the Alarms Correlation and Aggregated Reports project. The guide should encompass step-by-step instructions, best practices, and relevant code snippets where applicable. By doing so, developers, both new and experienced, will be able to contribute more efficiently to the project and expand its compatibility with a wider range of data sources.

The documentation should cover key aspects such as data source configuration, data retrieval methods, required data formatting, and any necessary adjustments to the existing system architecture. This will not only empower current contributors but also encourage new contributors to participate by simplifying the onboarding process and fostering collaboration within the project's community.

Addressing this issue will lead to a more robust and adaptable Alarms Correlation and Aggregated Reports project, capable of ingesting diverse data sources and providing valuable insights through its correlation and reporting functionalities.

**Comment by romain-fontugne** [comment]
done in #546
