### ISSUE TITLE
Highlight current section in documentation 

### ISSUE THREAD

**Issue by Aniket762** [InternetHealthReport/ihr-website#55]
Currently, I am reading the AS dependency section in the document but it doesn't highlight the link in the left section. I propose to add a link in the left half so that readers understand what are they reading currently.
<img width="1440" alt="Screenshot 2022-03-20 at 1 56 41 PM" src="https://user-images.githubusercontent.com/67703407/159154277-bacda8a8-cf32-4edd-8d74-8f6441dfcdb9.png">

@romain-fontugne sir, this is just a minor UI fix, I am thus sending the PR, incase you don't want it just close the issue and the corresponding PR

**Comment by romain-fontugne** [comment]
Yes, that would be great

**Comment by thisiskaransgit** [comment]
Can I work on this issue ?

**Comment by thisiskaransgit** [comment]
hey @Aniket762  can I work on this issue ?

**Comment by Aniket762** [comment]
> hey @Aniket762 can I work on this issue ?

Sure thing @thisiskaransgit assigning this to you right away :)

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 , I have solved the issue, kindly check the following screenshots.

1.  **Selected Acknowledgments Section** 
![Screenshot from 2022-05-29 15-27-00](https://user-images.githubusercontent.com/92504666/170863653-5750ae43-e2fa-42d4-9133-fda975dd5ec0.png)


2. **Selected Country Report Section**
![Screenshot from 2022-05-29 15-26-52](https://user-images.githubusercontent.com/92504666/170863657-5d039aa2-0c1a-49d2-9c08-f9d9ccfa9a6e.png)

Waiting for the approval to send the PR :smile:

**Comment by Aniket762** [comment]
Hey, @thisiskaransgit great work. The highlight looks great and suffices the need. Can you change the style of highlighting a bit? A red underline is enough and would increase the UI/UX for sure.

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 , Does this looks good ?
1.  
![Screenshot from 2022-05-29 18-13-54](https://user-images.githubusercontent.com/92504666/170869156-e1109aa9-9457-4d43-8be2-0d5eabe6e799.png)
2.
![Screenshot from 2022-05-29 18-12-43](https://user-images.githubusercontent.com/92504666/170869184-d59843e7-cf4e-4193-843a-eef5752c730d.png)

**Comment by Aniket762** [comment]
> Hey @Aniket762 , Does this looks good ? 1. ![Screenshot from 2022-05-29 18-13-54](https://user-images.githubusercontent.com/92504666/170869156-e1109aa9-9457-4d43-8be2-0d5eabe6e799.png) 2. ![Screenshot from 2022-05-29 18-12-43](https://user-images.githubusercontent.com/92504666/170869184-d59843e7-cf4e-4193-843a-eef5752c730d.png)

Yes absolutely

**Comment by Aniket762** [comment]
Closing this issue as of now, if some bug occurs will reopen :)
