### ISSUE TITLE
Reset time button breaks all filters

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#557]
**Describe the bug**
In the new alarms agg/corr dashboard when I click on the 'Reset time' button it seems to break all other filters. After clicking that button selecting a country on the world map doesn't work anymore (instead an error is thrown in the console).

**To Reproduce**

1. Using the `alarm-corr-aggr` branch.
2. Go to 'Global Report'
3. Select a time span on the timeline plot.
4. Click the 'Reset time' button
5. Click on any country on the world map
6. See the error in the console

**Expected behavior**
I expect it should filter alarms based on the country selected in step 5.

**Desktop (please complete the following information):**

- OS: linux
- Browser: Firefox

**Comment by mohamedawnallah** [comment]
Thanks for catching this bug I've made a PR that solves it :)

**Comment by romain-fontugne** [comment]
Thanks for the quick fix!
