### ISSUE TITLE
Home page banner click should not redirect to "Global report" page.

### ISSUE THREAD

**Issue by akib22** [InternetHealthReport/ihr-website#56]
On the home page, click on the banner it will redirect to **Global report page**.

**To Reproduce**

1. Go to the **Home page**.
2. Click on the banner

**Expected behavior**
Should not redirect to **Global Report page** when clicking on the banner.

@romain-fontugne, I am working on this issue and soon raise a pull request.

**Comment by Aniket762** [comment]
Closing the issue as  it was resolved via #57
