### ISSUE TITLE
Set Up Pre-commit Git Hook for Selective Linting

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#562]
**Problem**
Maintaining a healthy codebase requires consistent code quality. We aim to establish an automated code linting process using ESLint and GitHub Actions.

**Context**
Presently, we possess a [GitHub Actions workflow](https://github.com/InternetHealthReport/ihr-website/blob/master/.github/workflows/eslint.yml) for linting. However, it lacks automation as it identifies code linting issues without automatically fixing them.

**Solution**
I would suggest using a pre-commit git hook for linting instead of a GitHub Action so it is the responsibility of the developer to fix the lining issues. Please check [lint-staged](https://www.npmjs.com/package/lint-staged) npm package for selective linting and integrating it with [husky](https://www.npmjs.com/package/husky) npm package for managing git-hooks

**Comment by 0xAnon0602** [comment]
Hey can I work on this ?

**Comment by mohamedawnallah** [comment]
I would suggest using a pre-commit git hook for linting instead of a GitHub Action please check [lint-staged](https://www.npmjs.com/package/lint-staged) npm package for selecting linting and integrating it with [husky](https://www.npmjs.com/package/husky) npm package for managing git-hooks

**Comment by 0xAnon0602** [comment]
Thanks for pointing me in right direction 
Will add lint-staged integrated with husky
