### ISSUE TITLE
Hover effect on website

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#593]
On hovering over the Reports and Tools on the navbar the dropdown menu doesn't appear.
It only appears when someone clicks on it.

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/8453cf49-b277-4d26-938a-dd90ff74a902)

**Comment by romain-fontugne** [comment]
sure, go for it

**Comment by divyansh2375** [comment]
can i work on this issue @romain-fontugne ?

**Comment by divyansh2375** [comment]
Alright @0xAnon0602  . I actually asked because there was not any response coming here since 1 week

**Comment by romain-fontugne** [comment]
fixed in #598
