### ISSUE TITLE
Bug/ASInterdependenciesChart.vue component Doesn't Handle All Data Points

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#632]
**Describe the bug**
The `ASInterdependenciesChart.vue` component fails to handle a specific scenario where all data points retrieved from the Hegemony endpoint have the `originasn` equal to the `asn`. This results in a crash when viewing the AS Dependencies Chart. The bug report includes information on how to reproduce the issue and provides links to relevant URLs for further investigation.

**To Reproduce**
Please check the AS Dependencies Chart the following url you find it crashes:
https://ihr.iijlab.net/ihr/en-us/networks/AS6939?af=4&last=1&date=2023-10-20

For deeper research please check the Hegemony API endpoint response for this AS you will find all `originasn` and `asn` are equal:
https://ihr.iijlab.net/ihr/api/hegemony/?format=json&originasn=6939&af=4&ordering=timebin

**Expected behavior**
It shouldn’t crash at least showing for the user there is no data to show

**Screenshots**
<img width="1305" alt="Screenshot 2023-11-03 at 9 43 53 PM" src="https://github.com/InternetHealthReport/ihr-website/assets/69568555/c14f081a-c4d6-4729-9939-ec1f32a7affd">

**Comment by romain-fontugne** [comment]
thanks! Indeed I think the last version of the code is quite buggy

**Comment by MAVRICK-1** [comment]
can you assign me this one?

**Comment by mohamedawnallah** [comment]
Hey @MAVRICK-1 Thanks for your interest to contribute to IHR. For this issue I've already addressed it in the attached PR. Please keep an eye on the issues in our repository!

**Comment by MAVRICK-1** [comment]
@mohamedawnallah  do you guys have any online community on discord or slack where we can discuss about bug , issue or enhancement ?

**Comment by mohamedawnallah** [comment]
You could [join our Slack Channel](https://join.slack.com/t/internethealthreport/shared_invite/zt-19d4e48py-~oirVwkINe01gTVEF3o4Kw). Also if you wanna discuss about an issue or enhancement it is better to use [our GitHub Discussions](https://github.com/orgs/InternetHealthReport/discussions) or you could open a GitHub Issue and discuss it there.
