### ISSUE TITLE
Bug/ASInterdependenciesChart.vue component gives null pointer exception on getTime()

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#633]
**Describe the bug**
The `ASInterdependenciesChart.vue` gives null pointer exception for accessing getTime on an assumed date object.

**To Reproduce**
Please check the AS Dependencies Chart the following url you find it gives null pointer exception in the console:
https://ihr.iijlab.net/ihr/en-us/networks/AS267350?af=4&last=1&date=2023-10-06&rov_tb=routes

**Expected behavior**
It should handle the null pointer exception

**Screenshots**
<img width="1371" alt="Screenshot 2023-11-03 at 9 51 42 PM" src="https://github.com/InternetHealthReport/ihr-website/assets/69568555/a5e87405-856f-4094-84ed-106754ffca92">

**Comment by kamal9494** [comment]
Hey, can I work on this issue?

**Comment by mohamedawnallah** [comment]
Hey @kamal9494 Thanks for your interest to contribute to IHR. For this issue I've already addressed it in the attached PR. Please keep an eye on the issues in our repository!
