### ISSUE TITLE
Mobile view 

### ISSUE THREAD

**Issue by khadar1020** [InternetHealthReport/ihr-website#635]
**Describe the bug**
Open in Mobile, In the Network Delay chart the source and destination inputs coincide with the cross and search button it will be clear in the screenshot that I have provided the user may face a problem if he wants to enter the data for the second time he will not be able to press on the cross button 

**To Reproduce**

1. Go to 'network delay chart'
2. Click on 'source and destination search boxes and enter values'
3. See error

**Expected behavior**
We can make them responsive by using CSS properties

**Screenshots**
![Screenshot (835)](https://github.com/InternetHealthReport/ihr-website/assets/124120102/387aed4f-bde3-44b3-a4b2-9fb0ae7a6a5b)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]
- Version [119.0.6045.160 ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khadar1020** [comment]
I would like to work on this issue @romain-fontugne if you like the change please assign me this issue

**Comment by romain-fontugne** [comment]
thanks, go for it!

**Comment by Harshalvk** [comment]
I would like to work on this issue..
