### ISSUE TITLE
Display last fetched data for AS Dependency when network is unreachable

### ISSUE THREAD

**Issue by JanviSinha2001** [InternetHealthReport/ihr-website#636]
**Describe the problem statement**
In the AS Dependency page, when transit network data is not available, the current behavior displays a "network is unreachable" message. The absence of data disrupts the user experience and the ability to gain insights into historical trends.

**Describe the solution you'd like**
Instead of presenting a generic error message, the graph can display the last successfully retrieved data. This will ensure uninterrupted visualization of network dependencies, offering users continuous insights even in the absence of real-time updates. The graph can also display the date and time of the last available data for added clarity.

Screenshot of the issue: 
![image](https://github.com/InternetHealthReport/ihr-website/assets/108648050/4f993e0e-4b41-422f-9b2f-3b15a5560b75)

**Additional context**
Maintainers can kindly let me know their thoughts on the same.

**Comment by romain-fontugne** [comment]
I think it may be misleading for the user to change automatically dates. The user may be interested in what happened at that particular time. But you are right we could also give a away for the user to get the latest results. Maybe we could change the message to something like 'Network is unreachable. Last seen on xxx/xx/xx'. 
But actually our API is not really designed for that we'd have to iterate to all past dates

**Comment by JanviSinha2001** [comment]
Yes, that makes more sense. Will get started on that @romain-fontugne
