### ISSUE TITLE
Overlapping icons and logos

### ISSUE THREAD

**Issue by JanviSinha2001** [InternetHealthReport/ihr-website#637]
**Describe the bug**
The logos and icons are overlapping on the home page and the global report graph for alarms when viewing data for multiple countries.

**To Reproduce**

1. Navigate to the 'Global Report' section.
2. Click on the "Alarms for all countries over Time" section.
3. Observe the logos in the graph overlapping.

Similar behavior can be observed in the "Special thanks to" section of the home page.

**Expected behavior**
For a clearer and better UI, we can utilize CSS positioning or grid systems to ensure proper spacing and a non-overlapping display of logos and icons.

**Screenshots**
![image](https://github.com/InternetHealthReport/ihr-website/assets/108648050/82ee8cb8-42db-4501-8696-e35c6c8f6f01)

![image](https://github.com/InternetHealthReport/ihr-website/assets/108648050/a27b5c21-c05e-4ddf-bc65-1a342ae36e91)

**Comment by romain-fontugne** [comment]
We have a significant PR for the Global Report, so I think it is better not to touch anything there right now. But yes, the logos in the special thanks should be fixed. Feel free to work on this

**Comment by JanviSinha2001** [comment]
Okay, noted @romain-fontugne
