### ISSUE TITLE
Links position is uneven at homepage

### ISSUE THREAD

**Issue by khadar1020** [InternetHealthReport/ihr-website#640]
This issue was already assigned to me by @romain-fontugne sir yesterday here - https://github.com/InternetHealthReport/gsoc/issues/10

That is why I did not follow the template

![230756995-43e8a029-8356-4803-a995-b86460d10111](https://github.com/InternetHealthReport/ihr-website/assets/124120102/3b42535b-9a62-4901-a2cb-041074fcc8a6)

**Comment by ApoorvDubey23** [comment]
can I work on this issue if not resolved???

**Comment by khadar1020** [comment]
This issue is solved @ApoorvDubey23 and the PR is waiting for a review
