### ISSUE TITLE
Enhancement/NavigationDuplicated: Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#645]
**Describe the bug**
Currently navigation route is duplicated because of “redundantly” replacing the same route with the same parameters

**To Reproduce**
[This is only one example]
1. Go to [Network Report Page](https://ihr.iijlab.net/ihr/en-us/networks?af=4&last=3&date=2023-11-30)
2. Check the errors in the console
3. You’ll find a typical one as seen in the attached screenshot

**The code files where this issue needs to be addressed**
1. [Networks Component](https://github.com/InternetHealthReport/ihr-website/blob/f694d4baef18d385b8ff6eda32d94a3084068a18/src/views/Networks.vue#L286-L295)
2. [ROV Component](https://github.com/InternetHealthReport/ihr-website/blob/f694d4baef18d385b8ff6eda32d94a3084068a18/src/views/ROV.vue#L64-L75)
3. [Countries Component](https://github.com/InternetHealthReport/ihr-website/blob/f694d4baef18d385b8ff6eda32d94a3084068a18/src/views/Countries.vue#L201-L212)

**Expected behavior**
We shouldn’t “redundantly” replace the same route with the same parameters

**Screenshots**
<img width="478" alt="Screenshot 2023-11-30 at 10 00 58 PM" src="https://github.com/InternetHealthReport/ihr-website/assets/69568555/324e220c-410d-454d-806f-87807a865cc0">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome

**Additional context**
I’ve addressed the same issue in the Global Report Page. You could check this [pushRoute function in GlobalReport.vue](https://github.com/InternetHealthReport/ihr-website/blob/f694d4baef18d385b8ff6eda32d94a3084068a18/src/views/GlobalReport.vue#L74-L84) so in order to address this issue you need to do the following:
1) Add defensive checks for existing and the new parameters if any new replace the route.
2) Make sure to correctly address data types conversion and equivalence.

**Comment by khadar1020** [comment]
do you want on this issue or can I work on this issue @mohamedawnallah 
thank you

**Comment by mohamedawnallah** [comment]
Thanks for your interest @khadar1020! Fee free to submit PR for this

**Comment by Nishannb** [comment]
@mohamedawnallah I have submitted the PR solving this issue. Can you please review my PR #662 .

**Comment by khadar1020** [comment]
follow the guidelines @Nishannb from next time please let other people know you are working on this issue @mohamedawnallah 
you can review his PR It is waste of time others 
Thank you

**Comment by mohamedawnallah** [comment]
Hey @khadar1020 no one was explicitly assigned to this issue otherwise it is First Come First Serve and @Nishannb submitted the PR first. Thanks for your understanding!
![2023-12-07_08-43](https://github.com/InternetHealthReport/ihr-website/assets/69568555/6ae43c44-e19f-41bf-9b54-8e0d189cd51d)

**Comment by Simun-12** [comment]
The issue is still open.. Is it fixed or I can take up? @mohamedawnallah
