### ISSUE TITLE
Network Dependency,Route Origin Validation and Network Delay tables are not properly visible in mobile devices.

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#660]
**Screenshots**
![Screenshot_2023-12-02-02-47-33-317_com.android.chrome.jpg](https://github.com/InternetHealthReport/ihr-website/assets/146999057/e9d74369-9463-43f3-b696-8a506b175aa6)

![Screenshot_2023-12-02-02-47-28-996_com.android.chrome.jpg](https://github.com/InternetHealthReport/ihr-website/assets/146999057/67e0f2b4-c8c8-4d5a-ac15-3f71d431e76a)

![Screenshot_2023-12-02-02-47-37-322_com.android.chrome.jpg](https://github.com/InternetHealthReport/ihr-website/assets/146999057/3ba76d27-4298-4302-a53d-f2d8086716f7)

 **Describe the bug**
Data table is not visible properly.
Need some responsive fixation.

**Expected behavior**
Data chart should fit the full screen without scrolling.

**Smartphone**

**Additional context**
Should be improve for better user experience.

**Comment by ApoorvDubey23** [comment]
HI mentor , I am new to Open Source and would like to go with this issue as I am quite comfortable with css and responsiveness , plz assign this to me

**Comment by MAVRICK-1** [comment]
@ApoorvDubey23 , Hi currently I am working on this .

**Comment by ApoorvDubey23** [comment]
yaa sure , If there is any other way I can Contribute to your organisation , do let me know

**Comment by ApoorvDubey23** [comment]
is there any community channel of IHR?

**Comment by romain-fontugne** [comment]
Thanks, @MAVRICK-1 , yes that's a problem. How are you planning to fix this? I guess a mobile screen is just too small to show the table?

**Comment by MAVRICK-1** [comment]
@romain-fontugne ,Certainly! To optimize the mobile user experience, I propose making the tables more compact while ensuring they utilize the entire mobile screen. By reducing the table size, users can view the complete dataset on a single screen, eliminating the need for horizontal scrolling. This adjustment facilitates easier data analysis and readability. Additionally, users can zoom in if they wish to examine specific details. I'm prepared to initiate these enhancements post-migration.

**Comment by romain-fontugne** [comment]
well, as the screenshot says both are not that good :D
I appreciate you willingness to help but this may end up not more useful than the current implementation

**Comment by MAVRICK-1** [comment]
@romain-fontugne  yeah 💀,  i totally missed that top of the screenshot, If I found more useful way to representing Tables ,I will let you know.

**Comment by romain-fontugne** [comment]
well, actually Quasar documentation has something about responsive tables:
https://quasar.dev/vue-components/table/#responsive-tables

you can try that, let's us know if it improves anything

**Comment by MAVRICK-1** [comment]
> well, actually Quasar documentation has something about responsive tables:
> https://quasar.dev/vue-components/table/#responsive-tables
> 
> you can try that, let's us know if it improves anything

Sure 😊
