### ISSUE TITLE
[UI]Bad UI when switching to Mobile view 

### ISSUE THREAD

**Issue by ApoorvDubey23** [InternetHealthReport/ihr-website#665]
**Describe the bug**
While inspecting in the Chrome Browser when switching to dimensions of Smartphone(Samsung Galaxy S8+) the content is getting messed up in the table with overflowing content and tables shrinking too much

**To Reproduce**

1. Go to IHR Home Page 
2. Click on Global Report Button
3. Switch to mobile view 
4. Will see the UI getting messed up

**Expected behavior**
Changing the alignment of the content to have a clear view of tables as well table width should be enough to  
fit the content.
**Screenshots**

[Screencast from 07-12-23 09:25:50 PM IST.webm](https://github.com/InternetHealthReport/ihr-website/assets/132251091/86e5fa6a-e30e-4eb7-9b2e-fa58f50914b3)

**Desktop (please complete the following information):**

Chrome as well as mozilla firefox

**Smartphone (please complete the following information):**
Mobile view of Samsung Galaxy S8+

**Additional context**

I would like to work on this issue , @romain-fontugne can I ?

**Comment by romain-fontugne** [comment]
well, this is a page that shows a lot of information. I wouldn't recommend anyone to go there with a mobile. Unless you have a good idea on how to improve the UI, it may be a waste of time for you to work on this?

**Comment by romain-fontugne** [comment]
sure, but still I think it defies the purpose of the global report. We'll soon add new issues @ApoorvDubey23 stay tuned!

**Comment by ApoorvDubey23** [comment]
Sure

**Comment by mohamedawnallah** [comment]
@romain-fontugne Should we close this issue?

**Comment by abdulrehmanjaved-1** [comment]
Can i work on it?. Thank you.
