### ISSUE TITLE
Old Twitter Logo

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#667]
**Describe the bug**
IHR Tweets using old twitter logo

**To Reproduce**
Go the Home page and Scroll down to IHR Tweets

**Expected behavior**
new Twitter Logo

**Screenshots**
![2023-12-14 14 15 43](https://github.com/InternetHealthReport/ihr-website/assets/146999057/f1eb24a0-55e4-4f73-91b8-9333db2f1472)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by RickDeb2004** [comment]
@MAVRICK-1 have you started working on it?

**Comment by MAVRICK-1** [comment]
> @MAVRICK-1 have you started working on it?

I have already complete the work and also created pull request which has been reviewed
