### ISSUE TITLE
Unwanted (Horizontal Scroll Bar) in COVID-19 Reports page 

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#670]
**Describe the bug**
The Toolbox in the COVID-19 Reports Page is overflowing in Small Devices. As a result Horizontal Scroll Bar appears.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/covid19'
2. Reduce the window size
4. See Unwanted (Horizontal Scroll Bar) at the bottom of the page

**Expected behavior**
By Putting the Toolbox in side the parent container the overflowing will not happen.

**Screenshots**

https://github.com/InternetHealthReport/ihr-website/assets/113178195/f8cc9e62-33de-4f6a-b435-9b4b2e36e339

**Desktop (please complete the following information):**

- OS: [windows11]
- Browser [e.g. chrome]
- Version [latest]

**Comment by ArnabBCA** [comment]
@romain-fontugne I can solve this issue can you please assign it :)

**Comment by mohamedawnallah** [comment]
I’m not sure how you would handle this
