### ISSUE TITLE
COVID-19 Reports Page is not using Full width of the page.

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#671]
**Describe the bug**
Currently the list of (Network Delays During National Lockdowns) is only utlising 50% of the width of the screen as a result lot of space is wasted.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/covid19'

**Expected behavior**
It should utilize the whole screen width 

**Screenshots
Before
![Screenshot 2023-12-14 205923](https://github.com/InternetHealthReport/ihr-website/assets/113178195/d7587d4e-69f0-43bd-8ede-c564a46a17b6)
**
After
![2](https://github.com/InternetHealthReport/ihr-website/assets/113178195/d35cb9d2-9911-4e4d-a5cb-3c5f71a1955a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I can solve it can you please assign me :)

**Comment by ArnabBCA** [comment]
@romain-fontugne I can solve this issue can you please assign it :)

**Comment by mohamedawnallah** [comment]
I’m not sure about this issue

**Comment by ArnabBCA** [comment]
> I’m not sure about this issue

Currently it is using 50% of VW which looks ok in desktop devices but in mobile devices it is still using 50% of VW which is taking a lot of space.

**Comment by ArnabBCA** [comment]
> > I’m not sure about this issue
> 
> @mohamedawnallah Currently it is using 50% of VW which looks ok in desktop devices but in mobile devices it is still using 50% of VW which is taking a lot of space.

**Comment by ArnabBCA** [comment]
![Screenshot_2023-12-15-10-13-25-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/InternetHealthReport/ihr-website/assets/113178195/6879a293-58ff-4ff4-99a1-a67f957c658f)

@mohamedawnallah as you can see in mobile devices it is not utilizing the full width. A lot of black spaces are left of both sides.

**Comment by mohamedawnallah** [comment]
Ah sounds good! Go ahead
