### ISSUE TITLE
Unwanted Horizontal Scrollbar in the Documentation page

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#672]
**Describe the bug**
The links in the Documents and Contact page is not responsive causing overflowing issue.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/documentation'
2.  Reduce the screen size.
4.  See horizontal scroll bar.

**Expected behavior**
The Links should be responsive and break according to the screen size.

Screenshot.
![3](https://github.com/InternetHealthReport/ihr-website/assets/113178195/afdfe627-5be9-4361-bd00-63abe441e26e)

**Additional context**
I can solve the issue can you please assign :)

**Comment by MAVRICK-1** [comment]
<img width="960" alt="Screenshot 2023-12-14 233815" src="https://github.com/InternetHealthReport/ihr-website/assets/146999057/c87c1ead-fab2-4902-8e7a-ba1a0c0fee07">

Where are you getting horizontal scroll bar issue ? I guess you have opened inspect  code for that it is showing.

**Comment by ArnabBCA** [comment]
@romain-fontugne I can solve this issue can you please assign it :)

**Comment by ArnabBCA** [comment]
@mohamedawnallah what about this  UI issue?

**Comment by mohamedawnallah** [comment]
Yep, that’s needed for all links to be adaptable to the screen size. Go ahead @ArnabBCA
