### ISSUE TITLE
Able to scroll when modal is open in the API page

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#673]
**Describe the bug**
After clicking the authorize button the modal is opening But the scrolling is not disabled.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/api'
2. Click on 'Authorize Button'
3. Scrolling is not disabled

**Expected behavior**
Scrolling should be disabled when the modal is opened.

**Screenshots**

https://github.com/InternetHealthReport/ihr-website/assets/113178195/b5a09b49-9be3-4bc7-83dd-739b13ad142d

**Additional context**
I can solve this issue can you please assign :)

**Comment by ArnabBCA** [comment]
@romain-fontugne I can solve this issue can you please assign it :)

**Comment by mohamedawnallah** [comment]
I’m not sure about this issue as well 😁

**Comment by ArnabBCA** [comment]
> I’m not sure about this issue as well 😁

Normally when a modal is open. The background should stop scrolling and vice versa.

**Comment by mohamedawnallah** [comment]
Maybe it is a good user experience try to implement it and we see how it goes

**Comment by romain-fontugne** [comment]
yeah, I'm not so sure about this issue too. @ArnabBCA are you working on that? if not please close the issue
