### ISSUE TITLE
UI error , not responsive 

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#674]
**Describe the bug**
UI error  , not responsive 

**To Reproduce**
Vist the pages in mobile device
(Covid19)[https://ihr.iijlab.net/ihr/en-us/covid19]
(Documentation)[https://ihr.iijlab.net/ihr/en-us/documentation]

1. Horizontal scrolling 

**Expected behavior**
Horizontal scrolling should be permitted 

**Screenshots**
https://github.com/InternetHealthReport/ihr-website/assets/146999057/9841dc94-0edf-45e0-a50c-73ae873637a0

**Smartphone (please complete the following information):**

**Additional context**
Should be resolved for proper user experience

**Comment by ArnabBCA** [comment]
Duplicate issue #671

**Comment by mohamedawnallah** [comment]
This is duplicated for issues #670 and #671

**Comment by MAVRICK-1** [comment]
@mohamedawnallah sry i didn't notice 😬.
