### ISSUE TITLE
Show "No Results Found for _____" Message for Empty Search Queries

### ISSUE THREAD

**Issue by Animesh239** [InternetHealthReport/ihr-website#676]
**Is your feature request related to a problem? Please describe.**
When users perform an empty search (i.e., entering no search query) in the search bar, the application currently does not provide any feedback or indication.

**Describe the solution you'd like**
I propose implementing a feature that displays a "No Results Found" message when users submit an empty search query. This would enhance user experience by providing immediate feedback and clarity when no search term is entered.

**Implementation:**
Consider adding a conditional statement in the search functionality to detect empty queries and display a user-friendly message.

**Comment by Animesh239** [comment]
I want to work on this issue...

**Comment by romain-fontugne** [comment]
Ok, I'm assigning you to this issue but please next time follow our guidelines and submit the PR after you've been assigned :)
