### ISSUE TITLE
Extended Search bar looks odd

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#683]
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/4f1ffb2e-8d55-4c85-8ac5-b8e3e30e185e)
here when I click on the search bar it gets extended ....shouldn't we fix the position of search bar?

**Comment by RickDeb2004** [comment]
@mohamedawnallah

**Comment by dpgiakatos** [comment]
Please reevaluate this issue in the Vue 3.js version.

**Comment by Harshalvk** [comment]
https://github.com/InternetHealthReport/ihr-website/assets/80589780/e7ae8697-2489-4885-9ecf-0f474ec44bab
On what page you are experiencing the issue?? It fine on my browser

**Comment by dpgiakatos** [comment]
According to the URL from the image he provided, he is using the Vue 2.js version. That's why I suggest reevaluating this issue in the Vue 3.js version (the current version in master, not deployed yet).
