### ISSUE TITLE
Feature Request add Dark Mode Theme Toggle

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#684]
**Is your feature request related to a problem? Please describe.**
A dark mode is a must have feature in modern applications. Because most of the people have eye strains while looking at the bright light screen including me :) . Also after implementation it will give a good user experience.

**Describe the solution you'd like**
I want to implement a Dark Mode Toggle Button where user can select theme Dark or Light (Current Theme) according to their preference.

**Describe alternatives you've considered**
I will implement dark mode at Documentation Page First and after taking feedback from the mentors i will implement in the whole website.

**Comment by ArnabBCA** [comment]
@romain-fontugne @mohamedawnallah what is your opinion about this feature?

**Comment by romain-fontugne** [comment]
that would be a nice feature to have! Yet we have to wait for the vue3 migration to start implementing that

**Comment by ArnabBCA** [comment]
> that would be a nice feature to have! Yet we have to wait for the vue3 migration to start implementing that

@romain-fontugne can i now start implementing it :)

**Comment by romain-fontugne** [comment]
sure

**Comment by dpgiakatos** [comment]
I am closing this issue as it has been inactive for a long time with no reported progress. Regarding the theme change between light/dark mode, we may revisit it after internal discussion, as it requires UI changes and palette definitions by the maintainers.
