### ISSUE TITLE
Adding breadcrumbs for navigation in documentation page for mobile users 

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#685]
Integrating breadcrumbs into the documentation page offers users a streamlined navigation experience, allowing them to effortlessly access their designated topics with a single click. This approach proves more effective compared to a vertical swipe dashboard, where issues may arise with backtracking gestures, potentially leading users to previously visited pages. Breadcrumbs enhance user efficiency by providing a clear and direct path through the documentation.

**Describe alternatives you've considered**
Making a Toggle documentation dashboard 

**Additional context**
This simple feature will enhance the user experience

**Comment by MAVRICK-1** [comment]
@romain-fontugne @mohamedawnallah what are your views on this?

**Comment by ManasMadan** [comment]
@MAVRICK-1 Can i work on this ?
