### ISSUE TITLE
Horizontal scrolling problem in Home Page

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#687]
**Describe the bug* 
Horizontal scrolling problem in the homepage 

**To Reproduce**

1. Go to  https://ihr.iijlab.net/ihr/en-us
2 Scroll horizontally 
3.See error

**Expected behavior**
No horizontal scrolling should occur .

**Screenshots**

https://github.com/InternetHealthReport/ihr-website/assets/146999057/4fd44828-b4cc-4e7e-a390-ac26ecd10dc3

**Smartphone (please complete the following information):**

**Additional context**
Assign me I can fix this

**Comment by MAVRICK-1** [comment]
@romain-fontugne  @mohamedawnallah what are your views on this?

**Comment by Shiva0krishna** [comment]
@MAVRICK-1   I have also noticed it ( In mobile  view ).  It shouldn't be happening . Assign me I can fix this .

**Comment by romain-fontugne** [comment]
Honestly the mobile view is not super important for our visitors. We don't have a lot of users on small devices. It is nice to have the basics working in the mobile view but we don't really prioritize UI improvements for mobile. Especially now as we are migrating to vue3, so this may change during the migration

**Comment by MAVRICK-1** [comment]
👍 okay got it
