### ISSUE TITLE
The Examples in the The Network and Country Page is not Centered Properly

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#688]
**Describe the bug**
The Examples in the The Network and Country Page is not Centered Properly

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/networks?af=4&last=3&date=2023-12-16
2. Go to https://ihr.iijlab.net/ihr/en-us/countries?af=4&last=3&date=2023-12-16

**Expected behavior**
The Examples must be Centered Properly

**Screenshots**
![Exmple 2](https://github.com/InternetHealthReport/ihr-website/assets/113178195/6560b4fa-f4e3-4ec8-936b-70fc4726ff3a)
![Example 3](https://github.com/InternetHealthReport/ihr-website/assets/113178195/7d67eb3a-6121-4489-8735-486962682deb)

**Comment by ArnabBCA** [comment]
@mohamedawnallah can you assign me :)

**Comment by romain-fontugne** [comment]
Ok that need to be fixed, please go ahead
