### ISSUE TITLE
horizontal scrolling in reference on IHR in API page

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#689]
**Describe the bug**
Horizontal scrolling occuring in reference on IHR

**To  Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/api
2. Click on  any one of referenced on IHR.
3. Scroll scroll horizontally 

**Expected behavior**
No horizontal scrolling 

**Screen Recording**

https://github.com/InternetHealthReport/ihr-website/assets/146999057/f9147e89-a336-4768-b823-bc7e55e42419

**Smartphone (please complete the following information):**

**Additional context**
Assign me I can solve it

**Comment by romain-fontugne** [comment]
is this still the case in the upcoming vue3 version?

**Comment by horizenight** [comment]
Yes, this error is still there tested it on the smartphone. 
Device: [ Oneplus 7]

**Comment by MAVRICK-1** [comment]
> is this still the case in the upcoming vue3 version?

It is occurring only in mobile device but it works well in desktop devices

**Comment by romain-fontugne** [comment]
Then let skip this, sorry but most of our tools are not really designed for mobiles
