### ISSUE TITLE
Horizontal scrolling occur Mentis Atlas probe selection 

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#690]
**Describe the bug**

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/metis/selection
2. Select the desired Atlas probs , distance metric and Ip version 
3. Click on Go
4. Scroll down
5. See error

**Expected behavior**
Text wrap for Data source link

**Screenshots**

![Screenshot_2023-12-16-12-10-14-305_com android chrome](https://github.com/InternetHealthReport/ihr-website/assets/146999057/5647406e-e84c-4b58-92ea-6ee0637959a0)

**Video**

https://github.com/InternetHealthReport/ihr-website/assets/146999057/60dd5427-f68c-48ba-91a6-1734e9e297b7

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign me I can solve this

**Comment by Shiva0krishna** [comment]
@MAVRICK-1 .  Assign me I can solve this.

**Comment by romain-fontugne** [comment]
I'm not sure this is still the case in the coming vue3 version?

**Comment by romain-fontugne** [comment]
I'll close this, because it seems to be related to Metis mobile view (there is actually no detailed description of the issue..?) and Metis is not intended to be viewed on mobile
