### ISSUE TITLE
Data selection option in Atlast probe selections  should be more wider and responsive

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/ihr-website#691]
**Describe the bug**
Metis:Atlas probe selection probes selection table is not responsive 

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/metis/selection
2. Scroll down to Number of probes Distance metric selector tabel
3. See error

**Expected behavior**
Data selector should be more responsive for better user experience 

**Screenshots**
![Screenshot_2023-12-16-11-55-17-100_com android chrome](https://github.com/InternetHealthReport/ihr-website/assets/146999057/72a3cbd1-ec3d-4e50-b1d8-3198c8a75dc7)

**Smartphone (please complete the following information):**

**Additional context**
I can solve this

**Comment by ApoorvDubey23** [comment]
I would like to work on this , can you please assign this to me plz

**Comment by romain-fontugne** [comment]
I don't think this is really needed, the metis pages are target for developers using Atlas. I cannot imagine someone coding/preparing an Altas measurement on a phone :D
