### ISSUE TITLE
UI of covid-19 reports should be responsive 

### ISSUE THREAD

**Issue by ApoorvDubey23** [InternetHealthReport/ihr-website#692]
**Describe the bug**
When switching to mobile view , the UI of covid-19 reports must be made responsive as the Toolbox-add more destination networks is going out of the screen messing up the responsiveness, also the content padding should be reduced to make it look better

**To Reproduce**

1. Go to HomePage
2. Click on 'Reports-covid-19
3.Switch to mobile view

**Expected behavior**
less padding to make content look wider and toolbox should be placed relatively

**Screenshots**

[Screencast from 17-12-23 12:02:49 PM IST.webm](https://github.com/InternetHealthReport/ihr-website/assets/132251091/859b9ea5-829f-4994-9a6d-bb090ad3efca)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Samsung Galaxy S8+
- Chrome

**Additional context**
I would like to take on this issue

**Comment by ArnabBCA** [comment]
Duplicate issue #671 I am already assigned brother

**Comment by ApoorvDubey23** [comment]
Okay I am closing the issue then

**Comment by ApoorvDubey23** [comment]
also I need a help , while trying to commit my work I am getting this error :
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
file:///home/apoorv/ihr-website/node_modules/lint-staged/bin/lint-staged.js:21
const packageJson = JSON.parse(await fs.readFile(new URL('../package.json', import.meta.url)))
                               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
husky - pre-commit hook exited with code 1 (error)


any idea??

**Comment by MAVRICK-1** [comment]
It seems there's a syntax error in the `lint-staged.js` file around line 21. The error indicates that the parser encountered an unexpected reserved word (`const`) at that position. Review the code in `lint-staged.js` and ensure correct usage of `const` or any other syntax around that line. Additionally, make sure your Node.js version supports ECMAScript modules (ESM).

**Comment by romain-fontugne** [comment]
I'm closing this, please open a different issue if you have a different problem
