### ISSUE TITLE
Disappearing navigation panel on the documentation page

### ISSUE THREAD

**Issue by JanviSinha2001** [InternetHealthReport/ihr-website#699]
**Describe the bug**
The scroll/navigation panel in the documentation page of the website seems to disappear after popping up once on mobile view. A mobile user has to go to one of the other pages and come back again to the documentation page to see the navigation panel. This issue is only noticed in mobile view and NOT desktop view. 

**To Reproduce**

1. Open the Internet Health Report application on a mobile device or alternatively use dev tools to test it in mobile view.
2. Click on the Documentation page and observe the navigation panel on the left side of the page.
3. The navigation bar appears initially but disappears after you click on any hyperlink.

**Expected behavior**
The scroll panel should be visible at all times in the mobile view as well for easier navigation through the website. This can be done by changing the status of 'showSidebar.' Also, we can add a small icon or button at the top-left corner of the documentation page. This icon/button can serve as a convenient trigger to display the navigation bar, allowing users to access the navigation panel when required while also not covering the screen on a mobile.

**Screenshots**

https://github.com/InternetHealthReport/ihr-website/assets/108648050/3b5f3eee-eee9-49a6-878c-ac6f18474526

**Additional context**
Please let me know if any other method might be more efficient in your opinion.

**Comment by JanviSinha2001** [comment]
@romain-fontugne Kindly guide. Thanks!

**Comment by MAVRICK-1** [comment]
https://github.com/InternetHealthReport/ihr-website/assets/146999057/d1f7bb7e-3944-417b-b6b8-58bef859fe59

You have to do horizontal slide for this

**Comment by JanviSinha2001** [comment]
Thanks for pointing, was checking on dev tools so could not verify. Closing this
