### ISSUE TITLE
Enhancement for IHR API 

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#702]
Following issues I have noticed:
 **Callback:**

-  using a callback-based approach for asynchronous operations, which could lead to callback hell (nested callbacks) and reduced code readability.

**Repeated Axios Configuration:**

- Axios configuration, including the creation of the Axios instance, was scattered across different methods. This could lead to redundancy and made it challenging to update configurations consistently.

**less use of async/await for asynchronous operations to improve code readability.**
**Inconsistent error handling**

**Comment by RickDeb2004** [comment]
@mohamedawnallah, @dpgiakatos what's your suggestion for this issue ?..should I work on this

**Comment by romain-fontugne** [comment]
could you give an example where you want to update the code?

**Comment by chaitanya-uniyal** [comment]
has this issue been fixed ??? if not then , i would like to work on this....

**Comment by mohamedawnallah** [comment]
I'm not sure if we need to refactor the Promise-based approach to async await syntactic sugar approach for handling the asynchronous operations since the codebase is a mix of both for achieving the same purpose.
