### ISSUE TITLE
feat : Duplicate Data Removal from API Fetch.

### ISSUE THREAD

**Issue by Animesh239** [InternetHealthReport/ihr-website#703]
**Is your feature request related to a problem? Please describe.**
When fetching data from the API, we encounter duplicate entries that impact the accuracy of our analysis. These duplicates need to be removed to ensure the integrity of the data and improve the overall quality of our application.

**Describe the solution you'd like**
I would like to request a feature that automatically identifies and removes duplicate entries from the data retrieved via the IHR API. A built-in mechanism for data deduplication would greatly enhance the usability of the API in our application.

![ihr_dup](https://github.com/InternetHealthReport/ihr-website/assets/115821028/959d8097-eedc-47ba-95fa-7310bf4e42ae)

**Implementation**
We will allow only one entry for every ASN ...

**Comment by romain-fontugne** [comment]
These are not duplicates, the prefixes are different.
