### ISSUE TITLE
Footer Overlapping with the Side Navbar in Mobile View.

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#705]
**Describe the bug**
Footer Overlapping with the Side Navbar in Mobile View.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us'
2. Click on switch to mobile view.'
3. Scroll At the bottom
4. Toggle Navbar

**Expected behavior**
Changing the Z index Should Solve the problem

**Screenshots**
![Footer](https://github.com/InternetHealthReport/ihr-website/assets/113178195/0fab9294-d542-4ba0-a3e2-873062fbbc87)

**Comment by ArnabBCA** [comment]
@mohamedawnallah can you assign me.

**Comment by ArnabBCA** [comment]
@romain-fontugne can you assign me

**Comment by romain-fontugne** [comment]
Is this really a problem? the link in the navbar are still visible and usable.

**Comment by ArnabBCA** [comment]
> Is this really a problem? the link in the navbar are still visible and usable. 

![Screenshot_2023-12-22-16-38-26-22_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/InternetHealthReport/ihr-website/assets/113178195/5672b050-deee-415f-b07d-39c6abd165de)

@romain-fontugne as you can see the links are not visible when the user is at the bottom of the page.

**Comment by romain-fontugne** [comment]
fine, go ahead!
