### ISSUE TITLE
Translation issue: Japanese translation is not working 

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#707]
**Describe the bug**
While clicking on the translator icon , if we select Japanese then the web page is not translated into that.

**Expected behavior**
The web page should be translated into Japanese.

**Screenshots**

![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/3643731a-b6db-49d5-a24e-26da437c5930)

https://github.com/InternetHealthReport/ihr-website/assets/113274631/f353bb0a-721d-4cc2-b628-cb889196641f

**After Changes:**
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/05c07070-4fb0-4e61-b1d1-ddc5d177483d)

**Comment by RickDeb2004** [comment]
@romain-fontugne @mohamedawnallah @dpgiakatos should i work on this?

**Comment by RickDeb2004** [comment]
@romain-fontugne if you allow me I can do the whole.

**Comment by MAVRICK-1** [comment]
> @romain-fontugne @mohamedawnallah @dpgiakatos should i work on this?

It's working but jp.json file is not translated yet

**Comment by RickDeb2004** [comment]
> > @romain-fontugne @mohamedawnallah @dpgiakatos should i work on this?
> 
> It's working but jp.json file is not translated yet

yaa ..if needed can change the whole jp.json

**Comment by MAVRICK-1** [comment]
> > > @romain-fontugne @mohamedawnallah @dpgiakatos should i work on this?
> > 
> > It's working but jp.json file is not translated yet
> 
> yaa ..if needed can change the whole jp.json

Duplicate issue #664

**Comment by romain-fontugne** [comment]
let's discuss this in #664 to avoid duplicate discussions
