### ISSUE TITLE
X (previously twitter) logo should be updated in the footer

### ISSUE THREAD

**Issue by Murdock9803** [InternetHealthReport/ihr-website#711]
**Describe the bug**
The footer of the website has old twitter logo, it should be changed to the new X logo.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us'
2. Scroll down to the bottom of the page
3. you can see the old twitter logo

**Expected behavior**
The footer should contain the updated logo for X (twitter)

**Screenshots**
![Screenshot 2023-12-22 220312](https://github.com/InternetHealthReport/ihr-website/assets/136724527/80eeb9d9-b082-4c0b-bc5a-51e0b744157b)

**Desktop :**

- OS: [ Windows ]
- Browser [ chrome ]
- Version [ 120 ]

**Additional context**
I would like to work on this. We will have to replace the logo with a new `svg` file.

**Comment by Murdock9803** [comment]
@romain-fontugne  Please assign me this issue.

**Comment by dpgiakatos** [comment]
closed by [#669](https://github.com/InternetHealthReport/ihr-website/pull/669)

**Comment by Murdock9803** [comment]
Ok sir
