### ISSUE TITLE
Typo : spelling of developers is wrong in the API page

### ISSUE THREAD

**Issue by Murdock9803** [InternetHealthReport/ihr-website#712]
**Describe the bug**
There is a typo in the API page. developers is written as developpers.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us'
2. Click on 'API' in navigation bar.
3. On the page, see the wrong spelling for developers as shown in the screenshot attached.

**Expected behavior**
The spelling should be corrected.

**Screenshots**
![Screenshot 2023-12-22 222817](https://github.com/InternetHealthReport/ihr-website/assets/136724527/36f2ba25-c616-43e7-901f-5133a5240a56)

**Desktop :**

- OS: [ Windows ]
- Browser [ chrome ]
- Version [ 120 ]

**Additional context**
I would like to work on this issue.

**Comment by dpgiakatos** [comment]
This typo originates from the swagger file that the webpage retrieves from https://ihr.iijlab.net/ihr/api/swagger.yaml?1234. This issue does not stem from this repository.

**Comment by Murdock9803** [comment]
Ok @dpgiakatos, Thanks for the clarification. Should I close the issue ?
