### ISSUE TITLE
Update Twitter logo

### ISSUE THREAD

**Issue by Ayushhgupta39** [InternetHealthReport/ihr-website#718]
**Is your feature request related to a problem? Please describe.**
The current Twitter logo in the IHR website is outdated as the platform has been rebranded to X. I suggest the current logo to be replaced with the new version to maintain visual consistency and reflect the latest branding.

![image](https://github.com/InternetHealthReport/ihr-website/assets/96309609/d247f5c1-69a2-495c-a89e-9aff6078505b)
![image](https://github.com/InternetHealthReport/ihr-website/assets/96309609/8c041ddd-8097-4433-81b8-bd531eee6507)

**Describe the solution you'd like**
Replace the old logo with the new one in the project files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

I would like to work on this issue.

**Comment by dpgiakatos** [comment]
closed by https://github.com/InternetHealthReport/ihr-website/pull/669

**Comment by Ayushhgupta39** [comment]
> closed by #669

Can you please go through this link https://ihr.iijlab.net/ihr/en-us and confirm that the changes are being reflected in the main website properly. Because as of now, I still see the old logo

**Comment by dpgiakatos** [comment]
We have not deployed the latest version from the master branch yet.

**Comment by Ayushhgupta39** [comment]
Okay okay got it. So for further changes in the project, Do we have to take reference from the #669 ?

**Comment by dpgiakatos** [comment]
The reference branch is the master. All successfully closed PRs are merged into the master branch.

**Comment by Ayushhgupta39** [comment]
Got it, Thank you so much
