### ISSUE TITLE
Horizontal overflow in the Data Access docs in mobile view

### ISSUE THREAD

**Issue by Ayushhgupta39** [InternetHealthReport/ihr-website#720]
**Is your feature request related to a problem? Please describe.**
In the documentation under the Data Access section, there is an overflow under the Scripting of REST API and Example of Python library, which is causing a horizontal overflow in the entire page. This issue is causing content to extend beyond the screen width, leading to a suboptimal user experience.
![image](https://github.com/InternetHealthReport/ihr-website/assets/96309609/3ee56801-8a47-439d-a3bb-2cfd64315577)
![image](https://github.com/InternetHealthReport/ihr-website/assets/96309609/804f1ffb-fd54-4712-be8a-9e6be5ad230b)

**Describe the solution you'd like**
The text should adapt to the mobile screen size and the overflow should be fixed. I'd like to work on this issue and fix this.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by YannyTwoo** [comment]
I'd like to resolve this issue. Can be assigned to it?

**Comment by Adii2202** [comment]
Fixed #720
https://github.com/InternetHealthReport/ihr-website/pull/738
