### ISSUE TITLE
Regression in Group by alternative keys mechanism in Global Report post vue.js 3 migration

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#722]
## Regression Issue Description
Following the migration of Global Report V2 to vue.js 3 (Pull Request #669), a regression has emerged regarding the Group by alternative keys mechanism. This issue was not present before the migration.

## Steps to Reproduce
1. Select any alarm type with multiple group-by option keys.
2. Group the alarm type by a reverse key (e.g., in Hegemony, group by `asn` instead of `origin_asn`).
3. Check the descriptive attributes for Anomalus Dependency (e.g., Country Name, Anomalus Dependency Name, etc.)—they will not be attached.
4. Observe the 'Neighbor Dependency Overview' sub-visualization—it will not be functional.
5. Even when grouping by the initial key, notice the disappearance of descriptive columns and similar issues with the 'Neighbor Dependency Overview' sub-visualization.

## Expected Outcome
Grouping alarms by alternative/option keys must work correctly.

## Recordings

https://github.com/InternetHealthReport/ihr-website/assets/69568555/096d0803-3731-4a5e-8d61-c0eb7eaef626

**Comment by dpgiakatos** [comment]
closed by https://github.com/InternetHealthReport/ihr-website/pull/717
