### ISSUE TITLE
Feature Request: Enhance Mobile Chart Interaction for Improved User Experience

### ISSUE THREAD

**Issue by abdulrehmanjaved-1** [InternetHealthReport/ihr-website#730]
**Is your feature request related to a problem? Please describe.**
In the mobile web view, when there are a large number of traces, clicking on the chart line to view details results in the details covering the remaining chart. This creates a bad user experience.

**Describe the solution you'd like**
I suggest enhancing the user experience by implementing a solution where clicking outside the chart component hides the displayed details. This would provide a smoother interaction flow, aligning with user expectations, and significantly improve overall usability.

**Describe alternatives you've considered**
I have considered and implemented the following alternative:

1. **Preventing the Default Behavior using the `preventDefault` Method:**
   - I successfully addressed the issue by using the `preventDefault` method. This approach allows users to see details when clicking on chart lines while preventing the details from being shown when clicking anywhere outside. This solution aligns with the desired user experience and effectively resolves the problem.

No additional alternatives are currently being considered, as the `preventDefault` method has proven to be a suitable and efficient solution.

**Additional context**
I have attached screenshots illustrating the current issue.

![Screenshot from 2024-01-03 09-51-12](https://github.com/InternetHealthReport/ihr-website/assets/136925246/ecc27696-b6e2-46c3-a772-c72c48633a05)

Appreciate your consideration. Would be grateful if you could assign this issue to me. Thanks.

**Comment by mohamedawnallah** [comment]
Has been addressed here:
https://github.com/InternetHealthReport/ihr-website/issues/665#issuecomment-1851840264

**Comment by abdulrehmanjaved-1** [comment]
Thanks for mentioning #665. However, this enhancement isn't limited to the Global Report page; it's aimed at improving the ReactiveChart component, utilized across multiple pages in the web app. Appreciate your understanding.

**Comment by richardshaju** [comment]
@mohamedawnallah  Can I work on this issue?

**Comment by dpgiakatos** [comment]
The responsiveness of the site is not a priority, as it contains a lot of information and complex charts that require interaction on a larger screen.
