### ISSUE TITLE
Twitter logo should be changed 

### ISSUE THREAD

**Issue by ayan-joshi** [InternetHealthReport/ihr-website#731]
**Describe the bug**
![Screenshot 2024-01-08 114226](https://github.com/InternetHealthReport/ihr-website/assets/96243602/3d4d1bd8-5382-40b3-bdbb-a2f37469a2fe)

As twitter logo is changed , this need to be fixed 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign me this issue I'll fix this @romain-fontugne

**Comment by dpgiakatos** [comment]
closed by https://github.com/InternetHealthReport/ihr-website/pull/669
