### ISSUE TITLE
Update Installation Tutorial Video for Vue 3.js Compatibility

### ISSUE THREAD

**Issue by dpgiakatos** [InternetHealthReport/ihr-website#733]
**Is your feature request related to a problem? Please describe.**
In the `README.md` file, specifically in the "Setup" section, there is a link directing users to a YouTube video tutorial for installing the IHR app locally and getting started with contributions. However, the existing video instructions are outdated, as they use commands tailored for the Vue 2.js project.

**Describe the solution you'd like**
To ensure accuracy and alignment with the current project structure (Vue 3.js), we need to create a new version of the installation tutorial video. The updated video should provide step-by-step instructions using the correct Vue 3.js commands.

**Comment by dpgiakatos** [comment]
It is preferable to have both voice narration and captions in the video, not just captions. We aim to create a comprehensive tutorial video similar to the old one.

**Comment by mohamedawnallah** [comment]
I don't think we need to create/update a video for installing `ihr-website` the installation process is already found in our `README.md` file and it works fine for all UNIX-based systems. That said I think having `INSTALL.md` file would be better as It would be more maintainable and easy to edit in an open-source way.

**Comment by romain-fontugne** [comment]
Yes, I agree we don't really need a video. This was a voluntary initiative to help new contributors but again it is not really needed. That said I also agree with the issue raised by @dpgiakatos , if the video is misleading then we should do something about it,  removing the link could be enough :)
