### ISSUE TITLE
Create Website Shortcut for IHR

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#734]
**As a user, I want to have a convenient shortcut for quick access to IHR (replace with the actual website URL). This can be achieved by implementing a simple web shortcut that users can add to their home screens or bookmarks bar.**

**Requirements:**

1. The shortcut should have an easily recognizable icon representing IHR.
2. Users should be able to add the shortcut to their home screens on both mobile and desktop browsers.
3. Ensure that the shortcut is compatible with popular browsers such as Chrome, Firefox, Safari, and Edge.
4. The shortcut should open IHR in a new tab/window when clicked.

for reference: https://www.brandeis.edu/its/support/website-shortcut.html

@dpgiakatos if you consider it a good idea, I can give you the HLD for this .
pls review it.

**Comment by mohamedawnallah** [comment]
## Concern Regarding Feature Necessity

I believe the proposed feature of adding a website as a widget to the home screen or favoriting it is already available in most popular web browsers. Therefore, I don't think it is necessary to implement.

## Example in DuckDuckGo Browser
As an illustration, the screenshot below demonstrates adding "ihr-website" to the home screen using the DuckDuckGo browser on an Android device by clicking on `Add to Screen`:
<img width="102" alt="Screenshot 2024-01-14 at 9 00 22 PM" src="https://github.com/InternetHealthReport/ihr-website/assets/69568555/a6f2f32c-08e2-4cce-bb2a-bca90047c8db">

**Comment by mohamedawnallah** [comment]
@dpgiakatos Should we close this issue ?

**Comment by dpgiakatos** [comment]
Yes
