### ISSUE TITLE
Inconsistent Color Scale Displayed on World Map When Clicking on a Country in Global Report Page

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#735]
**Describe the bug**
The issue pertains to the inconsistency in maintaining the color scale when a country is clicked on the world map, both in the main data visualization and the sub-world map data visualization.

**To Reproduce**
Follow these steps to replicate the behavior:

1. Navigate to the Global Report page.
2. Observe the color scale for a specific country (e.g., Brazil).
3. Click on the selected country (Brazil).
4. Note that the color scale does not match the expected scale and differs from the state before clicking.

**Expected behavior**
The color scale for a given country should remain consistent, both before and after clicking.

**Screenshots**
The issue is illustrated in the following screenshot, where Brazil, initially displaying 689 alarms in yellow, exhibits a different color after clicking.
![2024-01-14_20-46](https://github.com/InternetHealthReport/ihr-website/assets/69568555/a591b792-800e-4685-9596-36b8387578e4)

**Comment by MAVRICK-1** [comment]
@mohamedawnallah can you assign me this? :-)

**Comment by mohamedawnallah** [comment]
Thanks @MAVRICK-1 for your interest! Before assigning this to you, How would you tackle it?

**Comment by MAVRICK-1** [comment]
> Thanks @MAVRICK-1 for your interest! Before assigning this to you, How would you tackle it?

Adjust the choropleth map and color bar based on Alarm Counts. By ensuring that the color scales match for both the map trace and the color bar in the layout.

**Comment by MAVRICK-1** [comment]
I know basic plotlyjs, I can go through the documentation and fix this

**Comment by RickDeb2004** [comment]
@mohamedawnallah @MAVRICK-1 I have a good experience in plotlyjs , can fix this issue .

**Comment by MAVRICK-1** [comment]
> @mohamedawnallah @MAVRICK-1 I have a good experience in plotlyjs , can fix this issue .
> 

Anyways you can go for it , I am currently working on other issues

**Comment by mohamedawnallah** [comment]
Go for it @RickDeb2004

**Comment by RickDeb2004** [comment]
> > @mohamedawnallah @MAVRICK-1 I have a good experience in plotlyjs , can fix this issue .
> 
> Anyways you can go for it , I am currently working on other issues

Thank you

**Comment by githyuvi** [comment]
@mohamedawnallah I see this issue is still not closed yet. Can I work on it as I have found the solution. 
Additionally, Reactive Chart and its parent components are getting rendered multiple times making the whole thing very slow.

**Comment by RickDeb2004** [comment]
> @mohamedawnallah I see this issue is still not closed yet. Can I work on it as I have found the solution. 
> Additionally, Reactive Chart and its parent components are getting rendered multiple times making the whole thing very slow.

I am working on it...and it's almost done...as I am not making a PR now..by EOD I will push my PR .

**Comment by githyuvi** [comment]
@mohamedawnallah I am not able to add reviewer and link my PR with this issue

**Comment by mohamedawnallah** [comment]
@githyuvi Thanks anyway for your PR but please don't submit a PR while others have explicitly mentioned that they are currently working on this issue and assigned to it. That said I'm not sure if @RickDeb2004 resolved this issue?

**Comment by mohamedawnallah** [comment]
> Additionally, Reactive Chart and its parent components are getting rendered multiple times making the whole thing very slow.

@githyuvi this sounds a good catch! Since Reactive Chart is a reusable component across multiple pages/routes It would be nice if we create a specific issue for it following the issue template to get more context and understanding about the issue and when it happens and if it is a legimitate issue feel free to work on it :)

**Comment by githyuvi** [comment]
@mohamedawnallah As this issue has been open for so long. Can you assign this to me now?

**Comment by RickDeb2004** [comment]
> @mohamedawnallah As this issue has been open for so long. Can you assign this to me now?

I am working on this issue ..got some problem while pushing PR 
@githyuvi @mohamedawnallah 
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/561210b8-4161-490c-8d74-f8e3653a9628)

**Comment by mohamedawnallah** [comment]
@RickDeb2004 Since husky doesn't give a full trace of the error (as shown in the screenshoot) and also in https://github.com/typicode/husky/issues/1014 we could  temporary something like this thread on stackoverflow:
https://stackoverflow.com/a/70529234

**Comment by RickDeb2004** [comment]
@dpgiakatos Don't know why not the colors or the countries are not shown in the map
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/9d313b20-67fd-4212-9776-3dbcd10dbbd8)

**Comment by dpgiakatos** [comment]
It takes some time to fetch and load the data. I just tested it now, and the visualization is working fine.
