### ISSUE TITLE
BGPlay is stuck

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#74]
**Describe the bug**
We used to have a working version on BGPlay on IHR website. Somehow this is not working anymore.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/networks/AS2497
2. Click on the AS dependency graph
3. Scroll down to the table below the graph and click on 'AS GRAPH'
4. The message 'Reconstructing the history.' is shown indefinitely and no graph appear

**Expected behavior**
We are supposed to see the BGPlay graph: https://stat.ripe.net/widget/bgplay#w.resource=2497

**Desktop (please complete the following information):**

- OS: linux
- Browser: brave

**Comment by VenomFate-619** [comment]
There is no option for 'AS GRAPH' present.

**Comment by thisiskaransgit** [comment]
Hey @VenomFate-619, just do this
1. Go to https://ihr.iijlab.net/ihr/en-us/networks/AS2497

2. Click on any of the traces of the Graph 
![Screenshot from 2022-12-23 23-37-47](https://user-images.githubusercontent.com/92504666/209391235-4049a07a-39b8-4fa4-b95a-6fd4ca402cf3.png)

3. Scroll down, you will be able to see the option for AS-Graph
![Screenshot from 2022-12-23 23-38-38](https://user-images.githubusercontent.com/92504666/209391351-96f9bcbc-d24e-43e4-8a7f-17793ac5d26d.png)

**Comment by romain-fontugne** [comment]
I have been told that we should directly use bgplay code (https://github.com/massimocandela/BGPlay). Currently we are using a version provided by RIPE and that one seem to have some issues

**Comment by Rithvik-padma** [comment]
Can I get more details about this issue and a few suggestions on how to resolve the bug @romain-fontugne.

**Comment by romain-fontugne** [comment]
As described above by @thisiskaransgit we have a tab to show BGPlay. The code we are using is provided by ripe, but I think instead of this we should try to integrate BGPlay code (https://github.com/massimocandela/BGPlay) directly to IHR website

**Comment by J0SAL** [comment]
Hey @romain-fontugne, I'm a beginner to opensource and would love to work on this issue, could you assign this to me and some ideas on how to solve it?

**Comment by romain-fontugne** [comment]
to resolve this issue you'll have to look at BGPlay code first: https://github.com/massimocandela/BGPlay
Try to get BGPlay working on its own and then try to integrate it with IHR website

**Comment by VenomFate-619** [comment]
I  tried to resolve this.
my approach to fix this is as follows:-
need to host the bgplay code on a server, I think forking the code and using that GitHub link would work
need to change the BGPLAY_PROJECT_URL   in bgplayjs-main-widget.js fike of bgplay repo, this link might be like 
![image](https://user-images.githubusercontent.com/67755128/217331221-099654bd-045f-43c1-aef1-37b23d784a93.png)

https://github.com/InternetHealthReport/bgplay
at frontend, we need to add bg-play repo link in the libraries

![image](https://user-images.githubusercontent.com/67755128/217331293-03c9a931-6037-4d02-b54d-fa214c5eb6ec.png)

![image](https://user-images.githubusercontent.com/67755128/217331342-0edc1502-c35c-4a2d-9a5a-772a1fd946c3.png)


The following issue needs to be handled:
the size of the widget currently is going too big for the container and if we make it 
the loading time, for a while a white screen is coming as it is downloading the js files
not able to find an equalizing to this.bgplay.reload()  
the widget returns the following
```
{
    "domId": "bgplay",
    "initialParams": {
        "width": 1100,
        "height": 800
    },
    "queryParams": {
        "resource": "193.0.0.0/21",
        "collectorPeers": "all",
        "unix_timestamps": "TRUE",
        "showResourceController": true,
        "ignoreReannouncements": "true",
        "rrcs": "10",
        "type": "bgp"
    },
"shell": {
get_params: ƒ (),
set_params: ƒ (params)
}
}
```

if this looks fine can I take up that issue?

**Comment by romain-fontugne** [comment]
@VenomFate-619 I have assigned you for this issue

**Comment by VenomFate-619** [comment]
@romain-fontugne do close this issue

**Comment by romain-fontugne** [comment]
yep, thanks again for fixing this!
