### ISSUE TITLE
Add World Map for Country Selection in Country Report

### ISSUE THREAD

**Issue by Animesh239** [InternetHealthReport/ihr-website#740]
**Is your feature request related to a problem? Please describe.**
 - Currently, the Country Report feature requires users to manually enter the country name in a text field. This can be error-prone and time-consuming, especially for users who are not familiar with country names or spellings.
 - I propose adding a world map to the Country Report feature. This would allow users to visually select the country they are interested in, which would be more intuitive and user-friendly.

**Describe the solution you'd like**
- Integrate a world map using plotly or d3js, into the Country Report interface.
- Allow users to click on a country on the map to select it.
- Once a country is selected, populate the corresponding country name in the text field.

## The world map will be displayed here
![ihr_cr](https://github.com/InternetHealthReport/ihr-website/assets/115821028/179313be-42ca-4896-bcc6-eb438f5cf249)

**Comment by Animesh239** [comment]
@dpgiakatos @romain-fontugne

**Comment by romain-fontugne** [comment]
That's a good idea. Please go for it.
