### ISSUE TITLE
website overflow in x direction looks weired.

### ISSUE THREAD

**Issue by Praashh** [InternetHealthReport/ihr-website#742]
**Describe the bug**
When you go to IHR site, in big screen it overflowing in x direction which looks weired.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/
2. See the behaviour

**Expected behavior**
It should not be overlow.

**Screenshots**

it is the issue
[Screencast from 22-02-24 01:00:20 PM IST.webm](https://github.com/InternetHealthReport/ihr-website/assets/99237795/2217202b-d330-4cab-95a0-97ea30214072)

this should be the expected behaviour
[Screencast from 22-02-24 01:16:02 PM IST.webm](https://github.com/InternetHealthReport/ihr-website/assets/99237795/ae91fc43-e304-45db-9872-16133018e335)

**Comment by Praashh** [comment]
I am happy to take this.

**Comment by dpgiakatos** [comment]
closed #669

The deployed version is the vue2js. The master branch has the new version.
