### ISSUE TITLE
Adding World Map for country selection  for Network Delays During National Lockdowns

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#745]
**Description:**
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/042dc596-4158-48a3-aa94-0a12fa40c8c3)
at this network delays during lock downs segment can have the world map for country selection  with this dropdown option.
![image](https://github.com/InternetHealthReport/ihr-website/assets/113274631/053bab16-ff82-40f5-851c-1e928975ff09)
like this but the color chart is not much important here for this network delay section.

What's your view on this ?
@romain-fontugne @dpgiakatos

**Comment by 0xAnon0602** [comment]
There is major update going on the website through #719 
So let's wait for it to get merge before adding anything on the website.

**Comment by dpgiakatos** [comment]
In this page, we only have information for some countries. Including a map with all the countries of the world would be confusing for the user.
