### ISSUE TITLE
Loading page issue

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#752]
The loading page on mobile seems a little inconsistent.

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/031d506c-4d66-4b5b-a98a-c0f568c89409)

I'm not sure if this is the top priority, but I would like to work on fixing it.

**Comment by dpgiakatos** [comment]
This is a low priority since the ihr-website is not optimized for smartphones. However, if you wish to resolve it, feel free to do so. My suggestion is to decrease the font size and the size of the logo when the screen becomes smaller. Please comment if you would like to be assigned. Thank you!

**Comment by 0xAnon0602** [comment]
@dpgiakatos 
Yes please assign it to me as it will not take much time to fix it :)
