### ISSUE TITLE
Search Bar result showing priority 

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#753]
When you search for something that includes a country name, the country is shown near the bottom in the search bar

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/afd01568-d566-4507-ba85-4225679d404f)

Shouldn't the priority be to show the country at the top of the search bar?

**Comment by dpgiakatos** [comment]
The search bar searches for AS, IXP, Prefix, Hostname, and Country. When you type an alphanumeric character, it starts searching for potential matches. In your case, as you can observe in the results, the substring "India" is included in the majority of results. This means that you are not only searching for a country. Thus, this is not an issue.
