### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#754]
I think we need to make a lot of changes to the [Documentation](https://ihr.iijlab.net/ihr/en-us/documentation) of the website after this new version, such as including IYP data using CYPHER QUERY and other enhancements.

I would like to work on updating the documentation. Could you guide me on what major changes need to be added, replaced, or deleted?

**Comment by dpgiakatos** [comment]
Yes, indeed, but I believe it's important for us, as maintainers, to address this issue to ensure the validity of the content.
