### ISSUE TITLE
Selected Dropdown value is not getting populated

### ISSUE THREAD

**Issue by sahshank01** [InternetHealthReport/ihr-website#76]
**Describe the bug**
On the COVID19 report page, after selecting a country from the dropdown, the dropdown is not getting populated with the selected country.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/covid19'.
2. Click on the 'Select a Country' Dropdown and select any country.

**Expected behavior**
When we select any country from the dropdown, it should get populated with the selected value.

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Chrome

**Comment by sahshank01** [comment]
Hi @romain-fontugne, please assign it to me, I am working on it.

**Comment by romain-fontugne** [comment]
thanks! I think I broke this in the latest version
