### ISSUE TITLE
Implement Notification System for Network Events

### ISSUE THREAD

**Issue by pankaj87072** [InternetHealthReport/ihr-website#762]
Currently, users of the 'IHR' website have no way of receiving real-time updates or alerts about network events or anomalies that affect their interests, such as outages, congestion, or routing changes.
Implement a notification system that allows users to subscribe to alerts or updates on the events.

**Comment by pankaj87072** [comment]
@romain-fontugne @m-appel any suggestions?

**Comment by dpgiakatos** [comment]
Implementing a notification system is a major change for the website. I suggest we discuss it internally first among the maintainers before proceeding with this issue.

**Comment by pankaj87072** [comment]
@dpgiakatos yes you are right i just suggested a feature which i think lacks in the site and should be added

**Comment by pankaj87072** [comment]
@dpgiakatos should i close this issue or just leave it for the discussion?
