### ISSUE TITLE
PeeringdbNetID returning null

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#772]
![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/db64d8f0-5951-495b-ad92-19d33fddb29e)

The peeringDB link on ASOverview component is returning undefined because the query used to get the peeringdbNetID is returning null from the IYP.

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/473f708e-9c4a-403d-97b4-8c131cb9fe47)

**Comment by 0xAnon0602** [comment]
The one solution I can think of is showing the peeringdb link only when the ID we get from IYP is not null.

**Comment by dpgiakatos** [comment]
For this bug, we had two issues:
1. We bound the corresponding value from the object incorrectly (fixed in #773).
2. The bug you mentioned in this issue. Indeed, in some ASes, we have a null PeeringDB ID. Let me check it first, and I will come back to this issue.

**Comment by 0xAnon0602** [comment]
Yeah that's why I suggested to add a filter to show the link only if the return data is not null

**Comment by dpgiakatos** [comment]
When we receive null from the IYP, we should disable the link. You can learn more about how to disable links by visiting the following link: https://css-tricks.com/how-to-disable-links/

I am assigning this to you right?

**Comment by 0xAnon0602** [comment]
Yes, assign it to me

**Comment by 0xAnon0602** [comment]
By disabling the link do you mean just showing it is as a normal text or completely not showing it.

Also IXPOverview also uses similar query to get PeeringdbIXID 
Should I also add the filter there too ?

**Comment by dpgiakatos** [comment]
I reconsidered, let's just remove the corresponding links when we have null values. Also, please add it to the PeeringdbIXID.
For example, for AS55836 (the one that we do not have a peeringdb), the external links should contain:
bgp.he.net
bgp.tools
radar.cloudflare.com
stat.ripe.net

And for AS2497, the external links should contain:
bgp.he.net
bgp.tools
peeringdb.com
radar.cloudflare.com
stat.ripe.net
