### ISSUE TITLE
Adding Slack Icon 

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#777]
Currently there is no **Slack** link on the homepage.

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/9d97a38d-41b3-4b6b-88e6-767bde67b62e)

**Comment by 0xAnon0602** [comment]
If this is something that needs to be implemented, then I can work on it.

**Comment by dpgiakatos** [comment]
It is not needed; someone can access Slack from the organization's README on GitHub.
