### ISSUE TITLE
Prefix Component Bug

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#778]
If someone searches for a **Prefix** and then tries to search for an **AS**, the Prefix component remains visible with an undefined value.

**Video showing the bug**

https://github.com/InternetHealthReport/ihr-website/assets/71931823/89f761d2-23aa-42bc-a50a-be678662957b

**Comment by romain-fontugne** [comment]
I have also stumbled on that bug. We should fix it asap.

**Comment by dpgiakatos** [comment]
There's a bug stemming from the routes change. I'll take care of it.

**Comment by dpgiakatos** [comment]
Fixed #779
