### ISSUE TITLE
Prevent to commit code with lint warnings and errors

### ISSUE THREAD

**Issue by akib22** [InternetHealthReport/ihr-website#78]
**Problem**
I found that lots of time when we are working on a project, we tend to forget to fix linting warnings and errors. This mistake makes our coding style inconsistent. Also, finding and fixing lint errors manually is very tedious. If we make the process automatic there is no chance to make the mistake.

**Solution**
Using the git `pre-commit` hook, I want to run the `lint` command to prevent the mistake. I like to use [husky](https://www.npmjs.com/package/husky) to achieve this.

Is it okay if I include the feature @romain-fontugne? If that is the case, please assign it to me.

**Comment by romain-fontugne** [comment]
Thanks, yes, I think we need to enforce it.
