### ISSUE TITLE
Network Delay 'accordion' is not getting collapsed

### ISSUE THREAD

**Issue by shashanksah143** [InternetHealthReport/ihr-website#79]
**Describe the bug**
In country report page, the 'network delay' accordion is not getting collapsed after clicking on the collapsed button. It is getting collapsed for a few milliseconds and then bounces back to its open state.

**To Reproduce**

1. Go to '(https://ihr.iijlab.net/ihr/en-us/countries)'
2. Select any country.
3. Scroll down to the 'Network Delay' accordion 
4.  Try to collapse the accordion 

**Expected behavior**
After clicking on the collapse icon, the accordion should get collapsed, just like the other two accordions present ('Network Dependency' and 'Route Origin Validation') on the page are behaving.

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Chrome

**Comment by shashanksah143** [comment]
@romain-fontugne sir, please assign it to me, I am working on this issue.

**Comment by romain-fontugne** [comment]
I cannot reprooduce that problem. It works for me on Linux/Brave

**Comment by shashanksah143** [comment]
@romain-fontugne, I am able to replicate the same issue on 
OS: Ubuntu 20.04.4 LTS
Browser: Mozilla Firefox 98.0.2

Wait for graphs to load the data completely (when the graphs are loading, the accordions are working fine), and then try to collapse the 'network delay' accordion. 

In my previous setup, the data for the country which I selected got cached, I think because of that I was able to replicate it in windows/chrome.

**Comment by Aniket762** [comment]
> @romain-fontugne, I am able to replicate the same issue on OS: Ubuntu 20.04.4 LTS Browser: Mozilla Firefox 98.0.2
> 
> Wait for graphs to load the data completely (when the graphs are loading, the accordions are working fine), and then try to collapse the 'network delay' accordion.
> 
> In my previous setup, the data for the country which I selected got cached, I think because of that I was able to replicate it in windows/chrome.

Hey, what's the current status on this? If you can still find the error can you please attach a screenshot?

**Comment by shashanksah143** [comment]
@Aniket762 Currently I am busy with some other work, If you want you can take this issue.
Are you able to replicate the issue?
Attaching a screenshot will not be helpful, as this bug is occurring on mouse click event.

**Comment by shashanksah143** [comment]
Please find the attached video link below of the bug. 
https://drive.google.com/file/d/1Jv42GlasS8bXYRpc_3CeQGGsIbmHPgN2/view?usp=sharing

**Comment by Aniket762** [comment]
> @Aniket762 Currently I am busy with some other work, If you want you can take this issue. Are you able to replicate the issue? Attaching a screenshot will not be helpful, as this bug is occurring on mouse click event.

Thanks a lot, @shashanksah143 for attaching the video. I would keep this issue open and whenever you get some time you can help us get it fixed.
