### ISSUE TITLE
Fix tracemon in NetworkReport

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#8]
Tracemon is currently not working for Forwarding anomalies

**Comment by romain-fontugne** [comment]
looks like tracemon is broken, ips show in a random order. This would require to fix tracemon first

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir, i would like to work on this.
Can you please give me some brief about the issue, it would be really helpful

**Comment by romain-fontugne** [comment]
I think this is not a problem anymore, thanks
