### ISSUE TITLE
Links in treemap are unpredictable

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#811]
**Describe the bug**
Some of the treemaps on IHR website link to a report page some don't. I think this is very confusing.

**To Reproduce**
For example:
1. go to https://ihr.iijlab.net/ihr/en/network/AS2497?af=4&last=3&date=2024-07-01&active=routing
2. clicking on any country in the 'Connected ASes' treemap opens the country page.

On the same page:
1. clicking on any country in the 'Originated Prefixes' treemap simply zoom on this.

**Expected behavior**
I think it would be more intuitive if clicking on the graph just zoomed in/out of the graph. Eventually, clicking on one of the label could send us to the corresponding report page.

**Comment by abansal15** [comment]
Hello @dpgiakatos @romain-fontugne if no one is working on this issue could you please asign this issue to me

**Comment by dpgiakatos** [comment]
Hello @abansal15 ! I have assigned this to you!

**Comment by abansal15** [comment]
Hello @dpgiakatos @romain-fontugne i have completed the issue but when i am trying to push my branch issue-811 then i am getiing permission issues could you please help me in resolving this.
![image](https://github.com/InternetHealthReport/ihr-website/assets/120590200/8a267d31-e1bc-4498-a0a3-8ad545b98892)

**Comment by MAVRICK-1** [comment]
@abansal15 , you should first fork the repository. Then, push your changes to a branch. Finally, raise a pull request (PR).

**Comment by abansal15** [comment]
> @abansal15 , you should first fork the repository. Then, push your changes to a branch. Finally, raise a pull request (PR).

yes i have forked the repository then when  i am pushing changes to the issue-811 branch i am getting that issue

**Comment by MAVRICK-1** [comment]
@abansal15 did you setup your SSH key?

**Comment by dpgiakatos** [comment]
According to the error, you tried to push to InternetHealthReport/ihr-website instead of your forked repository. Please read the documentation on how to fork, push, and create a pull request: https://docs.github.com/en/pull-requests

**Comment by abansal15** [comment]
> @abansal15 did you setup your SSH key?

yes

**Comment by abansal15** [comment]
@dpgiakatos i have raised the pr could you please review it

**Comment by dpgiakatos** [comment]
I removed the `beginner-friendly` tag, as this issue needs further investigation, according to the following comment on #812.

> This PR solves the problem with clicking in the 'Originated Prefixes' chart, but it does not address the expected behavior mentioned in the issue:
> 
> "I think it would be more intuitive if clicking on the graph just zoomed in/out of the graph. Eventually, clicking on one of the labels could send us to the corresponding report page."
> 
> Currently, the Plotly component cannot achieve this functionality—zooming in/out when clicking on the box and navigating when clicking on the label. Therefore, I will approve this PR as it fixes an existing bug, even though it does not resolve the corresponding issue.
> 
> I will revisit this issue after discussing it internally.
> 
> Thank you!
> 
> _Originally posted by @dpgiakatos in https://github.com/InternetHealthReport/ihr-website/pull/812#pullrequestreview-2152530459_

**Comment by abansal15** [comment]
@dpgiakatos i think that issue was on clicking the treemap graph of Originated Prefixes its only zomming in/out on clicking the label also but now after resolving the issue on clicking the label its redirecting to that country report page.
could you please tell me what more it should behave after you discussed it internally so that i can try to resolve the issue correctly.
Thanks.

**Comment by dpgiakatos** [comment]
We decided to enable navigation to another page only for leaf nodes. Therefore, we had to rewrite the functionality that handles clicks on the treemap. This issue has been resolved. Thank you all!
