### ISSUE TITLE
Metis deployment page disappeared

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#815]
**Describe the bug**
We had a page to show Metis results. It looks like that:
https://exp1.iijlab.net/ihr/en-us/metis/deployment

it seems that this page disappeared in a recent version of the website:
https://ihr.iijlab.net/ihr/en/metis/deployment

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en/metis/deployment

**Expected behavior**
https://exp1.iijlab.net/ihr/en-us/metis/deployment

**Comment by abansal15** [comment]
@romain-fontugne could you please describe the bug in more detail as your above all four links page are exact same

**Comment by romain-fontugne** [comment]
Nevermind, malte fixed that!
