### ISSUE TITLE
'Network Unreachable' message is not disappearing

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#819]
**Describe the bug**
In the monitoring tab of network reports, we have a 'network unreachable' message that appear for certain ASes. Once this message is shown, it won't disappear when we go to other reports.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en/network/AS567
2. Then in the search box type '2497' and click on 'Internet Initiative Japan'
3. Click on the Monitoring tab
4. See the 'network unreachable' message on top of the graph

**Expected behavior**
The visibility of the message should be reset every time the user browse to a different report.

**Screenshots**
![image](https://github.com/user-attachments/assets/11ebac3d-1d5d-4e39-83c1-40d221bfd664)

**Comment by dpgiakatos** [comment]
Fixed in https://github.com/InternetHealthReport/ihr-website/pull/820
