### ISSUE TITLE
Network delay graph showing negative values for median RTT in some countries

### ISSUE THREAD

**Issue by shashanksah143** [InternetHealthReport/ihr-website#82]
**Describe the bug**
For some countries, the median RTT values shown in the network delay graphs are in negative. 

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/countries/
2. Select the country as 'Netherlands'.
3. Scroll down to the 'Network delay' accordion.
4. Hover on the graph to see the median RTT values from AS33915 to Google (AS15169), for some timestamps values are in negative.

**Expected behavior**
The median RTT values displayed should be a non-negative number. 

**Screenshots**
![error](https://user-images.githubusercontent.com/102915015/161681819-6414853a-cd5e-4bdd-8b4b-2fd0eee377bf.jpg)

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Chrome

**Additional context**
As discussed with @romain-fontugne, The estimate can be below 0 in some cases it's weird but mathematically it is correct. But in frontend, it should be displayed as a positive value.
e.g. 
-0.56 should be displayed as abs(-0.56) = 0.56

**Comment by shashanksah143** [comment]
@romain-fontugne, I would like to work on this issue.

**Comment by romain-fontugne** [comment]
Thanks. Yes, let's show absolute values. I hope that will make it less confusing.
