### ISSUE TITLE
Data is not displayed in the ranking widget on the network page

### ISSUE THREAD

**Issue by dpgiakatos** [InternetHealthReport/ihr-website#821]
**Describe the bug**
The ranking values do not displayed in the chart.

**To Reproduce**

1. Go to network page
2. Search for AS131160
3. Go to Rankings tab

Or

Visit the following link:
https://ihr.iijlab.net/ihr/en/network/AS131160?af=4&last=3&date=2024-07-21&active=rankings

**Expected behavior**
We expected to display the ranking like this page:
https://ihr.iijlab.net/ihr/en/network/AS2497?af=4&last=3&date=2024-07-21&active=rankings

**Screenshots**
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/2f7b5668-9df6-421e-928e-d2770f355659">

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/9ef68ced-00d3-44f5-9b88-1656bffb2f8b">

**Comment by dpgiakatos** [comment]
Possible solution:
Adding a v-if in the HTML part. This way, if we do not have all the displayed rankings, we will always display the available ones.

**Comment by romain-fontugne** [comment]
I guess the widget is only showing rank that are lower than a certain value (100? or 50? or 20?). The reason is that being ranked 33349th in a ranking doesn't mean much. I think we have three options to address this:
1. we can still show the values (but as stated earlier it has little meaning
2. we show a message saying  "This network does not appear in the top 100 of any ranking."
3. we could have a better visualization for rankings, something more intuitive like a radar chart?

**Comment by romain-fontugne** [comment]
> Possible solution: Adding a v-if in the HTML part. This way, if we do not have all the displayed rankings, we will always display the available ones.

I'm not sure I understand? you want to show the 'data' tab when there is nothing to show in the 'chart' tab?

**Comment by dpgiakatos** [comment]
> > Possible solution: Adding a v-if in the HTML part. This way, if we do not have all the displayed rankings, we will always display the available ones.
> 
> I'm not sure I understand? you want to show the 'data' tab when there is nothing to show in the 'chart' tab?

Yes, this is what I mean.

**Comment by dpgiakatos** [comment]
> I guess the widget is only showing rank that are lower than a certain value (100? or 50? or 20?). The reason is that being ranked 33349th in a ranking doesn't mean much. I think we have three options to address this:
> 
>     1. we can still show the values (but as stated earlier it has little meaning
> 
>     2. we show a message saying  "This network does not appear in the top 100 of any ranking."
> 
>     3. we could have a better visualization for rankings, something more intuitive like a radar chart?

I agree with the first one. I disagree with the second one, as this will confuse the user. They will never go to the data tab if we show this message. The third option is a nice idea.

**Comment by dpgiakatos** [comment]
Ok!
