### ISSUE TITLE
Improve Contribution Guidelines in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by dpgiakatos** [InternetHealthReport/ihr-website#836]
To enhance the contribution experience for new and existing contributors, I suggest the following additions to the `CONTRIBUTING.md` file:
- **Overview of Libraries**: Provide a list of libraries used in the project, along with a brief description of each one and its purpose
- **Component Descriptions**: Include explanations of the main components of the project, detailing what each component does and how they interact with one another
- **Code Style Guidelines**: If applicable, outline any coding standards or style guides that contributors should follow
- **Testing Instructions**: Provide information on how to run tests

By including this information, we can make it easier for new contributors to understand the project structure and how they can contribute effectively.

**Comment by abansal15** [comment]
Hello @dpgiakatos can you please assign this issue to me ?

**Comment by dpgiakatos** [comment]
Thank you for your message. This issue will be addressed by the organization members, as they have a better understanding of the project's overall structure.

**Comment by abansal15** [comment]
okay @dpgiakatos
