### ISSUE TITLE
Font Sizes Issue for Larger Screens

### ISSUE THREAD

**Issue by dpgiakatos** [InternetHealthReport/ihr-website#844]
**Describe the bug**
When viewing the website on larger screens (e.g., 1440p), the font sizes for some elements appear too large, while others seem too small. 

**Expected solution**
Utilize `em`, `px`, or `%` units for font sizes to ensure consistent scaling across different screen sizes.

![image](https://github.com/user-attachments/assets/d4534a85-c0c4-4084-bfed-a2ee1964d530)

**Screenshots**
The following screenshot illustrates the difference in font sizes on a 1440p screen.

![image](https://github.com/user-attachments/assets/c0d5206e-c994-43f1-9da1-fbe326c36ecb)

**Comment by praj-jha** [comment]
hey i can fix this please assign it to me

**Comment by phiho1983** [comment]
Hi, I'd like to take care of this issue, this will be my first contribution.

**Comment by dpgiakatos** [comment]
I am assigning this task to you. You will find our latest code in the dev branch (https://github.com/InternetHealthReport/ihr-website/tree/dev). Before you start the implementation, please read our contribution guidelines first (https://github.com/InternetHealthReport/ihr-website/blob/dev/CONTRIBUTING.md). Thank you!

**Comment by dpgiakatos** [comment]
Hello! Do we have any updates on this?

**Comment by abansal15** [comment]
Hello @dpgiakatos if no one is working on this issue could you please it to me ?

**Comment by tejasathalye** [comment]
.take

**Comment by dpgiakatos** [comment]
Hi, let's wait a few more days. If we don't receive a reply from the assigner, I will assign this to you if you are still interested. Thanks!

**Comment by abansal15** [comment]
Okay @dpgiakatos you can assign me after few days i am still interested in it
Thanks

**Comment by dpgiakatos** [comment]
Hello, since we have not received any reply from the assigner, I am making this issue available for assignment again. Thank you.

**Comment by itsUndefined** [comment]
I'd like to take a look at the issue

**Comment by dpgiakatos** [comment]
Hello @itsUndefined, I am assigning this to you since @abansal15 is currently addressing another issue in our website. Thank you!

**Comment by sakshamgupta912** [comment]
Hey @dpgiakatos , what is the status for this ? i would like to contribute on this problem

**Comment by itsUndefined** [comment]
Hi and sorry for the delay. I'll send a PR tomorrow for this.

**Comment by dpgiakatos** [comment]
It's OK, looking forward for the PR.
