### ISSUE TITLE
Improve the loading UI of Your connection

### ISSUE THREAD

**Issue by 0xAnon0602** [InternetHealthReport/ihr-website#847]
**Describe the bug**
When someone loads the main page of the website, the "Your Connection" dialog box glitches during loading.

https://github.com/user-attachments/assets/c3cfa730-58df-4ef5-aa3d-6899b9304341

**Comment by abansal15** [comment]
Hello @0xAnon0602 @dpgiakatos could you please assign this issue to me .

**Comment by 0xAnon0602** [comment]
@abansal15 Assigned

**Comment by abansal15** [comment]
Hello @0xAnon0602 i have raised the pr could you please review it
https://github.com/InternetHealthReport/ihr-website/pull/848

**Comment by dpgiakatos** [comment]
Hi, I will take care of the code review. Thank you!

**Comment by abansal15** [comment]
Thanks a lot 
Does I have to do something else  ?

**Comment by abansal15** [comment]
@dpgiakatos according to the contribution guideline should i have to make the changes by creating a new branch with that issue number or as you told in the dev branch ?
![image](https://github.com/user-attachments/assets/728905b7-d172-452b-a8ce-c121026be516)

**Comment by dpgiakatos** [comment]
You need to follow the contribution guidelines. I wanted to briefly explain that we are working with the dev branch, and all our changes should be synchronized with it. Please make sure to follow our contribution guidelines. Thank you!

**Comment by abansal15** [comment]
@dpgiakatos i have again raised the pr following the guidelines i hope this time i have not make any mistakes
