### ISSUE TITLE
cards heights and link position is not equal 

### ISSUE THREAD

**Issue by Chayan8837** [InternetHealthReport/ihr-website#851]
**Describe the bug**
 at the main page , cards heights are not equal and the links are not at same position for all cards 

**To Reproduce**

1. Go to  main page 

**Expected behavior**
heights  and position of all likes should equal for all cards

**Screenshots**
![Screenshot (812)](https://github.com/user-attachments/assets/caf5e880-3e61-49cc-a7ed-e8959e1bd932)

**Desktop (please complete the following information):**

- OS: Windows
- Browser  chrome

**Comment by abansal15** [comment]
@Chayan8837 i think box heights cannot be made equal as content is not same in all the boxes if we make the height equal then we have to increase the width by this may be 2 boxes will not be in fitted in the same row... 
What's your point of view?

**Comment by Chayan8837** [comment]
yes  you right, but we can set the links positions at the bottom of the cards

**Comment by dpgiakatos** [comment]
Hello! I believe we can improve this section. If we replace the cards with something like the image below, it could improve the website. What are your thoughts?
![image](https://github.com/user-attachments/assets/5fd0d729-dc4a-4c6c-ac7e-a8fecd03a25d)
P.S. The image is sourced from the following: https://colorlib.com/wp/template/rango/

**Comment by Chayan8837** [comment]
Yes , it will be nice if we use this design ...

**Comment by Chayan8837** [comment]
![Screenshot (817)](https://github.com/user-attachments/assets/afe9d394-0e89-40a7-beed-ebc736952898)
the middle card will be highlighted and the animation is smooth
![Screenshot (818)](https://github.com/user-attachments/assets/f6a8992d-d892-4a5a-b95a-5ec44bbe708e)

I've created a component for the slider. If you'd prefer all the code in one file, I can change it. Also, if you'd like any improvements in the design, let me know. Should I create a PR?

**Comment by dpgiakatos** [comment]
Hi, thank you for your interest in implementing changes. However, please refrain from making any modifications unless you are assigned to this task. We are still discussing the UI changes for the landing page, and there is a possibility that the new design may be changed or dropped in favor of the old one. We appreciate your patience and understanding. Thank you.
