### ISSUE TITLE
For a better user experience, the dropdown should appear on hover

### ISSUE THREAD

**Issue by Chayan8837** [InternetHealthReport/ihr-website#860]
# Feature Request: Dropdown Hover Interaction

## Is your feature request related to a problem? Please describe.
I'm always frustrated when dropdown menus require an extra click to open. It disrupts the user experience, especially when quick navigation is needed.

## Describe the solution you'd like
I would like the dropdown to open automatically when hovered over, rather than requiring a click. This would make navigation more seamless and improve the overall user experience.

## Describe alternatives you've considered
An alternative could be using a small icon or indicator next to the dropdown that makes it more intuitive to click, though this still adds an extra step compared to hover-based interaction.

## Additional context
Implementing the hover effect would make navigation quicker for users and reduce unnecessary clicks. This approach is often seen in modern websites for enhancing usability. Here's a screenshot of a similar feature implemented on other sites:

![Screenshot (819)](https://github.com/user-attachments/assets/84340b2a-9b31-41aa-9515-d4620074d98f)

**Comment by dpgiakatos** [comment]
This is not a problem. In fact, it represents the opposite behavior in HCI. By allowing a mouse click to open a dropdown menu, the website becomes more accessible.
