### ISSUE TITLE
"Network is Unreachable" label not cleared when switching report timeframe

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/ihr-website#864]
**Describe the bug**
When selecting a report timeframe during which no AS Hegemony data is available, a message "Network is Unreachable" or "No Data Available" is displayed.
However, choosing a different timeframe *with* data, does not clear this message.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en/network/AS2497?af=4&last=3&date=2024-09-28&active=monitoring
2. Observe "No Data Available" message
3. Select a different date (e.g., 2024-09-29)
4. "No Data Available" message will be overlaying the graph

**Expected behavior**
"No Data Available" message should disappear.

**Screenshots**

![image](https://github.com/user-attachments/assets/3922fd72-9b1b-4226-976f-be98395063ad)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Tested on Firefox 131.0.3 and Chromium 130.0.6723.69

**Additional context**

I also noticed that the message differs depending on the way the page is loaded. Accessing the page via a link (like above) results in "No Data Available". Navigating from a timeframe with data to one without results in "Network is Unreachable".

**Comment by abansal15** [comment]
Hello @m-appel  @dpgiakatos  can you please assign this issue to me

**Comment by dpgiakatos** [comment]
Can you describe how you plan to address it?

**Comment by ArnabBCA** [comment]
Hi @dpgiakatos, I would like to work on this issue, I have tested my solution and it appears that resetting before every fetch by adding layout.value.annotations = [] in the function `fetchHegemony` solves this issue https://github.com/InternetHealthReport/ihr-website/blob/65b495915b4fb5aee088377954a00c9e1033dfe3/src/components/charts/AsInterdependenciesChart.vue#L338C1-L340C27

**Comment by dpgiakatos** [comment]
Sounds good the proposed solution!
